### PR TITLE
JBPM-5758 - Replace kie-internal QueryContext with the one from kie-a…

### PR DESCRIPTION
**Pull request by tsurdilo**
…pi in CaseRuntimeDataService

### CODE REVIEW

**Comment by tsurdilo** [comment]
depends on https://github.com/kiegroup/jbpm/pull/787

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
@mswiderski didnt include a file in commit..fixing

**Comment by mswiderski** [comment]
@tsurdilo there seems to be compilation error, could you please take a look?

**Comment by tsurdilo** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
@mswiderski i think the build did not pick up changes in the jbpm pr.

**Comment by psiroky** [comment]
@tsurdilo correct. You are using different branch names, so the PRs weren't matched.

**Comment by tsurdilo** [comment]
@psiroky ok - should be merge https://github.com/kiegroup/jbpm/pull/787 first or should i redo this pr with matching branch name ?

**Comment by psiroky** [comment]
@tsurdilo not sure. Is the jBPM PR standalone so that we don't have to merge it together with this one? If so, you can just wait for the jBPM till it gets merged.

**Comment by tsurdilo** [comment]
@psiroky thanks! did new pr https://github.com/kiegroup/droolsjbpm-integration/pull/873 that has matching branch name. sorry for the inconvenience here

**Pull request closed without merging**
