### PR TITLE
[JBPM-9540] Make kie-server-services-jbpm-cluster module compatible w…

### PR DESCRIPTION
**Pull request by sutaakar**
…ith JDK 11

Signed-off-by: Karel Suta <ksuta@redhat.com>

**Thank you for submitting this pull request**

**JIRA**: 

[JBPM-9540](https://issues.redhat.com/browse/JBPM-9540)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
thx @sutaakar good catch

**Comment by sutaakar** [comment]
Looks like the test failures are caused by port clash and race condition for Hibernate transaction.
Jenkins retest this please

**Comment by sutaakar** [comment]
@elguardian Could you please merge?
The GitHub Action failure for Java 11 is unrelated.

**Pull request merged**
