### PR TITLE
JBPM-6373 - KIE Server improvements for cloud based deployments

### PR DESCRIPTION
**Pull request by mswiderski**
@tsurdilo @sutaakar whenever you guys have a moment

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
test fail on jenkins is unrelated to the changes in pr

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
