### PR TITLE
JBPM-5710 KIE Persistence Cleanup

### PR DESCRIPTION
**Pull request by marianbuenosayres**
This set of PRs is a set of modifications to allow multiple persistences without all of them depending on JPA:

- Creating drools-persistence-api and jbpm-persistence-api
- SingleSessionCommandService refactors
- PersistenceContext and ProcessPersistenceContext refactors:
- TaskPersistenceContext refactors
- Changes in the current persistence model interfaces
- TimerJobFactoryManager / TimerService refactors

### CODE REVIEW

**Comment by mswiderski** [comment]
this single test failure looks like it's related, here you can find details copied: http://pastebin.com/LcxMyjdD do you mind taking a look?

**Comment by marianbuenosayres** [comment]
@mswiderski can I get a transcript of the output? The public link doesn't seem to be working anymore

**Comment by mswiderski** [comment]
looks like OSGi manifest related issue:

```
org.osgi.framework.BundleException: Unresolved constraint in bundle org.jbpm.runtime.manager [153]: Unable to resolve 153.0: missing requirement [153.0] osgi.wiring.package; (osgi.wiring.package=org.drools.persistence.jta)
```

all failed tests:
```
Test Result (13 failures / +13)
org.kie.eap.test.KieEapModulesSmokeIT.org.kie.eap.test.KieEapModulesSmokeIT
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[5]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[6]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[8]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[9]
org.kie.karaf.itest.KieSpringDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringMetaInfAppContextKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManagerWithPersistence
org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManager
org.kie.karaf.itest.RuntimeManagerFeatureKarafIntegrationTest.testJbpmRuntimeManager
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieSession
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieBase
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieSessionDefaultType
```

do you need more?

**Comment by marianbuenosayres** [comment]
@mswiderski could this fail be due to missing the other builds of the other repos? I was able to build locally

**Comment by marianbuenosayres** [comment]
I was able to reproduce the OSGI bundle related issues locally, and will continue working on this PR a week from now. Thank you for your help so far, I understand a lot better now the issues related to this tests.

**Comment by mswiderski** [comment]
looks there are related test failures in karaf tests

**Comment by marianbuenosayres** [comment]
Jenkins please retest

**Comment by marianbuenosayres** [comment]
Jenkins please retest

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
@marianbuenosayres could you please rebase with master this and drools pull request for it? build is failing with compilation errors...

**Comment by marianbuenosayres** [comment]
@mswiderski I tried running this locally, and am unable to see any errors on this branch when I run "mvn clean install -Dfull". Could you forward me the error in Jenkins that causes the build to fail? That way if it is something I can fix, I can figure it out

**Comment by mswiderski** [comment]
here it is:

```
11:37:41 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project kie-spring: Compilation failure: Compilation failure:
11:37:41 [ERROR] /home/jenkins/workspace/droolsjbpm-integration-pullrequests/kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManagerFactory.java:[19,30] cannot find symbol
11:37:41 [ERROR] symbol:   class TransactionManager
11:37:41 [ERROR] location: package org.drools.persistence
11:37:41 [ERROR] /home/jenkins/workspace/droolsjbpm-integration-pullrequests/kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManagerFactory.java:[20,30] cannot find symbol
11:37:41 [ERROR] symbol:   class TransactionManagerFactory
11:37:41 [ERROR] location: package org.drools.persistence
11:37:41 [ERROR] /home/jenkins/workspace/droolsjbpm-integration-pullrequests/kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManagerFactory.java:[25,57] cannot find symbol
11:37:41 [ERROR] symbol: class TransactionManagerFactory
11:37:41 [ERROR] /home/jenkins/workspace/droolsjbpm-integration-pullrequests/kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManagerFactory.java:[28,12] cannot find symbol
11:37:41 [ERROR] symbol:   class TransactionManager
11:37:41 [ERROR] location: class org.kie.spring.persistence.KieSpringTransactionManagerFactory
11:37:41 [ERROR] /home/jenkins/workspace/droolsjbpm-integration-pullrequests/kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManagerFactory.java:[33,12] cannot find symbol
11:37:41 [ERROR] symbol:   class TransactionManager
11:37:41 [ERROR] location: class org.kie.spring.persistence.KieSpringTransactionManagerFactory
11:37:41 [ERROR] /home/jenkins/workspace/droolsjbpm-integration-pullrequests/kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManagerFactory.java:[27,5] method does not override or implement a method from a supertype
11:37:41 [ERROR] /home/jenkins/workspace/droolsjbpm-integration-pullrequests/kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManagerFactory.java:[32,5] method does not override or implement a method from a supertype
11:37:41 [ERROR] -> [Help 1]
11:37:41 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project kie-spring: Compilation failure
11:37:41 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
11:37:41 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
11:37:41 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
11:37:41 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
11:37:41 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
11:37:41 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
11:37:41 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:37:41 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11:37:41 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:37:41 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
11:37:41 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
11:37:41 	at java.lang.Thread.run(Thread.java:745)
11:37:41 Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
11:37:41 	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1029)
11:37:41 	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)
11:37:41 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
11:37:41 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
11:37:41 	... 11 more
11:37:41 [ERROR] 
11:37:41 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
11:37:41 [ERROR] 
11:37:41 [ERROR] For more information about the errors and possible solutions, please read the following articles:
11:37:41 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
11:37:41 [ERROR] 
11:37:41 [ERROR] After correcting the problems, you can resume the build with the command
11:37:41 [ERROR]   mvn <goals> -rf :kie-spring
```

**Comment by marianbuenosayres** [comment]
jenkins please retest

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by marianbuenosayres** [comment]
@mswiderski found the new commits that were referencing the TransactionManagerFactory on the wrong package. Fixed them now

**Pull request merged**
