### PR TITLE
JBPM-9273 System error occurred while adding deployment unit

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://issues.redhat.com/browse/JBPM-9273)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by prashuts** [comment]
Jenkins run fdb

**Comment by prashuts** [comment]
There are failures in https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-integration-master.pullrequests/124/testReport/
@bxf12315  Please check and let me know the status if any concerns, as currently its blocking for PR approvals.

**Comment by bxf12315** [comment]
Jenkins retest this

**Review by prashuts — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Pull request merged**
