### PR TITLE
[RHPAM-2267] - Allow undertow proxied request to use ssl

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
@mareknovotny can this be merged?

**Comment by mareknovotny** [comment]
what will we do with failed test coverage? @sutaakar

**Comment by sutaakar** [comment]
@spolti Can you please improve test coverage?

**Comment by spolti** [comment]
Tests improved.
@sutaakar thanks for the help.

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
@rsynek jacoco coverage ant task fails here with 
`Caused by: java.lang.IllegalStateException: Can't add different class with same name: org/jbpm/prediction/pmml/AbstractPMMLBackend`
 https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-integration-pullrequests/695/consoleText

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
Jenkins retest this

**Pull request merged**
