### PR TITLE
[7.67.x-blue] Update camel to 2.25.4.

### PR DESCRIPTION
**Pull request by baldimir**
Related PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2486

### CODE REVIEW

**Comment by baldimir** [comment]
jenkins execute product fdb

**Review by yesamer — APPROVED** [review]

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins retest this

**Comment by yesamer** [comment]
jenkins execute product fdb

**Comment by baldimir** [comment]
jenkins execute product fdb

**Comment by baldimir** [comment]
jenkins run fdb

**Comment by baldimir** [comment]
The test failure from the normal PR check (Linux - Pull request), is not relevant to this PR. Till downstream builds finish, I will retrigger to try to make the check green.

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
The full production downstream build test failure is a flaky test. It passes in the classic Full Downstream PR check here https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.67.x-blue/job/fdb/job/droolsjbpm-integration-7.67.x-blue.fdb/21/testReport/org.kie.bc/DeploymentIT/ .

**Comment by baldimir** [comment]
Another different test failed in the PR check, looks to be a flaky test again, because it didn't fail before anywhere else and ended on timeout. Not restarting the PR check because of this and I consider it green.

**Review by mareknovotny — APPROVED** [review]
lgtm, test failures or errors are not related

**Pull request merged**
