### PR TITLE
Fix kie-maven-plugin-example and added reproducer for DROOLS-3960

### PR DESCRIPTION
**Pull request by lucamolteni**
Related to https://github.com/kiegroup/drools/pull/2327

### CODE REVIEW

**Comment by baldimir** [comment]
This kind of tests could be added rather here https://github.com/kiegroup/droolsjbpm-integration/tree/master/kie-plugins-testing

**Comment by lucamolteni** [comment]
jenkins test again

**Comment by lucamolteni** [comment]
jenkins test again

**Comment by lucamolteni** [comment]
jenkins test again

**Pull request merged**
