### PR TITLE
[JBPM-8506] Need slf4j adapter for kie server with RHDM 7

### PR DESCRIPTION
**Pull request by elguardian**
added org.slf4j:slf4j-jdk14 to the assembly so weblogic can log

### CODE REVIEW

**Comment by elguardian** [comment]
@MarianMacik @mswiderski can you review this ?

**Comment by sutaakar** [comment]
@elguardian Just a quick question, have you tried to check that the change works correctly on WebSphere? I am asking because the ee7 artifact is used in both application servers.

**Comment by sutaakar** [comment]
WebLogic and WebSphere seem to work correctly, just reported DROOLS-4054 .

**Comment by elguardian** [comment]
@mswiderski can you check this one ?

This is a customer case, if goes in plz merge.

**Pull request merged**
