### PR TITLE
Adjustments to analyze random failures of testContainerDisposedAfterS…

### PR DESCRIPTION
**Pull request by sutaakar**
…tartup()

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@sutaakar out of curiosity what is this for?

**Comment by sutaakar** [comment]
@mswiderski I have noticed that WebSocketKieControllerStartupIntegrationTest.testContainerDisposedAfterStartup() sometimes fails, but I wasn't able to figure out why yet. It seems to pass with local builds so I am trying to simulate it here on Jenkins with additional info.

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
@mswiderski Could these changes be temporary merged? Seems that I am not able to simulate the issue here in PR builder. Will revert this commit when the issue will be found/fixed.

**Comment by sutaakar** [comment]
@mswiderski Done

**Pull request merged**
