### PR TITLE
[DROOLS-6837] LoadBalancer does not use Authentication to check on fa…

### PR DESCRIPTION
**Pull request by tkobayas**
…iled endpoints

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6837

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
As I wrote in the JIRA comment https://issues.redhat.com/browse/DROOLS-6837 , I cannot reproduce the `IOException Server returned HTTP response code: 401 for URL:` locally (even with nginx). Usually, HttpURLConnection.getResponseCode() should return 401 instead of IOException so LoadBalancer.CheckFailedEndpoints can detect that the server is online even without authentication (= 401).

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/HttpURLConnection.html#getResponseCode()

However, the IOException is sometimes observed according to https://www.google.com/search?client=firefox-b-e&q=%22Server+returned+HTTP+response+code%3A+401+for+URL%3A%22 so I simulate the error with WireMockServer in the test case and fixed the issue by providing authentication.

@mariofusco  @sutaakar  Could you review? Thanks!

**Comment by tkobayas** [comment]
Linux - Pull Request : all tests passed. Failed with jacoco, not related to this PR.
```
[2022-04-01T12:55:54.266Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (generate-aggregated-jacoco-report) on project droolsjbpm-integration: An Ant BuildException has occured: Unable to read execution data file /home/jenkins/workspace/KIE/main/pullrequest/droolsjbpm-integration-main.pr/bc/kiegroup_droolsjbpm_integration/target/jacoco.exec
[2022-04-01T12:55:54.266Z] [ERROR] around Ant part ...<report>... @ 7:11 in /home/jenkins/workspace/KIE/main/pullrequest/droolsjbpm-integration-main.pr/bc/kiegroup_droolsjbpm_integration/target/antrun/build-main.xml: EOFException
```

**Review by mariofusco — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]
Looks good to me

**Pull request merged**
