### PR TITLE
[do not merge] Stabilize random test failure in Jenkins build

### PR DESCRIPTION
**Pull request by sutaakar**
Will run this PR several times to make sure that test instability is really gone.

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@sutaakar are you still working on this?

**Comment by sutaakar** [comment]
no, will close it

**Comment by jhrcek** [comment]
Hello @sutaakar and  @mswiderski
Was this PR an attempt to stabilize these tests [ProcessInstanceAdminServiceIntegrationTest](http://janhrcek.cz/random-failures/#/class/org.kie.server.integrationtests.jbpm.admin.ProcessInstanceAdminServiceIntegrationTest) and [QueryDataServiceIntegrationTest](http://janhrcek.cz/random-failures/#/class/org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest)? As you can see in my test failure data I'm collecting, these 2 classes alone are responsible for arount ~400 failures in PR builder jobs (click the method names to see more details). If you can't find a way to stabilize them, would you consider disabling them? It seems that these 2 classes are failing far more often than others..

**Comment by mswiderski** [comment]
@jhrcek there is no way to figure it out as it stands right now. Moreover it does seem to not cause any issues both locally and on QE jenkins. So disabling them is fine for me to be honest but it then can hide potential issues on production/release builds.

**Comment by sutaakar** [comment]
@jhrcek I wouldn't disable them as they have sense for local and QE tests.

**Comment by jhrcek** [comment]
I suspect the main difference will be that kie-jenkins is using parallel maven build with `-T1C` for which the tests are not ready. I'd just suggest try the same command as PR jobs are using locally few times:
`mvn -e -fae -nsu -B -T1C clean install -Dfull -DskipTests`

**Comment by mswiderski** [comment]
@jhrcek I actually tried it with these settings many times... 

do you mean that QE jenkins is not running with parallel builds enabled?

**Comment by sutaakar** [comment]
@mswiderski @jhrcek No, we don't run the tests in parallel.

**Pull request closed without merging**
