### PR TITLE
[JBPM-9729] KIE-Server template is removed after a ping failure

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/JBPM-9729
adding kie server instance online flag and modifying alive ping so the server can have that possibility of comming back alive if there is a network glitch during ping is alive.

### CODE REVIEW

**Comment by elguardian** [comment]
@sutaakar  it should be fixed now. Some implementations keep in memory mutable data. the copy constructor should fix that.

**Comment by elguardian** [comment]
Jenkins retest this please

**Review by sutaakar — APPROVED** [review]
Looks good to me, seems to work as expected.

**Comment by sutaakar** [comment]
@elguardian Can you please take a look on the test failures?

**Comment by sutaakar** [comment]
Can you also provide some test coverage for healthcheck?

**Comment by elguardian** [comment]
Jenkins retest this please.

**Pull request merged**
