### PR TITLE
JBPM-7252 - Upgrade camel version to 2.21.0

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1469

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mariofusco** [comment]
ok to test

**Comment by tsurdilo** [comment]
Jenkins Build errors related to https://github.com/kiegroup/droolsjbpm-integration/pull/1482

Depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1482

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mariofusco** [comment]
ok to test

**Pull request merged**
