### PR TITLE
removed not used revapi-naven-plugin

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
@mswiderski please approve

**Comment by rsynek** [comment]
@mbiarnes @mswiderski guys, why removing the revapi plugin? I can see REST API resource classes at least in the kie-server-rest-jbpm-search module - these should be checked for backward compatibility in my opinion.

**Comment by mswiderski** [comment]
@rsynek jbpm-search will most likely be removed soon and that's why we don't need the revapi anymore there.

**Comment by mswiderski** [comment]
@mbiarnes is this waiting for anything or can be merged?

**Comment by mswiderski** [comment]
not relevant any more after this https://github.com/kiegroup/droolsjbpm-integration/pull/1274 was merged

**Pull request closed without merging**
