### PR TITLE
 JBPM-7424 - org.kie.server.json.format.date has no effect anymore in

### PR DESCRIPTION
**Pull request by mswiderski**
in addition another commit to avoid conflicts with db in kia-spring module

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@MarianMacik @sutaakar could you please review as this fixes the build

**Comment by MarianMacik** [comment]
Looks OK to me.

**Pull request merged**
