### PR TITLE
[7.67.x] skipped parallel checkouts for build chain

### PR DESCRIPTION
**Pull request by mbiarnes**
(cherry picked from commit 21583553d0e8403334eb8daa0c36f9bf8e01ce87)

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
@afalhambra @gmunozfe please check the failures here as this branch and 7.67.x-blue shows 2 common failures. I saw this failures also on other PR in FDB run for postgresql upgrade https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2024

**Comment by afalhambra** [comment]
> lue shows 2 common failures

In two of them, the issue seems to be caused by this:

```
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: 
Could not transfer artifact jakarta.xml.bind:jakarta.xml.bind-api:pom:2.3.3 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/public/): 
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Is there any issue ongoing with Nexus repo?

**Comment by mareknovotny** [comment]
nexus is available, so no problem to cause that dependency error.

**Comment by afalhambra** [comment]
@mareknovotny - ok, trying to reproduce the issue locally

**Comment by mareknovotny** [comment]
jenkins retest this please

so relaunching it then again to see if they are consistent.

**Comment by afalhambra** [comment]
@mareknovotny 
locally, I'm not able to reproduce `JbpmRestIntegrationTest#testKieModuleMetaDataGetProcesses`. I'm pointing out to a different nexus repo `https://repository.jboss.org/nexus`.

Will try out with the nexus repo used by CI

**Comment by mareknovotny** [comment]
so now the one of dependency failure in test was related to different artifact and the other test still shows problem with jakarta xm bind dependency. So i would call it weird Nexus problem. cc @winklerm

**Comment by afalhambra** [comment]
seems an environment issue as I'm unable to reproduce any of the failures locally pointing out to the same nexus repo, with the same maven command.
FYI @mareknovotny @winklerm

**Pull request merged**
