### PR TITLE
Add CXF dependency to Wildfly/EAP deployable

### PR DESCRIPTION
**Pull request by sutaakar**
To return cxf-rt-ws-policy excluded by https://github.com/kiegroup/droolsjbpm-integration/pull/885

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
test failures not related to this change

**Comment by mswiderski** [comment]
@sutaakar should we back port this to 7.2.x?

**Comment by sutaakar** [comment]
@mswiderski Yes, will prepare a PR.

**Pull request merged**
