### PR TITLE
[JBPM-9121] REST Process APIs should return 403 when user has no permissions

### PR DESCRIPTION
**Pull request by gmunozfe**
Security (based on required roles) is performed only on process operations, but REST APIs are responding with an internal error (500) instead of forbidden (403).
Added also annotations for Swagger.

### CODE REVIEW

**Comment by gmunozfe** [comment]
Unrelated test failures.
jenkins retest this

**Comment by elguardian** [comment]
wait for CI to be green. Sonar cloud is not relevant

**Comment by elguardian** [comment]
Jenkins retests this please.

**Comment by gmunozfe** [comment]
jenkins retest this

**Pull request merged**
