### PR TITLE
Stabilize and extend testStartAndStopScanner()

### PR DESCRIPTION
**Pull request by sutaakar**
Raise scanner interval as previous one was too small, could cause Kie server to be unresponsive.
Add additional checks to verify that scanner is really doing what is expected.

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
test failures not related to the change

**Pull request merged**
