### PR TITLE
[6.5.x] Remove kie module from repository when container is disposed

### PR DESCRIPTION
**Pull request by mswiderski**
@baldimir here it is

### CODE REVIEW

**Comment by baldimir** [comment]
@mswiderski there is 1 failed test. I will check if it is related.

**Comment by baldimir** [comment]
It looks unrelated.

**Comment by baldimir** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
ok, let's wait for the next build to finish and then merge it. 
requested by https://issues.jboss.org/browse/RHBPMS-5212 ... or we should not merge for one off patches @mareknovotny ??

**Pull request closed without merging**
