### PR TITLE
[7.26.x] [JBPM-8400] Logs are constantly flooded with 'Unable to load key store. Using password from configuration'

### PR DESCRIPTION
**Pull request by elguardian**
added some logic to print the message just the first time

### CODE REVIEW

**Comment by elguardian** [comment]
backport #1903

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
Do not merge. This is targeting 7.5.1.

**Comment by domhanak** [comment]
@elguardian just a thought, I know it is a backport, but I noticed this too after using installer to install the workbench. Do you think we could improve the message to be more descriptive or to help user resolve it? For example add `Check your keystore configuration.` or something similar. Let me know what you think about it.

**Comment by sutaakar** [comment]
the failure seems to be related to https://github.com/kiegroup/kie-jenkins-scripts/pull/558

**Comment by elguardian** [comment]
@domhanak pls if you want to change the behaviour let's create another jira... otherwise we will start get confusing and snatch discussion outside the proper channels.

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by mareknovotny** [comment]
are we ready for merging?

**Pull request merged**
