### PR TITLE
[DROOLS-5616] Be able to set with an Env Variable that KIE using XStr…

### PR DESCRIPTION
**Pull request by tkobayas**
…eam does not complain on unknown fields

**JIRA**: 

https://issues.redhat.com/browse/DROOLS-5616
https://issues.redhat.com/browse/RHDM-1444

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
👍  I like this A LOT :) 

_Arigatouu gozaimashita_ Toshiya, I was getting curious on this topic and I just found out you have already done it 🤣

**Comment by tkobayas** [comment]
Grazie, Matteo!

@elguardian  @sutaakar  Please review and merge this if it's okay. Thanks!

**Comment by sutaakar** [comment]
@tkobayas Can you please add `<argument>-Dorg.kie.server.xstream.ignore.unknown.elements=true</argument>` to https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-tests/pom.xml#L1468 to be able to run this test also for SpringBoot? Thanks.
Otherwise looks good.

**Comment by elguardian** [comment]
Not very happy about this. We are using media type parameters for this sort of things.
example
https://github.com/kiegroup/droolsjbpm-integration/commit/933120d759fae5f521cb8fb39f9d5edb16589d5e#diff-63a038f8aee4aca5fd3dad3f72359355

**Review by elguardian — CHANGES_REQUESTED** [review]
At least add the media type parameter, for ignoring unkown fields.

**Comment by tarilabs** [comment]
> At least add the media type parameter, for ignoring unkown fields.

interesting comment https://github.com/kiegroup/droolsjbpm-integration/pull/2221#pullrequestreview-482435733, since what is being discussed here is a marshaller-wide configuration..
F

**Comment by elguardian** [comment]
> interesting comment [#2221 (review)](https://github.com/kiegroup/droolsjbpm-integration/pull/2221#pullrequestreview-482435733), since what is being discussed here is a marshaller-wide configuration..
> F

Marshalling wide for xml stream is never a good idea so would try to minimize that as much as possible (it is not how xml works).
In any way this is how we are treating this sort of problems with marshaller through the system.

Either this is done that way or I will reject it.

**Comment by tarilabs** [comment]
I agree! What I'm saying is that for `XStream` this is a marshaller-instance-wise setting, and since you mentioned:

> We are using media type parameters for this sort of things.

I am interested to understand how you deal with this libraries limitations in a case like this one?
I have a similar issue in another project using `XStream`, and I'm hoping to learn here how to deal with this limitation in a new way. 

Do you have a link to share which deal with an _analogous_ problem such as this one, please?
The link you previously shared, IIUC, relies on the ability for Jackson to support marshaller cloning but AFAIK this feature is not available for `XStream`. How did you solved this problem?

**Comment by tkobayas** [comment]
I created another PR which adds media type "ignoreUnknownElements".

https://github.com/kiegroup/droolsjbpm-integration/pull/2223/

I think the point is aligned with what @tarilabs said. As there is no way to revert xstream.ignoreUnknownElements(), I recreate an xstream instance when the media type "ignoreUnknownElements" changed from "true" to "false".

https://github.com/kiegroup/droolsjbpm-integration/pull/2223/files#diff-1f557254ee4636142b42b01b7577c95aR239

Is it good enough? Even though I introduced media type, I hope that the system property is still available for user's convenience.

**Comment by jonathanvila** [comment]
I would add that doing a system wide flag is a nice and not intrusive way of configure this behavior to make KIE behave the same on XStream, JAXB or JSON ... so not hard xml validation.
Adding a request header makes current clients to recode ( I don't know if it's needed also to modify the KIE client code and the kie-camel component ? ), it's ok if wanted to have this feature request wise if needed.

**Comment by elguardian** [comment]
Ok. Let's try to clarify things. 

This jira should not exist in first place. It is clearly an integration problem not a kie server problem.

You are trying to solve an integration problem in kie server. XML have a schema that must be fullifiled. It you are sending more info to the kie server this needs to be fixed in the integration part and not kie server. I understand this must be convenient but it is not the right approach to do this. If you send a xml that does not fit what is expected in xml it must throw an error. No room for discussion there, otherwise it would be difficult for troubleshot if someone sends data and gets ignored silently.

The reason I am insistent about this being fixed in another way it is because xml is not though for this and can cause problems at GSS at some point.

Parameter in media type specifying that is a way to explicityly force the integration parts to tell kie server to ignore those fields. 

Also wide flag will impact in operations at kie server level so user expectations can really get messy using kie server (not just user input)

**Comment by elguardian** [comment]
reached an agreement with Jonathan Vila Lopez about this. It will require a bit more tweaking as this should only apply to the user payloads (user space) and not the entire objet.

**Pull request closed without merging**
