### PR TITLE
[JBPM-9492] Send signals using alias without need to send the instanceid

### PR DESCRIPTION
**Pull request by fjtirado**
Retrieving containerId using KieServerRegistry just for the API
mentioned in the JIRA

**JIRA**:

[JBPM-9492](https://issues.redhat.com/browse/JBPM-9492)

### CODE REVIEW

**Review by afalhambra — CHANGES_REQUESTED** [review]
Seems there is an issue.

When calling `processServiceBase.signal` the following workflow is executed:

https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java#L273 

goes to https://github.com/kiegroup/jbpm/blob/master/jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/ProcessServiceImpl.java#L342

which looks for a deploymentId which is based on the GAV format (and not on an alias), therefore an exception is thrown saying that no deployment id was found.

**Comment by elguardian** [comment]
@fjtirado just do the comsetic stuff will merge right away aftewards.

**Comment by afalhambra** [comment]
> @fjtirado just do the comsetic stuff will merge right away aftewards.

I think there is an issue which needs to be fixed IMO, as per my comment above. Please, have a look

**Comment by fjtirado** [comment]
@elguardian done, lets wait for green

**Review by afalhambra — APPROVED** [review]
Looks good to me. Just add the missing `;` on line below:

https://github.com/kiegroup/droolsjbpm-integration/blob/2eaa8b3db934f7c8666c0395bdad888a19998dfa/kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java#L63

and wait for the CI to turn green

Thanks!

**Review by elguardian — APPROVED** [review]

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by elguardian** [comment]
jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
failures related to PMML and OSGI. unrelated.

**Pull request merged**
