### PR TITLE
JBPM-8766 Cannot start a task if elytron adapter is installed

### PR DESCRIPTION
**Pull request by bxf12315**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by bxf12315** [comment]
jenkins please retest this

**Comment by bxf12315** [comment]
jenkins please retest this

**Comment by mareknovotny** [comment]
Hi @cristianonicolai, are you ok with merging this PR?

**Pull request merged**
