### PR TITLE
[DROOLS-7604] kie-karaf-itests fail with "Unable to resolve org.mvel2…

### PR DESCRIPTION
**Pull request by tkobayas**
…/2.5.1.Final"

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7604

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2427
 -> mvel upgrade

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
GHA Java 8 : GHA was cancelled, but kie-karaf-itests was successful. This is the main part which we want to verify.
```
2024-02-01T05:28:58.2533243Z [INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ kie-karaf-itests ---
2024-02-01T05:28:58.2563327Z [INFO] Failsafe report directory: /home/runner/work/droolsjbpm-integration/droolsjbpm-integration/kiegroup_droolsjbpm-integration/kie-osgi/kie-karaf-itests/target/failsafe-reports
2024-02-01T05:28:58.2577033Z [INFO]
2024-02-01T05:28:58.2578389Z [INFO] -------------------------------------------------------
2024-02-01T05:28:58.2579176Z [INFO]  T E S T S
2024-02-01T05:28:58.2580349Z [INFO] -------------------------------------------------------
2024-02-01T05:28:58.6429166Z [INFO] Running org.kie.karaf.itest.RuntimeManagerFeatureKarafIntegrationTest
2024-02-01T05:29:12.8868937Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.241 s - in org.kie.karaf.itest.RuntimeManagerFeatureKarafIntegrationTest
2024-02-01T05:29:43.1942849Z [INFO] Running org.kie.karaf.itest.KieSpringDependencyKarafIntegrationTest
2024-02-01T05:29:59.0504351Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.854 s - in org.kie.karaf.itest.KieSpringDependencyKarafIntegrationTest
2024-02-01T05:30:29.3605539Z [INFO] Running org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintIntegrationTest
2024-02-01T05:30:53.9975686Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.634 s - in org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintIntegrationTest
2024-02-01T05:30:54.6117855Z [INFO] Running org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest
2024-02-01T05:31:12.9029786Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.288 s - in org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest
2024-02-01T05:31:13.5444077Z [INFO] Running org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest
2024-02-01T05:31:33.4291015Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.883 s - in org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest
2024-02-01T05:31:34.0698581Z [INFO] Running org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest
2024-02-01T05:31:55.4406364Z [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.368 s - in org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest
2024-02-01T05:32:25.7546087Z [INFO] Running org.kie.karaf.itest.blueprint.KieBlueprintDependencyKarafIntegrationTest
2024-02-01T05:32:39.3978390Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.64 s - in org.kie.karaf.itest.blueprint.KieBlueprintDependencyKarafIntegrationTest
2024-02-01T05:33:09.7328309Z [INFO] Running org.kie.karaf.itest.blueprint.KieBlueprintjBPMPersistenceKarafIntegrationTest
2024-02-01T05:33:27.6147643Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.879 s - in org.kie.karaf.itest.blueprint.KieBlueprintjBPMPersistenceKarafIntegrationTest
2024-02-01T05:33:57.9380134Z [INFO] Running org.kie.karaf.itest.blueprint.KieBlueprintImportIntegrationTest
2024-02-01T05:34:14.5211720Z [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.58 s - in org.kie.karaf.itest.blueprint.KieBlueprintImportIntegrationTest
2024-02-01T05:34:45.1619037Z [INFO] Running org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest
2024-02-01T05:34:59.5651242Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.401 s - in org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest
2024-02-01T05:35:29.8772203Z [INFO] Running org.kie.karaf.itest.blueprint.KieBlueprintScannerReimportIntegrationTest
2024-02-01T05:36:05.0685192Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.189 s - in org.kie.karaf.itest.blueprint.KieBlueprintScannerReimportIntegrationTest
2024-02-01T05:36:05.6924473Z [INFO] Running org.kie.karaf.itest.KieDMNKarafIntegrationTest
2024-02-01T05:36:16.9208628Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.226 s - in org.kie.karaf.itest.KieDMNKarafIntegrationTest
2024-02-01T05:36:47.2626622Z [INFO] Running org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest
2024-02-01T05:37:10.2480982Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.983 s - in org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest
2024-02-01T05:37:40.8793036Z [INFO] Running org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest
2024-02-01T05:38:31.4938533Z [INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 50.612 s - in org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest
2024-02-01T05:39:01.8117298Z [INFO] Running org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJaxbIntegrationTest
2024-02-01T05:39:15.2066969Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.392 s - in org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJaxbIntegrationTest
2024-02-01T05:39:45.5523991Z [INFO] Running org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest
2024-02-01T05:39:57.8693662Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.315 s - in org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest
2024-02-01T05:39:58.5106724Z [INFO] Running org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationXstreamIntegrationTest
2024-02-01T05:40:10.4896621Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.976 s - in org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationXstreamIntegrationTest
2024-02-01T05:40:11.1249626Z [INFO] Running org.kie.karaf.itest.WorkbenchModelsKarafIntegrationTest
2024-02-01T05:40:22.2202867Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.093 s - in org.kie.karaf.itest.WorkbenchModelsKarafIntegrationTest
2024-02-01T05:40:22.8651919Z [INFO] Running org.kie.karaf.itest.pmml.KiePmmlIntegrationTest
2024-02-01T05:40:32.8297375Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.963 s - in org.kie.karaf.itest.pmml.KiePmmlIntegrationTest
2024-02-01T05:41:03.1582743Z [INFO] Running org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest
2024-02-01T05:41:15.7712720Z [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.611 s - in org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest
2024-02-01T05:41:46.0974190Z [INFO] Running org.kie.karaf.itest.DecisionTablesIntegrationTest
2024-02-01T05:41:57.7235857Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.624 s - in org.kie.karaf.itest.DecisionTablesIntegrationTest
2024-02-01T05:41:58.3635317Z [INFO] Running org.kie.karaf.itest.KieSpringMetaInfAppContextKarafIntegrationTest
2024-02-01T05:42:11.2296001Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.863 s - in org.kie.karaf.itest.KieSpringMetaInfAppContextKarafIntegrationTest
2024-02-01T05:42:41.5578731Z [INFO] Running org.kie.karaf.itest.planner.PlannerCloudBalanceIntegrationTest
2024-02-01T05:42:51.9873860Z [WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 10.427 s - in org.kie.karaf.itest.planner.PlannerCloudBalanceIntegrationTest
2024-02-01T05:43:21.9972768Z [INFO]
2024-02-01T05:43:21.9973464Z [INFO] Results:
2024-02-01T05:43:21.9974264Z [INFO]
2024-02-01T05:43:21.9974786Z [WARNING] Tests run: 62, Failures: 0, Errors: 0, Skipped: 2
```

GHA Java 11 : Not related to this PR. Flaky.
```
2024-02-01T03:44:07.6128142Z [ERROR] Tests run: 15, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.41 s <<< FAILURE! - in org.kie.server.client.LoadBalancerClientTest
2024-02-01T03:44:07.6130207Z [ERROR] testDefaultLoadBalancerNoServersAvailable(org.kie.server.client.LoadBalancerClientTest)  Time elapsed: 5.36 s  <<< ERROR!
2024-02-01T03:44:07.6131935Z org.kie.server.common.rest.NoEndpointFoundException: No available endpoints found
```

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins PR: Not related to this PR
```
[2024-02-01T11:12:41.023Z] [ERROR] Tests run: 33, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 257.859 s <<< FAILURE! - in org.kie.server.integrationtests.jbpm.jms.JmsResponseHandlerIntegrationTest
[2024-02-01T11:12:41.023Z] [ERROR] testStartAndCompleteTaskUseOfFireAndForgetResponseHandler[JAXB](org.kie.server.integrationtests.jbpm.jms.JmsResponseHandlerIntegrationTest)  Time elapsed: 240.717 s  <<< ERROR!
[2024-02-01T11:12:41.023Z] java.util.concurrent.TimeoutException: Synchronization failed for defined timeout: 240000 milliseconds.
[2024-02-01T11:12:41.023Z]      at org.kie.server.integrationtests.jbpm.jms.JmsResponseHandlerIntegrationTest.testStartAndCompleteTask(JmsResponseHandlerIntegrationTest.java:297)
```

**Comment by tkobayas** [comment]
The kie-karaf-itests issue is fixed by this PR + https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2427

Please review @grgrzybek @mariofusco @mareknovotny

**Review by grgrzybek — APPROVED** [review]

**Pull request merged**
