### PR TITLE
[JBPM-8864] not able to delete kieContainer after deploying container several times with same containerID due to an error

### PR DESCRIPTION
**Pull request by elguardian**
the system registers the container even before the container was created causing problem during unregistering (cannot dispose because the container is null in the registered instance so it cannot 
dispose in kieservice container map. The solution is to delay till we have the container active and then
overwrite the container.

### CODE REVIEW

**Comment by sutaakar** [comment]
@elguardian Can you please add a test reproducing the issue?

**Comment by elguardian** [comment]
done @sutaakar

**Comment by sutaakar** [comment]
@elguardian Please remove the unrelated package-lock.json changes.
Also the test failures seem to be related to these changes.

**Comment by elguardian** [comment]
Saw it... some weak tests (race condition) and a change of behaviour in the list of containers when the container is failing during deployment

**Comment by elguardian** [comment]
fixing test case as missing modules in maven repository was considered  equal to deployment failure
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
@sutaakar thx for the hint, I was wasting a lot of time trying to make everything work in the current project. can you approve ?

**Comment by elguardian** [comment]
@kiegroup/gatekeepers 
can anyone merge this ?

**Comment by sutaakar** [comment]
SonarCloud failures are acceptable, coverage is calculated also from changes in test classes related just for local testing.

**Pull request merged**
