### PR TITLE
JBPM-9151 API return 200 if containerId does not exist

### PR DESCRIPTION
**Pull request by fjtirado**
Change integration test to check for 404 rather than for 200
Depends on [jbpm#1668](https://github.com/kiegroup/jbpm/pull/1668)

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by elguardian** [comment]
wait for CI. but probably the usual suspects.

**Comment by elguardian** [comment]
@fjtirado failures seems related.

**Comment by elguardian** [comment]
@fjtirado failing test.
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-integration-pullrequests/991/testReport/junit/org.kie.server.integrationtests.jbpm/RuntimeDataServiceIntegrationTest/testGetProcessDefinitionsByContainer_3__JAXB_KieServicesConfiguration_transport_JMS__serverUrl__null___/
seems related.

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by elguardian** [comment]
@fjtirado looks like something from the pr. just correct the test case if needed.

**Comment by sutaakar** [comment]
It looks like discrepancy between REST and JMS client when returning process definitions for non existing container.

**Comment by gmunozfe** [comment]
Looks good to me, good work @fjtirado !

**Pull request merged**
