### PR TITLE
[DROOLS-6554] droolsjbpm-integration deploy job failure

### PR DESCRIPTION
**Pull request by tkobayas**
**JIRA**: 

https://issues.redhat.com/browse/DROOLS-6554

**referenced Pull Requests**: 

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1730

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mbiarnes — APPROVED** [review]
LGTM

**Review by almope — APPROVED** [review]

**Comment by almope** [comment]
jenkins execute fdb

**Review by mareknovotny — APPROVED** [review]
lgtm

**Comment by almope** [comment]
Jenkins execute fdb

Retrying fdb as apparently there were some infrastructure glitches

**Comment by mareknovotny** [comment]
so there are 3 test failed in i guess not related areas:

-     org.kie.wb.test.websocket.WebSocketAccessIntegrationTest.testControllerConnection[user: REST_ALL]
-     org.kie.wb.test.rest.functional.ProjectIntegrationTest.testInstallProjectSnapshotTwice
-     org.kie.wb.test.websocket.WebSocketAccessIntegrationTest.testControllerConnection[user: NO_REST]

`Caused by: java.net.PortUnreachableException: ICMP Port Unreachable` is the root cause in all 3 failures. So environment issue or wrong setup of tests.

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by gitgabrio — COMMENTED** [review]
@almope @tkobayas 
Hi guys. Why it has been necessary to add this declaration in two different pom ? (this one and the https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1730 one ?)

**Review by gitgabrio — APPROVED** [review]
LGTM

**Pull request merged**
