### PR TITLE
[JBPM-8220] Update ServerTemplateConverter

### PR DESCRIPTION
**Pull request by rhtevan**
Related to AF-1685: Development Lifecycle Streamline (#1698)

### CODE REVIEW

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by rhtevan** [comment]
@mswiderski 
Updated ServerTemplateConverter as discussed earlier.
https://github.com/kiegroup/droolsjbpm-integration/pull/1698#discussion_r255191563

**Comment by mswiderski** [comment]
ok to test

**Comment by rhtevan** [comment]
@mswiderski  My pleasure :+1:

**Comment by rhtevan** [comment]
@sutaakar 
Could you help trigger a retest?

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by rhtevan** [comment]
@sutaakar 
Could you take a look. As Maciej is on sick leave this week, who would be the best person to merge this?

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by sutaakar** [comment]
@rhtevan Not sure who has merge rights, possibly @cristianonicolai

**Comment by mswiderski** [comment]
@rhtevan @sutaakar I can merge but there are 160 tests failures so not sure this is ready to be merged

**Comment by sutaakar** [comment]
AFAIK the test failures are being fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/1721.
So I think we can wait for it and retest after it is merged.

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by rhtevan** [comment]
@sutaakar @mswiderski 
This time looks much better. But still has 15 failures which I believe it is unrelated as other builds (triggered by different PR) have experiencing the same failure. Are we able to merge this PR and investigate those failures separately? What do you thing?

**Comment by sutaakar** [comment]
I think it could be merged.

**Comment by MarianMacik** [comment]
Full downstream failed probably because of Jenkins outage, but since this is Openshift related, there is no added value in running it. Fails on PR check are not related.

**Pull request merged**
