### PR TITLE
[BXMSPROD-1372] [Improve community CI] [droolsjbpm-integration] test …

### PR DESCRIPTION
**Pull request by tkobayas**
…random errors

- Karaf errors

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1372

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by elguardian — APPROVED** [review]
LGTM

**Comment by tkobayas** [comment]
Build Chain (8)
```
2021-06-17T09:06:20.8595628Z [INFO] KIE :: Execution Server :: Remote :: Client ........ FAILURE [  1.750 s]

2021-06-17T09:06:20.9076682Z [ERROR] Failed to execute goal on project kie-server-client: Could not resolve dependencies for project org.kie.server:kie-server-client:bundle:7.56.0-SNAPSHOT: Could not transfer artifact org.mortbay.jetty:jetty:jar:6.1.26 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar: Connection reset -> [Help 1]
2021-06-17T09:06:20.9095721Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project kie-server-client: Could not resolve dependencies for project org.kie.server:kie-server-client:bundle:7.56.0-SNAPSHOT: Could not transfer artifact org.mortbay.jetty:jetty:jar:6.1.26 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar
...
2021-06-17T09:06:20.9918179Z Caused by: java.net.SocketException: Connection reset
2021-06-17T09:06:20.9919611Z     at java.net.SocketInputStream.read (SocketInputStream.java:210)
2021-06-17T09:06:20.9921323Z     at java.net.SocketInputStream.read (SocketInputStream.java:141)
2021-06-17T09:06:20.9923358Z     at sun.security.ssl.SSLSocketInputRecord.read (SSLSocketInputRecord.java:476)
2021-06-17T09:06:20.9926584Z     at sun.security.ssl.SSLSocketInputRecord.readHeader (SSLSocketInputRecord.java:470)
2021-06-17T09:06:20.9930783Z     at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket (SSLSocketInputRecord.java:70)
2021-06-17T09:06:20.9934584Z     at sun.security.ssl.SSLSocketImpl.readApplicationRecord (SSLSocketImpl.java:1355)
2021-06-17T09:06:20.9936890Z     at sun.security.ssl.SSLSocketImpl.access$300 (SSLSocketImpl.java:73)
2021-06-17T09:06:20.9938731Z     at sun.security.ssl.SSLSocketImpl$AppInputStream.read (SSLSocketImpl.java:964)
2021-06-17T09:06:20.9944358Z     at org.apache.maven.wagon.providers.http.httpclient.impl.io.SessionInputBufferImpl.streamRead (SessionInputBufferImpl.java:137)
```
Network issue

**Review by mariofusco — APPROVED** [review]

**Comment by tkobayas** [comment]
I confirmed that KieSpringjBPMPersistenceKarafIntegrationTest fails with JDK 11 (passes with JDK 8) on my local end. I think we can address this with another PR. (better to fix one-by-one)
```
[INFO] Running org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest
18:05:00.715 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.<clinit>:131 - KIE Project Version : 7.56.0-SNAPSHOT
18:05:00.873 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:179 - *** The karaf version is 4.2.3 ***
18:05:00.874 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:180 - *** The cxf version is 3.2.14 ***
18:05:00.874 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:181 - *** The camel version is 2.21.5 ***
18:05:00.884 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getFeaturesUrl:294 - Features URL: mvn:org.kie/kie-karaf-features/7.56.0-SNAPSHOT/xml/features
18:05:00.888 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getFeaturesUrl:294 - Features URL: mvn:org.apache.karaf.features/spring/4.2.3/xml/features
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/home/tkobayas/usr/work/BXMSPROD-1372/droolsjbpm-integration/kie-osgi/kie-karaf-itests/target/paxexam/unpack/de51a4ee-3d77-4fa6-96cc-c65e912b5eb8/system/org/apache/felix/org.apache.felix.framework/5.6.12/org.apache.felix.framework-5.6.12.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Warning: Nashorn engine is planned to be removed from a future JDK release
Executing work item WorkItem 1 [name=Human Task, state=0, processInstanceId=1, parameters{Comment=Please perform a self-evalutation., Skippable=false, reason=Yearly performance evaluation, ActorId=krisv, TaskName=Performance Evaluation, NodeName=Self Evaluation}]
Executing work item WorkItem 2 [name=Human Task, state=0, processInstanceId=1, parameters{Comment=You need to evaluate krisv., Skippable=false, reason=Yearly performance evaluation, TaskName=Performance Evaluation, NodeName=HR Evaluation, GroupId=HR}]
Executing work item WorkItem 3 [name=Human Task, state=0, processInstanceId=1, parameters{Comment=You need to evaluate krisv., Skippable=false, reason=Yearly performance evaluation, TaskName=Performance Evaluation, NodeName=PM Evaluation, GroupId=PM}]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.958 s <<< FAILURE! - in org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest
[ERROR] testJbpmRuntimeManagerWithPersistence(org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest)  Time elapsed: 4.669 s  <<< ERROR!
java.lang.IllegalArgumentException: javax.persistence.metamodel.Metamodel referenced from a method is not visible from class loader
	at org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManagerWithPersistence(KieSpringjBPMPersistenceKarafIntegrationTest.java:127)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManagerWithPersistence:127 » IllegalArgument
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by tkobayas** [comment]
Ah, kie-karaf-itests tests are skipped for JDK 11. Maybe intentional? @jiripetrlik

**Comment by mareknovotny** [comment]
that is true as tests on JDK11 were not possible to fix.

**Pull request merged**
