### PR TITLE
AF-593+: Move uberfire-maven-utils to kie-soup.

### PR DESCRIPTION
**Pull request by mbarkley**
Please see this [PR](https://github.com/kiegroup/kie-soup/pull/8) for general discussion.

### CODE REVIEW

**Comment by psiroky** [comment]
This is just one PR in a long list. They all need to merged together. The build is broken at this point, so we should probably revert this until all the other PRs are ready.

**Comment by psiroky** [comment]
Reverted https://github.com/kiegroup/droolsjbpm-integration/commit/acb24bea6d4e2d35536a571541e463735113847f. @mbarkley could you please open new PR with the same changes?

**Comment by mbarkley** [comment]
@psiroky I am just going to close the rest of the PRs and send them all again when they are ready.

I forgot that I need to move XStreamUtils from kie-internal to kie-soup before the uberfire PR has any chance of passing.

**Comment by mbarkley** [comment]
@psiroky [Done](https://github.com/kiegroup/droolsjbpm-integration/pull/1247).

**Pull request merged**
