### PR TITLE
[7.7.x] Skip several tests on Jenkins as they tend to be unstable there

### PR DESCRIPTION
**Pull request by sutaakar**
Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1489

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
@MarianMacik Can you please cherrypick this PR to your one to have all related changes in one PR?

**Comment by MarianMacik** [comment]
@sutaakar Sure, will do.

**Comment by sutaakar** [comment]
PR cherrypicked in https://github.com/kiegroup/droolsjbpm-integration/pull/1499 , closing

**Pull request closed without merging**
