### PR TITLE
[reproducer] Spring issue reproducer

### PR DESCRIPTION
**Pull request by sutaakar**
@mswiderski Failure occurs in testPersistenceTimer(). It should be reproducible in IDE.

### CODE REVIEW

**Comment by mswiderski** [comment]
Is this suppose to fail/hang or it should be fine as you removed the test annotations?

**Comment by sutaakar** [comment]
It should hang, I removed other test annotations so we can focus just on this test. It doesn't seem to be affected by other tests.

**Comment by mswiderski** [comment]
Since you pin pointed the issue maybe ignore the test for now so we don't block PR builds. Wdyt?

**Comment by sutaakar** [comment]
Yes, we can, will prepare PR.

**Comment by sutaakar** [comment]
PR prepared: https://github.com/kiegroup/droolsjbpm-integration/pull/864

**Pull request closed without merging**
