### PR TITLE
Fix maven integration tests

### PR DESCRIPTION
**Pull request by baldimir**

### CODE REVIEW

**Comment by mareknovotny** [comment]
some port not free up.

Jenkins retest this please

**Comment by mareknovotny** [comment]
you can do a change just once @baldimir on main and then label it with backport_branchname label and the backport PRs will be created by bot automatically ;)

**Review by porcelli — APPROVED** [review]

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
there is now problem with nighties which fails right in the kie-maven-plugin on 13 tests due this changes on both branches (7.67.x and 7.67.x-blue). We need to revert and get back to the original problem what causes it and how to fix it properly.
```
[2024-03-14T20:21:57.256Z] [INFO] -------------------------------------------------
[2024-03-14T20:21:57.256Z] [INFO] Build Summary:
[2024-03-14T20:21:57.256Z] [INFO]   Passed: 5, Failed: 13, Errors: 0, Skipped: 0
[2024-03-14T20:21:57.256Z] [INFO] -------------------------------------------------
[2024-03-14T20:21:57.256Z] [ERROR] The following builds failed:
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-10-default/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-10-yes-generate/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-11-default/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-11-yes-generate/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-12/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-13/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-6/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-7-exec-model/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-7-no-exec-model/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-8-exec-model/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-8-no-exec-model/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-9-exec-model/pom.xml
[2024-03-14T20:21:57.256Z] [ERROR] *  kie-maven-plugin-test-kjar-9-no-exec-model/pom.xml
[2024-03-14T20:21:57.256Z] [INFO] -------------------------------------------------
```

**Comment by porcelli** [comment]
@mareknovotny can you share how CI is building this? Because in local this is clearly broken and when applied the changes here it fixes.

**Comment by mareknovotny** [comment]
you should have access to CI @porcelli look there, it is available to see at https://kiegroup.github.io/droolsjbpm-build-bootstrap/job/productization-jobs

**Comment by mareknovotny** [comment]
the command is basically `mvn -B -s /tmp/tmp.eOYreVYwXO-settings.xml -fae dependency:tree deploy -B -Dfull=true -Drevapi.skip=true -Denforcer.skip=true -Dgwt.compiler.localWorkers=1 -Dproductized=true -Dfindbugs.skip=true -Dcheckstyle.skip=true -DaltDeploymentRepository=local::default::file:///home/jenkins/workspace/PROD_rhba.nightly_7.67.x/deployDirectory -DskipTests=true`

**Pull request merged**
