### PR TITLE
[DROOLS-1655] unregister statful ksession from the kcontainer when it…

### PR DESCRIPTION
**Pull request by mariofusco**
… is disposed

### CODE REVIEW

**Comment by mariofusco** [comment]
Depends on https://github.com/kiegroup/drools/pull/1369

**Comment by mariofusco** [comment]
ok to test

**Comment by mariofusco** [comment]
ok to test

**Comment by mariofusco** [comment]
ok to test

**Comment by mariofusco** [comment]
@mswiderski @tarilabs can you please check if these failures are related with my change? I gave a quick look and I don't think so.

**Comment by tarilabs** [comment]
I agree it's a number of test from ` org.kie.server.integrationtests.jbpm.cases.` package. Unfortunately I'm focused on other tasks and haven't had time to lurk inside case management atm

**Comment by mswiderski** [comment]
@mariofusco looking at another PR that I sent today (regarding changing the transaction manager for local tests - IDE) there are no such failures so I would assume these are related then. I can take a closer look tomorrow morning.

**Comment by mswiderski** [comment]
@mariofusco looks like the error comes from this https://github.com/kiegroup/jbpm/blob/master/jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java#L576 - which means somehow the case file is no longer in working memory...

**Comment by mariofusco** [comment]
ok to test

**Comment by tarilabs** [comment]
```
08:37:28 Unexpected error while executing the UpstreamReposBuilder! null
08:37:28 java.lang.NullPointerException
08:37:28 	at org.kie.jenkinsci.plugins.kieprbuildshelper.GitHubUtils.findOpenPullRequest(GitHubUtils.java:62)
```

Jenkins test again

**Comment by tarilabs** [comment]
<details>

```
12:49:05 FATAL: command execution failed
12:49:05 hudson.remoting.ChannelClosedException: channel is already closed
12:49:05 	at hudson.remoting.Channel.send(Channel.java:604)
12:49:05 	at hudson.remoting.Request.call(Request.java:130)
12:49:05 	at hudson.remoting.Channel.call(Channel.java:821)
12:49:05 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:256)
12:49:05 	at com.sun.proxy.$Proxy94.isAlive(Unknown Source)
12:49:05 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1043)
12:49:05 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1035)
12:49:05 	at hudson.Launcher$ProcStarter.join(Launcher.java:399)
12:49:05 	at hudson.tasks.Maven.perform(Maven.java:367)
12:49:05 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:49:05 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
12:49:05 	at hudson.model.Build$BuildExecution.build(Build.java:205)
12:49:05 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
12:49:05 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
12:49:05 	at hudson.model.Run.execute(Run.java:1728)
12:49:05 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:49:05 	at hudson.model.ResourceController.execute(ResourceController.java:98)
12:49:05 	at hudson.model.Executor.run(Executor.java:404)
12:49:05 Caused by: java.io.IOException
12:49:05 	at hudson.remoting.Channel.close(Channel.java:1284)
12:49:05 	at hudson.remoting.Channel.close(Channel.java:1255)
12:49:05 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:703)
12:49:05 	at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:674)
12:49:05 	at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:86)
12:49:05 	at jenkins.model.Jenkins.access$2000(Jenkins.java:325)
12:49:05 	at jenkins.model.Jenkins$22.run(Jenkins.java:3293)
12:49:05 	at hudson.model.Queue._withLock(Queue.java:1309)
12:49:05 	at hudson.model.Queue.withLock(Queue.java:1186)
12:49:05 	at jenkins.model.Jenkins._cleanUpDisconnectComputers(Jenkins.java:3287)
12:49:05 	at jenkins.model.Jenkins.cleanUp(Jenkins.java:3163)
12:49:05 	at hudson.WebAppMain.contextDestroyed(WebAppMain.java:381)
12:49:05 	at org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:808)
12:49:05 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextDestroyed(ServletContextHandler.java:457)
12:49:05 	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:842)
12:49:05 	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:215)
12:49:05 	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:529)
12:49:05 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
12:49:05 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
12:49:05 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
12:49:05 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:73)
12:49:05 	at org.eclipse.jetty.server.Server.doStop(Server.java:456)
12:49:05 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
12:49:05 	at winstone.Launcher.shutdown(Launcher.java:305)
12:49:05 	at winstone.ShutdownHook.run(ShutdownHook.java:25)
12:49:05 Build step 'Invoke top-level Maven targets' marked build as failure
12:49:05 Email was triggered for: Failure - Any
12:49:05 Sending email for trigger: Failure - Any
12:49:05 ERROR: rhel7-large-9046 is offline; cannot locate jdk1.8
12:49:05 ERROR: rhel7-large-9046 is offline; cannot locate jdk1.8
12:49:05 ERROR: rhel7-large-9046 is offline; cannot locate jdk1.8
12:49:05 ERROR: rhel7-large-9046 is offline; cannot locate jdk1.8
```

</details>

Jenkins test again

**Comment by tarilabs** [comment]
Jenkins test again please

**Comment by tarilabs** [comment]
```
Test Result (1 failure / +1)
org.kie.server.integrationtests.jbpm.search.TaskSearchServiceIntegrationTest.testFindTaskWithActivationTimeEqualsToFilter[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42592/kie-server-services/services/rest/server'}]
```

Jenkins test again

**Comment by mariofusco** [comment]
@tarlabs this seems to be endless :) Thanks for your help anyway.

**Comment by tarilabs** [comment]
@mariofusco np the CaseMgt seems now resolved, what I believe we're interested to check now if the ltests askSearchServiceIntegrationTest.testFindTaskWithActivationTimeEqualsToFilter failure is a flaky or not. I would assume it's a flaky random test given I don't see the other transport option listed as failed for the same test, but better to check again..

**Comment by sutaakar** [comment]
@tarilabs @mariofusco TaskSearchServiceIntegrationTest.testFindTaskWithActivationTimeEqualsToFilter instability should be fixed as part of https://github.com/kiegroup/droolsjbpm-integration/pull/1058

**Comment by tarilabs** [comment]
```
Test Result (1 failure / -2)
org.kie.server.integrationtests.jbpm.search.TaskSearchServiceIntegrationTest.testFindTaskWithActivationTimeEqualsToFilter[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:39681/kie-server-services/services/rest/server'}]
```

**Comment by tarilabs** [comment]
thanks @sutaakar

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
