### PR TITLE
[DROOLS-1379] Update versions in POMs

### PR DESCRIPTION
**Pull request by triceo**
I merged #976, an old PR. It was green, but I did not think to retest. Turns out it was not actually green any more. Lesson learned.

### CODE REVIEW

**Comment by triceo** [comment]
Jenkins please retest this.

**Comment by triceo** [comment]
Build failure seems unrelated to this PR. Asking @baldimir and @sutaakar  to confirm.

**Comment by domhanak** [comment]
@markcoble failures here are related to #1040 You did change a test logic as a part of formatting changes and they are now randomly failing. Missed by reviews. Could you please fix it back?

**Comment by sutaakar** [comment]
@domhanak Can you please check the issues? They seems related to search tests.

**Pull request merged**
