### PR TITLE
[BXMSPROD-1037] - exclusions for Enforcer banDuplicationClasses viola…

### PR DESCRIPTION
**Pull request by akoufoudakis**
[BXMSPROD-1037] - exclusions for Enforcer banDuplicationClasses violation

**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1037

**referenced Pull Requests**:
* parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1557

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
please rebase this PR and find the way how to fix failed tests which are directly related to upgrade of jackson

**Review by mareknovotny — CHANGES_REQUESTED** [review]
there is probably clash between Springboot managed jackson and the upgraded version therefore the tests failed

**Comment by akoufoudakis** [comment]
Closing the PR. The proper fix is here: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1593.

**Pull request closed without merging**
