### PR TITLE
[JBPM-9579] Adding a pagination parameter to LogCleanupCommand

### PR DESCRIPTION
**Pull request by fjtirado**
Integration test

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9579)

**referenced Pull Requests**: 
https://github.com/kiegroup/droolsjbpm-knowledge/pull/499
https://github.com/kiegroup/jbpm/pull/1853

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Pull request merged**
