### PR TITLE
[7.2.x] JBPM-6261 - Workbench UI doesn't show errors if Projects is not possi…

### PR DESCRIPTION
**Pull request by mswiderski**
…ble to deploy

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
@pefernan @manstis there seems to be some failures in the stunner ... is it known issue or?

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@mswiderski It's an intermittent fault with our use of FreeMarker... if you see this type of error just re-build (for now.. one day we may actually look into a fix.. but for now it's quicker to rebuild).

**Comment by mswiderski** [comment]
@manstis this PR seems to be really unlucky... trying one more time ...

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
test failure not related to this PR

**Pull request merged**
