### PR TITLE
[7.59.x] [RHPAM-3784] Prometheus exporter: KiE Server gives wrong count 

### PR DESCRIPTION
**Pull request by spolti**
JIRA: https://issues.redhat.com/browse/RHPAM-3784

cherry-picks https://github.com/kiegroup/droolsjbpm-integration/pull/2646

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by spolti** [comment]
Jenkins retest this please

**Comment by spolti** [comment]
@cristianonicolai @mareknovotny can this be merged?

**Comment by mareknovotny** [comment]
according to jira it targets next coming release and we need to wait for opening the 7.59.x branch for this, right now only blockers are accepted for merging.

**Pull request merged**
