### PR TITLE
[DROOLS-5688] Implement PMML mojo

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik

See https://issues.redhat.com/browse/DROOLS-5688

This PR
1) Create/adapt _GeneratePMMLModelMojo_ inside kie-maven-plugin to use the newly created public API
2) create the  kie-maven-plugin-integration-tests module to contain integration-tests based on standard maven-invoker
3) create kie-pmml-trusty-integration-tests module inside the previous one
4) remove PMML-trusty tests from the takari-based testing module (kie-plugin-testing)

Depends on https://github.com/kiegroup/drools/pull/3162

### CODE REVIEW

**Comment by gitgabrio** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
please link here also dependent PR(s) @gitgabrio

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by gitgabrio** [comment]
@lucamolteni 
FYI: look inside kie-maven-plugin/src/it

**Review by danielezonca — APPROVED** [review]
LGTM :+1:

**Pull request merged**
