### PR TITLE
[RHPAM-2421] OpenShiftStartupStrategy doesn't respin Kie server pods after Kie container change.

### PR DESCRIPTION
**Pull request by rhtevan**
The solution is moving away from annotating KieServer DC with a change timestamp for triggering a rollout to leveraging fabric8 client deployment API directly.

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

### CODE REVIEW

**Comment by kie-ci3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by rhtevan** [comment]
@mswiderski Appreciated very much if you help merge this PR for fixing a blocker issue for 7.5 release.

cc @errantepiphany @sutaakar

**Comment by mswiderski** [comment]
I can merge ... though would like to have green build. Is these test failures known issues or?

**Comment by rhtevan** [comment]
@sutaakar Could you help take a look those integration test failures. Looks like test case may need some updates.

**Comment by sutaakar** [comment]
Will take a look.

**Comment by sutaakar** [comment]
@rhtevan The tests are passing on 7.28.x and failing on 7.29.x . Considering that 7.29.x has been tagged few hours ago it may happen that not all needed artifacts were built. I think we can retrigger the PR check tomorrow.

**Comment by sutaakar** [comment]
@rhtevan the failures seem to be related to https://github.com/kiegroup/drools/pull/2574

**Comment by sutaakar** [comment]
@tarilabs It seems that changes made by https://github.com/kiegroup/drools/pull/2574 are related to the test failures. The https://github.com/kiegroup/droolsjbpm-integration/blob/master/camel-container-tests/camel-container-integration-tests/src/test/resources/org/kie/camel/container/integration/tests/kjar/FunctionDefinition.dmn is not being correctly resolved. Can you please take a look and tell us what is wrong there?

**Comment by tarilabs** [comment]
@sutaakar I believe what is actually wrong is for the test to expect zero message what-so-ever, instead of checking that there are no Error(s) --and allow for Warn(s) to be reported.

Ref, https://github.com/kiegroup/droolsjbpm-integration/blob/ace243f7df28d184b25f61f69e395437f3c4f999/camel-container-tests/camel-container-integration-tests/src/test/java/org/kie/camel/container/integration/tests/remote/AbstractRemoteIntegrationTest.java#L102

image

/cc @jiripetrlik @etirelli

**Comment by tarilabs** [comment]
In any case thanks @sutaakar for reporting this about kiegroup/drools#2574 it is clear the heuristic must be further improved to not throw a Warn for that `.dmn` model.

You can take the action to Revert the kiegroup/drools#2574 merge commit if that is blocking some of you work!
I will improve the heuristic for this case, next week.

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by rhtevan** [comment]
@mswiderski It's all green now. Could you help merge it. Thanks!

**Comment by mareknovotny** [comment]
Merging as the #1915 was merged and this is the same change

**Pull request merged**
