### PR TITLE
DROOLS-6085 DMN fix OAS server default url when embedded as Spring Boot

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6085

**referenced Pull Requests**: none

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
@sutaakar can you kindly help me trigger manually the Spring Boot verification "nightly" please ?

Locally it worked following your suggestions

**Comment by sutaakar** [comment]
jenkins execute springboot build

**Comment by sutaakar** [comment]
The nightly SpringBoot check will verify this once merged, the command above should check the SpringBoot with the PR.

**Comment by sutaakar** [comment]
Checking what is the issue with SpringBoot build....

**Review by MarianMacik — APPROVED** [review]
Looks good to me.

**Review by sutaakar — APPROVED** [review]
Looks good to me.

**Review by hellowdan — APPROVED** [review]

**Pull request merged**
