### PR TITLE
[DROOLS-7071] Fix kie-karaf-itests failures because of poi version

### PR DESCRIPTION
**Pull request by tkobayas**
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7071

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Updated apache POI version for karaf features to meet drools' dependency. (other bundles are required for POI's dependencies).

Please review @grgrzybek @jiripetrlik , thanks!

**Review by jiripetrlik — CHANGES_REQUESTED** [review]
Hello @tkobayas and thank you for your fix! It seems that the version for community Karaf works well. It would be also good to fix the version for Fuse. I wrote about it in more detail in the related JIRA.

**Comment by tkobayas** [comment]
@jiripetrlik Thank you for the suggestion. I updated features-fuse.xml as well and confirmed that kie-karaf-itests works with fuse locally.

**Review by grgrzybek — APPROVED** [review]

**Comment by grgrzybek** [comment]
:+1:

**Comment by tkobayas** [comment]
Hi @mariofusco Please merge this PR, thanks! (This one is not 7.67.x. Just to fix CI test failures in main = 7.x)

**Review by mariofusco — APPROVED** [review]

**Review by jiripetrlik — COMMENTED** [review]
Thank you @tkobayas for the additional fix. I was able to run it successfully also with Fuse.

**Pull request merged**
