### PR TITLE
[7.67.x-blue] Fix maven plugin tests

### PR DESCRIPTION
**Pull request by baldimir**
Fix broken build of kie-maven-plugin integration tests projects.

### CODE REVIEW

**Review by porcelli — APPROVED** [review]
thank you @baldimir - I confirm that this works. the invoker still being executed, but this time without failure.

**Comment by mareknovotny** [comment]
failed `org.kie.server.springboot.samples.KeycloakKieServerTest.org.kie.server.springboot.samples.KeycloakKieServerTest`

jenkins retest this

**Comment by porcelli** [comment]
thank you for looking at it @mareknovotny - but I don't think the invoker change has anything to do with the failed test. the change in the invoker is isolated to the `kie-maven-plugin` directory/module

**Comment by mareknovotny** [comment]
the last failure is `org.kie.server.integrationtests.jbpm.JobServiceIntegrationTest.testScheduleAndRunJob[JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35167/kie-server-services/services/rest/server'}]` so previous failure is gone.

@baldimir @porcelli even the failed test is not always related it is good to re-run the CI to see it confirmed.

**Comment by porcelli** [comment]
agree, and that’s the problem of a flaky CI environment - we keep running trying get lucky 🙃

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
