### PR TITLE
[7.52.x]JBPM-9708 Allow navigation from the parent process instance to the child process instance using Process Diagram

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[https://issues.redhat.com/browse/JBPM-9708](JBPM-9708)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Review by prashuts — APPROVED** [review]
LGTM

**Comment by jstastny-cz** [comment]
jenkins retest this and run fdb

**Review by jstastny-cz — APPROVED** [review]
Works fine. Please make sure PR check failures are reviewed.

**Comment by bxf12315** [comment]
Jenkins run fdb

**Review by nmirasch — APPROVED** [review]

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by nmirasch** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Pull request merged**
