### PR TITLE
BXMSPROD-494 allow GA build on windows machine

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-494

related to

https://github.com/kiegroup/lienzo-core/pull/133
https://github.com/kiegroup/lienzo-tests/pull/108
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1471
https://github.com/kiegroup/kie-soup/pull/158
https://github.com/kiegroup/appformer/pull/1054
https://github.com/kiegroup/droolsjbpm-knowledge/pull/465
https://github.com/kiegroup/drools/pull/3116
https://github.com/kiegroup/optaplanner/pull/940
https://github.com/kiegroup/jbpm/pull/1758
https://github.com/kiegroup/kie-jpmml-integration/pull/43
https://github.com/kiegroup/droolsjbpm-integration/pull/2243
https://github.com/kiegroup/openshift-drools-hacep/pull/100
https://github.com/kiegroup/droolsjbpm-tools/pull/118
https://github.com/kiegroup/kie-uberfire-extensions/pull/106
https://github.com/kiegroup/kie-wb-playground/pull/97
https://github.com/kiegroup/kie-wb-common/pull/3423
https://github.com/kiegroup/drools-wb/pull/1423
https://github.com/kiegroup/optaplanner-wb/pull/381
https://github.com/kiegroup/jbpm-designer/pull/891
https://github.com/kiegroup/jbpm-wb/pull/1461
https://github.com/kiegroup/jbpm-work-items/pull/153
https://github.com/kiegroup/kie-docs/pull/2849
https://github.com/kiegroup/optaweb-employee-rostering/pull/498
https://github.com/kiegroup/optaweb-vehicle-routing/pull/367
https://github.com/kiegroup/kie-wb-distributions/pull/1062

### CODE REVIEW

**Comment by mareknovotny** [comment]
we need to rebase this @Ginxo

**Comment by Ginxo** [comment]
I'm afraid we will have a disk space problem on windows machine. Trying to find a solution for it.

**Comment by Ginxo** [comment]
windows error `fatal: cannot create directory at 'kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel': Filename too long`

**Comment by Ginxo** [comment]
after adding

```
- name: Support longpaths
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
```

The error appears, so I guess there's no easy way to skip too long problem here
```
[INFO] ------------------------------------------------------------------------
2021-03-11T11:28:48.0657100Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (default) on project kie-server-services-task-assigning-user-system-api: MavenReportException: Error while generating Javadoc: Unable to execute javadoc command: Error while executing process. Cannot run program "C:\hostedtoolcache\windows\jdk\11.0.10\x64\bin\javadoc.exe" (in directory "D:\a\droolsjbpm-integration\droolsjbpm-integration\kiegroup\droolsjbpm_integration\kie-server-parent\kie-server-services\kie-server-services-task-assigning\kie-server-services-task-assigning-user-system\kie-server-services-task-assigning-user-system-api\target\apidocs"): CreateProcess error=267, The directory name is invalid -> [Help 1]
```

**Comment by mareknovotny** [comment]
closing this PR as not possible for now

**Pull request closed without merging**
