### PR TITLE
[JBPM-9734] KafkaConsumerHappyPathTest flaky tests

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9734](https://issues.redhat.com/browse/JBPM-9734)

Cherry-pick from 95dc6a7c589109a5c231e32a5cc68063296be423

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
Failures are unrelated, could you merge @mareknovotny ?

**Comment by mareknovotny** [comment]
timeout happened (I am curious why even 5 hours is not enough to finish FDB here. It even didn't started downstream repository build, still processing this repository.
Jenkins do fdb

**Comment by mareknovotny** [comment]
the average build time for previous PR runs are around 3 hours and something. So 5 hours is really extreme which is probably caused by a hanging some test or Jenkins master were again restarted.
Merging now, but please check this if it is not helping in stability for coming PRs on this repo

**Pull request merged**
