### PR TITLE
PLANNER-1622: [Tasks Assignment] Planning model iteration #1

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
Hi @rsynek that's the peer version of the PR against the jbpm-task-assigning feature branch.

**Comment by rsynek** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
Closed since we found that to keep a parallel jenkins jobs for having CI for the feature branch is not straight ahead. We'll consider moving to this approach only if we find it's necessary at some point

**Pull request closed without merging**
