### PR TITLE
JBPM-9431: Unable to add deployment unit while creating very first container (#2295)

### PR DESCRIPTION
**Pull request by akumar074**
* Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2295

(cherry picked from commit 121c1d2d336e20e00a5f68241a77231cde32887d)

**JIRA**: 
 * [RHPAM-3254](https://issues.redhat.com/browse/RHPAM-3254)
 * [JBPM-9431](https://issues.redhat.com/browse/JBPM-9431)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by prashuts** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Review by prashuts — APPROVED** [review]
LGTM

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
