### PR TITLE
[RHPAM-1975] ServerTemplateConverter breaks with KieServerMode mixed-case

### PR DESCRIPTION
**Pull request by rhtevan**
Improve resiliency by accommodating unexpected character case.     

Related JIRAs
https://issues.jboss.org/projects/RHPAM/issues/RHPAM-1975
https://issues.jboss.org/browse/KIECLOUD-121

### CODE REVIEW

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by rhtevan** [comment]
@sutaakar Is this something you could do a quick check. Thanks!

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by rhtevan** [comment]
@sutaakar Shall we merge this PR now, or still have something to clear up?

**Comment by sutaakar** [comment]
I think it could be merged

**Comment by rhtevan** [comment]
Please help to merge this PR. Thanks!

**Comment by sutaakar** [comment]
@mswiderski Can you please take a look and merge if ok?

**Pull request merged**
