### PR TITLE
JBPM-6233: Websocket test stabilization

### PR DESCRIPTION
**Pull request by sutaakar**
To be possible to run websocket tests against custom deployments.

### CODE REVIEW

**Comment by mswiderski** [comment]
@sutaakar could this be related in anyway?
https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/droolsjbpm-integration-pullrequests/1513/testReport/junit/org.kie.server.integrationtests.controller/WebsocketKieControllerStartupIntegrationTest/testContainerDisposedAfterStartup_JSON_/

**Comment by sutaakar** [comment]
@mswiderski I think it is a race condition. Will soon create a JIRA for it.

**Comment by mswiderski** [comment]
@sutaakar shall we then hold this PR?

**Comment by sutaakar** [comment]
@mswiderski yes, we can.

**Comment by sutaakar** [comment]
@mswiderski Tests should be stabilized now. Race condition bug reported in JBPM-6316.

**Comment by mswiderski** [comment]
@sutaakar so this one is ready to be merged, right?

**Comment by sutaakar** [comment]
@mswiderski yes

**Pull request merged**
