### PR TITLE
JBPM-7877 - KIE Server documentation with examples

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/856

improvements to swagger docs to include payload information (examples) so they can be presented in swagger ui and generated docs.

swagger ui with examples
image

and the generated asciidoc out of the swagger
image 1

### CODE REVIEW

**Comment by sutaakar** [comment]
@mswiderski Nice job :)
@sterobin FYI, this may help you with Kie server REST requests.

**Comment by sterobin** [comment]
@mswiderski, nice! This is in line with where I’m going with my doc effort. Can you make the example responses in json as well so that both the requests and responses are json in every case? As you and I discussed, they should all be the same and json makes the most sense to use with how common it is. This is what I’m doing in my current doc effort for this API. 

Also, one thing I’m doing too is coming up with actual example bodies and responses with actual example data, which I think is optimal to show users helpful example values instead of just “string”. After I’m done, I’ll be asking for all of my examples (after SME help/sing-off) to be applied to the swagger page as well. Do you foresee any problems with that?

**Comment by mswiderski** [comment]
@sterobin have a look at published api docs based on this work 
http://jbpm.org/api-docs/paths.html

I am looking into responses as well

**Comment by mswiderski** [comment]
@cristianonicolai here is the work we talked about

**Comment by kuppumani** [comment]
Thank you.

Let me check and let you know the status.

Regards,

Kuppumani M

**Comment by kuppumani** [comment]
Hi,

I am trying with spring boot with jBPM. Please share the source code for
the same. Thank you.

Regards,
Kuppumani

**Comment by kuppumani** [comment]
hi,

How to deploy my business process model by using spring boot deployment
service?

Regards,
Kuppumani   M

**Comment by MarianMacik** [comment]
@kuppumani If you need help regarding jbpm, you can get further information at [jbpm.org website](http://jbpm.org/community/getHelp.html), namely you can use our Freenode IRC Channel or our mailing lists jbpm-usage@googlegroups.com or jbpm-setup@googlegroups.com.

**Comment by kuppumani** [comment]
Sure, we are trying to implement spring boot with jBPM . In other words
embedded jbpm engine with Spring Boot.

Below scenarios we are trying.
1. Migration from one version to another version.
2.deployment service
3. Entire user task lifecycle.
4.deployment service.

Actually we are trying all workbench functionality in embedded jBPM engine
with spring boot.   Thank you.

Regards.
Kuppumani M

**Pull request merged**
