### PR TITLE
JBPM-5976 - Provide auto acknowledge jobs for execution errors

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/kiegroup/jbpm/pull/893

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
Will take a look at the failures later today

**Comment by mswiderski** [comment]
should be fixed with https://github.com/kiegroup/jbpm/pull/895 which uses the same branch so let's retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request merged**
