### PR TITLE
DROOLS-1509 ServiceResponse XStream marshalling inconsistencies with …

### PR DESCRIPTION
**Pull request by tarilabs**
…JAXB.

Examples provided on the related JIRA.

### CODE REVIEW

**Comment by tarilabs** [comment]
@mswiderski @etirelli can you review, please?

**Comment by mswiderski** [comment]
looks ok to me, not entirely sure if this breaks backward compatibility if the payload is send without kie server client (which is rather rare case anyway). 

+1 from me

**Comment by etirelli** [comment]
+1, if we need to break the API, now is the time.

**Comment by psiroky** [comment]
@tarilabs could you please mention this breakage in the docs?

**Comment by tarilabs** [comment]
@psiroky done: kiegroup/kie-docs#228

**Pull request merged**
