### PR TITLE
RHPAM-1878: exclude because of byte-buddy upgrade

### PR DESCRIPTION
**Pull request by mbiarnes**
…ound

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/924

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mswiderski** [comment]
@MariaMacik do you think it’s worth to run spring boot tests?

**Comment by MarianMacik** [comment]
@mswiderski why not, since we now have it...

jenkins execute springboot build

**Pull request merged**
