### PR TITLE
DROOLS-6570 Swagger(v2) documentation of Kie Server DMN endpoints

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6570

**referenced Pull Requests**: none

Commit 034c829 refers to revapi changes, since the Java annotations changed (to include these examples indeed).

<details>
<summary>
Preview screenshots
</summary>

### Before

before

### After

after

</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
```
[2021-08-26T15:57:17.942Z] [INFO] Container tests for Camel integration .............. FAILURE [05:30 min]
[2021-08-26T15:57:17.942Z] [INFO] OptaPlanner core GWT wrapper for OptaPlanner Workbench SKIPPED
[2021-08-26T15:57:17.942Z] [INFO] Drools :: High Availability ........................ SKIPPED
[2021-08-26T15:57:17.942Z] [INFO] Drools :: High Availability :: HA-Remote ........... SKIPPED
[2021-08-26T15:57:17.942Z] [INFO] Drools :: High Availability :: HA-Core ............. SKIPPED
[2021-08-26T15:57:17.942Z] [INFO] Drools :: High Availability :: HA-Core-Infra ....... SKIPPED
[2021-08-26T15:57:17.942Z] [INFO] Drools and jBPM integration distribution ........... SKIPPED
[2021-08-26T15:57:17.942Z] [INFO] BPMS distribution .................................. SKIPPED
[2021-08-26T15:57:17.942Z] [INFO] BRMS distribution .................................. SKIPPED
[2021-08-26T15:57:17.942Z] [INFO] ------------------------------------------------------------------------
[2021-08-26T15:57:17.942Z] [INFO] BUILD FAILURE
[2021-08-26T15:57:17.942Z] [INFO] ------------------------------------------------------------------------
[2021-08-26T15:57:17.942Z] [INFO] Total time:  04:04 h
[2021-08-26T15:57:17.942Z] [INFO] Finished at: 2021-08-26T11:57:05-04:00
[2021-08-26T15:57:17.942Z] [INFO] ------------------------------------------------------------------------
[2021-08-26T15:57:17.942Z] [ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven3-plugin:1.9.3:start (start-container) on project camel-container-integration-tests: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly23xInstalledLocalContainer@55e92493]: Monitor [org.codehaus.cargo.container.spi.startup.CombinedContainerMonitor] failed to detect running container within the timeout period [300000]. -> [Help 1]
[2021-08-26T15:57:17.942Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.cargo:cargo-maven3-plugin:1.9.3:start (start-container) on project camel-container-integration-tests: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly23xInstalledLocalContainer@55e92493]
```

Jenkins retest this

**Comment by tarilabs** [comment]
```
Test Result (3 failures / ±0)
org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskCompletedBoundaryTimerProcessInstanceorg.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskNotCompletedBoundaryTimerProcessInstance
org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskNotCompletedBoundaryTimerProcessInstance
```

🤷 unrelated, will give 1 more shot

Jenkins retest this

**Comment by tarilabs** [comment]
now `264 failed.`

🤔 🤷 

Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins retest this

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
