### PR TITLE
JBPM-9935 : JMS login is using JAAS to get username and roles

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 34f3cd675c3960e60268bef293ec6d778d1ac13e)

**JIRA**:  

[JBPM-9935](https://issues.redhat.com/browse/JBPM-9935)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by sutaakar** [comment]
Please rebase

**Review by mareknovotny — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Rikkola** [comment]
Kafka tests failing.
```
org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest.testAsyncKafkaWIH[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest.testAsyncKafkaWIH[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest.testAsyncKafkaWIHNoConnection[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest.testAsyncKafkaWIHNoConnection[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest.testAsyncKafkaWIHConnectedLater[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest.testAsyncKafkaWIHConnectedLater[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaSampleTest.testKafkaWIHSendMessage[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaSampleTest.testKafkaWIHSendMessage[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaSerializationTest.testKafkaWIHSendMessage[2: PER_REQUEST]
org.jbpm.workitem.springboot.samples.KafkaSerializationTest.testKafkaWIHSendMessage[2: PER_REQUEST]
```
jenkins do fdb

**Comment by mareknovotny** [comment]
i think all failed tests are related to https://github.com/kiegroup/jbpm-work-items/pull/224

**Comment by Rikkola** [comment]
@mareknovotny sounds about right, but we can rerun the tests now that it is in.

**Comment by mareknovotny** [comment]
no doubt about that @Rikkola 

> @mareknovotny sounds about right, but we can rerun the tests now that it is in.

no doubt about that @Rikkola !

**Comment by mareknovotny** [comment]
ok, now failed only 
`org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest.testAsyncKafkaWIHNoConnection[0: SINGLETON]` which is not related to this change, but @afalhambra can explain why the fix didn't helped in 100% of cases ;)

**Comment by afalhambra** [comment]
Hi @mareknovotny @Rikkola,
Previous errors in kafka tests were related to https://github.com/kiegroup/jbpm/pull/2052 but those were fixed with this kiegroup/jbpm-work-items#224
However, we know there are still some flaky tests like the last one you faced which we're trying to improve, but keep in mind they are extremely difficult to reproduce locally
Can you please share the link to the CI job where it fails to confirm the same?

**Comment by mareknovotny** [comment]
@afalhambra https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-integration-main.fdb/57/

**Comment by afalhambra** [comment]
> @afalhambra https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-integration-main.fdb/57/

Yeap, that's a flaky one - and it's already reported https://issues.redhat.com/browse/BXMSPROD-1373 sometime back

**Pull request merged**
