### PR TITLE
JBPM-8018 - CarInsuranceClaimCaseIntegration in Kie Server tests uses wrong data output name to map claimReport after calculation, JBPM-7987 - Spring auto registration doesn’t seem to work for AgendaEventListener

### PR DESCRIPTION
**Pull request by mswiderski**
@sutaakar have a look especially at the first commit (change in bpmn2) for the reported "regression" which actually turned out to be a bug in the case definition.

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by sutaakar** [comment]
The build fails due to undeclared transitive dependencies:

> [WARNING] Rule 0: de.is24.maven.enforcer.rules.IllegalTransitiveDependencyCheck failed with message:
Found 2 illegal transitive type dependencies in artifact 'org.kie:kie-server-spring-boot-autoconfiguration-drools:jar:7.16.0-SNAPSHOT':
1.) org.kie.api.event.rule.AgendaEventListener
2.) org.kie.api.event.rule.RuleRuntimeEventListener

**Comment by mswiderski** [comment]
@sutaakar thanks, already fixed

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
test failures are not related

**Pull request merged**
