### PR TITLE
[JBPM-8974] Fix Swagger docs test for working at WAS also

### PR DESCRIPTION
**Pull request by gmunozfe**
This test was failing at Websphere due to parent path navigation provoked HTTP 404 response.
Let's fix it creating the URL ad-hoc.

### CODE REVIEW

**Comment by gmunozfe** [comment]
Right @sutaakar 

I think it's some kind of bug of Websphere. With current `web.xml`, this trace is shown (when GET should be excluded from the list of methods):

_[2/14/20 18:48:30:309 CET] 0000005d WebConstraint I   SECJ8063I: For URL /rest/swagger.json/docs/* in application kie-server-controller-services, the following HTTP methods are **uncovered**, and **not accessible**: TRACE HEAD DELETE POST **GET** OPTIONS PUT_

If  `deny-uncovered-http-methods` is commented in the `web.xml`, all those methods are converted in accessible:

_[2/14/20 18:59:50:920 CET] 0000005c WebConstraint I   SECJ8065I: For URL /rest/swagger.json/docs/* in application kie-server-controller-services, the following HTTP methods are uncovered, and **accessible**: TRACE HEAD DELETE POST GET OPTIONS PUT_

And Swagger is shown

Screenshot from 2020-02-14 19-08-57

**Comment by gmunozfe** [comment]
@sutaakar 

I've found how to fix it without changing `deny-uncovered-http-methods`.

It seems like `rest/swagger.json` resource was not correctly treated by Websphere (console displayed 403 Forbidden), so adding a trailing backslash and asterisk makes it work.
If you agree, this fix can be also added to `web.xml` for kie-server.

**Comment by sutaakar** [comment]
Looks ok.

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
@kiegroup/gatekeepers could you merge this?

**Pull request merged**
