### PR TITLE
[7.67.x-blue] Updating mysql connector gav

### PR DESCRIPTION
**Pull request by LightGuard**
Updating the mysql connector gav.

Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2484
https://github.com/kiegroup/kie-wb-distributions/pull/1244
https://github.com/kiegroup/appformer/pull/1417
https://github.com/kiegroup/jbpm/pull/2433

### CODE REVIEW

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
jenkins retest

**Comment by yesamer** [comment]
Jenkins retest

**Comment by yesamer** [comment]
Jenkins retest it

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run fdb

**Review by yesamer — APPROVED** [review]

**Review by baldimir — APPROVED** [review]

**Comment by baldimir** [comment]
Closing this in favor of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2488 . There were more places that have to be updated, so @yesamer created a new PR chain, so it can be tested together.

**Pull request closed without merging**
