### PR TITLE
[7.44.x][JBPM-9414] Adding integration tests for RHPAM-3106

### PR DESCRIPTION
**Pull request by afalhambra**
**Backport to 7.44.x** - **[JBPM-9414](https://issues.redhat.com/browse/JBPM-9414)**: Adding integration tests for [RHPAM-3106](https://issues.redhat.com/browse/RHPAM-3106)

**referenced Pull Requests**: https://github.com/kiegroup/jbpm/pull/1777
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]
LGTM, thanks @afalhambra

**Comment by mareknovotny** [comment]
marking as DO_NOT_MERGE until 7.44.x branch is open

**Comment by mareknovotny** [comment]
branch 7.44.x is open

**Comment by fjtirado** [comment]
@kiegroup/gatekeepers  please merge this

**Pull request merged**
