### PR TITLE
[JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/JBPM-10101

depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2038

### CODE REVIEW

**Comment by mareknovotny** [comment]
@jiripetrlik  suggested to remove drools-ha completely from git, do you want to do it :) ? @elguardian

**Comment by mareknovotny** [comment]
compilation error

**Review by jiripetrlik — CHANGES_REQUESTED** [review]
@elguardian 
Is there any reason to trying to fix this instead of removing "drools-ha" completely?

**Comment by mareknovotny** [comment]
i still need to remove openshift-drools-hacep repository so it is ok to keep that removal of drools-ha module for that. fyi @jiripetrlik  @elguardian

**Comment by elguardian** [comment]
@mareknovotny that solution was after this PR. I am merging. You can remove it aftewards if you like.

**Pull request merged**
