### PR TITLE
AF-593: Decouple kie-wb-common-datamodel from Drools

### PR DESCRIPTION
**Pull request by mbarkley**

### CODE REVIEW

**Comment by mbarkley** [comment]
Related:
https://github.com/AppFormer/uberfire/pull/822
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/541
https://github.com/kiegroup/droolsjbpm-knowledge/pull/263
https://github.com/kiegroup/drools/pull/1444
https://github.com/kiegroup/jbpm/pull/973
https://github.com/kiegroup/kie-wb-common/pull/1133
https://github.com/kiegroup/drools-wb/pull/596
https://github.com/kiegroup/jbpm-designer/pull/654
https://github.com/kiegroup/jbpm-wb/pull/864
https://github.com/kiegroup/optaplanner-wb/pull/218

**Comment by mbarkley** [comment]
Two of the test failures (in `ContainerConfigPropogationIntegrationTest`) look like timeouts and are not reproducible locally. I suspect they will pass if I rerun the tests.

The remaining tests appear to also fail on master (in `KieBlueprintScannerReimportIntegrationTest` and `KieServerImplTest`). @manstis, any suggestions on who has the expertise to look into this?

**Comment by manstis** [comment]
@mbarkley I guess @mariofusco may be the best to ask.

**Comment by mbarkley** [comment]
@mariofusco It looks like [this](https://github.com/kiegroup/drools/commit/122f30f11701943d89fd4580f39d521b0cf85bf1) commit causes the failures in `KieServerImplTest`. Would you mind looking into this?

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by mbarkley** [comment]
@manstis Alex doesn't get back from PTO for some time.

Maybe someone else could review this instead?

//cc @mswiderski @mariofusco

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Pull request merged**
