### PR TITLE
Workaround for broken OpenShift server mock

### PR DESCRIPTION
**Pull request by mareknovotny**
JIRA:

https://issues.redhat.com/browse/BXMSPROD-1267

**referenced Pull Requests**: 
* parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1699

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Review by sutaakar — APPROVED** [review]
Looks good to me

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
Something wrong in IT setup
`[2021-08-23T10:52:55.857Z] [ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven3-plugin:1.9.3:start (start-container) on project kie-server-integ-tests-case-id-generator: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly23xInstalledLocalContainer@7c30e092]: Monitor [org.codehaus.cargo.container.spi.startup.CombinedContainerMonitor] failed to detect running container within the timeout period [120000]. -> [Help 1]
[2021-08-23T10:52:55.857Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.cargo:cargo-maven3-plugin:1.9.3:start (start-container) on project kie-server-integ-tests-case-id-generator: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly23xInstalledLocalContainer@7c30e092]`

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
parent FDB verified the error and failures are random or related to env.

**Pull request merged**
