### PR TITLE
[DROOLS-6566] Upgrade to Karaf 4.3.2 and fix all (but 3) integration …

### PR DESCRIPTION
**Pull request by grgrzybek**
…tests ... (#2588)

The changes can be summarized:
* there's special kie-osgi-servlet3-compatibility bundle fragment
  provided to handle Servlet API 3/4 OSGi problems
* I've changed dbcp to dbcp2 in "h2" feature to be able to set proper
  ClassLoader to load H2 driver
* droolsjbpm-hibernate no longer needs to "wrap:" hibernate bundles -
  Entity classes should *always* be loaded from the EMF bundle and
  required imports are added in
  KieBlueprintjBPMPersistenceKarafIntegrationTest#getDefaultOptions()
* I've copied changed version of Taskorm.xml from JBPM to reflect model
  changes
* OsgiKieModule can now deal with changed bundle: URI from Felix 6 (OSGi
  Core R7)

(cherry picked from commit 298c727b5023a168d72aa25b00216fa3225a3487)

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
ok to test

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
jenkins retest

**Comment by mbiarnes** [comment]
Jenkins retest this

**Review by jiripetrlik — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
There is some problems with starting ikaraf integration tests `java.rmi.server.ExportException: internal error: ObjID already in use` or `Container never came up` errors.
Failures in  `org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest` should be fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/2593

**Comment by grgrzybek** [comment]
I'll check 7.59.0 branch today. It worked in `main`...

**Comment by grgrzybek** [comment]
sorry for delay - I should be ready with results on Monday.

**Comment by grgrzybek** [comment]
Actually I checked now and ... updated the PR with the most obvious change... It happens to me all the time when I backport new Maven modules to branches with different version...

Now:
```
[ERROR] Tests run: 59, Failures: 0, Errors: 1, Skipped: 3
```

and the only test failing is:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest
[ERROR] org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest  Time elapsed: 0.006 s  <<< ERROR!
com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
Caused by: java.net.BindException: Address already in use (Bind failed)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
```

but this seems (to me) like wiremock issue maybe?

On 2nd attempt it worked:
```
[INFO] Running org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest
17:29:16.748 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.<clinit>:131 - KIE Project Version : 7.59.1-SNAPSHOT
17:29:16.766 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:179 - *** The karaf version is 4.3.2 ***
17:29:16.766 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:180 - *** The cxf version is 3.3.9 ***
17:29:16.766 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:181 - *** The camel version is 2.24.0 ***
17:29:16.776 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getFeaturesUrl:296 - Features URL: mvn:org.kie/kie-karaf-features/7.59.1-SNAPSHOT/xml/features
WireMock server started and bound to localhost:59600
	######### Available processes[ProcessDefinition{id='evaluation', name='Evaluation', version='1', packageName='Evaluation.src.main.resources', containerId='evaluationproject', associatedEntities=null, serviceTasks=null, processVariables=null, reusableSubProcesses=null, nodes=null, timers=null, tagsByVariable=null, dynamic=false}]
	######### Definition details: ProcessDefinition{id='evaluation', name='Evaluation', version='1', packageName='Evaluation.src.main.resources', containerId='evaluationproject', associatedEntities=null, serviceTasks=null, processVariables=null, reusableSubProcesses=null, nodes=null, timers=null, tagsByVariable=null, dynamic=false}
	######### Process instance id: 2
	######### Tasks: [TaskSummary{id=4, name='Self Evaluation', description='Please perform a self-evalutation.', status='Completed', actualOwner='maciek', createdBy='maciek', createdOn=Mon Aug 03 13:34:17 CEST 2015, processInstanceId=2, processId='evaluation', containerId='evaluationproject', correlationKey=null, processType=null}]
	######### Rules executed
	######### ProcessInstance: ProcessInstance{id=3, processId='evaluation', processName='Evaluation', state=3, containerId='evaluationproject', correlationKey=''}
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.483 s - in org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by mareknovotny** [comment]
yes, that seems as some issue in CI environment. Thanks @grgrzybek !

**Pull request merged**
