### PR TITLE
[JBPM-5624] Added spring boot

### PR DESCRIPTION
**Pull request by rstancel**
Jira: https://issues.jboss.org/browse/JBPM-5624

### CODE REVIEW

**Comment by tsurdilo** [comment]
@rstancel @mswiderski  looks good to me. great job!

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
any comments? plan to merge it end of today so it gets included in 7.6

**Pull request merged**
