### PR TITLE
[reproducer, do not merge] JBPM-5838: reproducer

### PR DESCRIPTION
**Pull request by sutaakar**

### CODE REVIEW

**Comment by sutaakar** [comment]
Run "mvn clean install -Ptomcat8" from kie-server-tests. In router integration tests you will see "INFO] [talledLocalContainer] Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 8089; nested exception is: 
[INFO] [talledLocalContainer] 	java.net.BindException: Address already in use (Bind failed)
".

**Comment by mswiderski** [comment]
@sutaakar is this for local reproduce purpose or shall we merge this in? I guess it's not too safe to not use the generated port right?

**Comment by sutaakar** [comment]
It is just for local reproduction. Don't merge this.

**Comment by mswiderski** [comment]
thanks @sutaakar, run this on top of https://github.com/kiegroup/droolsjbpm-integration/pull/879 and all finished successfully

**Pull request closed without merging**
