### PR TITLE
[RHDM-594] Remove drools-pmml dependency

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by sutaakar** [comment]
The failure seems to be related by duplicate classes. The kie-pmml artifact brings transitive dependency on ch.qos.logback:logback-classic:jar containing same classes as are in org.slf4j:slf4j-jdk14:jar used in kie-server pom.

**Comment by mariofusco** [comment]
ok to test

**Comment by mariofusco** [comment]
ok to test

**Comment by mbiarnes** [comment]
Jenkins please retests this

**Pull request merged**
