### PR TITLE
[7.52.x] [DROOLS-6307] Increase timeout for legacy PMML tests

### PR DESCRIPTION
**Pull request by jiripetrlik**

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by jiripetrlik** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
@jiripetrlik  can you please rebase master?
https://issues.redhat.com/browse/BXMSPROD-1307 fixes the GA error. Thanks.

**Comment by mareknovotny** [comment]
is this still targeting 7.52.x ? or we can mark this as outdated and close it? @jiripetrlik @sutaakar ?

**Comment by sutaakar** [comment]
I think it can be marked as outdated, lets wait for @jiripetrlik

**Comment by mareknovotny** [comment]
the branch 7.52.x is not active, I am closing this PR

**Pull request closed without merging**
