### PR TITLE
JBPM-7542 - updated revapi after changes to the Swagger annotations

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by mswiderski** [comment]
Tests can’t be related to this change. @tsurdilo @MarianMacik could you please double check?

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
@mswiderski this looks good to me. running tests locally to see if it matches to jenkins fails.

**Comment by tsurdilo** [comment]
jenkins fails not related to changes in this pr. will merge

**Pull request merged**
