### PR TITLE
RHBPMS-4819: upgrade of batik

### PR DESCRIPTION
**Pull request by mbiarnes**
DON'T MERGE until https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/601 was merged.
Should be merged together with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/604

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
@mswiderski Seems that we still rely on batik 1.6.1-1 since the batik update breaks designer and there doesn't seem to be an easy workaround for this- Look at RHBPMS-4819. So we can't do the update now.

**Comment by mswiderski** [comment]
@mbiarnes I believe we need to forward port this commit to master https://github.com/kiegroup/jbpm-designer/commit/aa32868e12531bf4135d374efa91bfcdcb38d5b9

**Comment by tsurdilo** [comment]
@mbiarnes yep as @mswiderski said that should just be cherry-picked to master or create a new pr. dont think i should do this as then your branch names won't match up to fully build stuff.

**Comment by psiroky** [comment]
Superseded by https://github.com/kiegroup/droolsjbpm-integration/pull/1294

**Pull request closed without merging**
