### PR TITLE
JBPM-6277: Task Subforms retrieved by Kie Server Rest API is missing subform fields

### PR DESCRIPTION
**Pull request by pefernan**
@mswiderski @jsoltes could you take a look?

### CODE REVIEW

**Comment by pefernan** [comment]
@jsoltes better now?

**Comment by jsoltes** [comment]
jenkins please retest this

**Comment by psiroky** [comment]
Several tests with again fail until https://github.com/kiegroup/droolsjbpm-integration/pull/1069 is merged.

**Comment by jsoltes** [comment]
#1069 is merged, so one more try: jenkins please retest this

**Comment by jsoltes** [comment]
The full downstream build is broken because of this pr: https://github.com/AppFormer/uberfire/pull/779. This is getting fixed in here: https://github.com/kiegroup/guvnor/pull/481

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by pefernan** [comment]
@mswiderski I have created specific JIRA for this PR, so we can close the oriinal 6.5.x JIRA. Let's see when jenkins gets stable :S

**Pull request merged**
