### PR TITLE
IPBRPMS-2143 : Moving kie-tomcat-integration into droolsjbpm-integrat…

### PR DESCRIPTION
**Pull request by mbiarnes**
…ion for build order optimization

(cherry picked from commit 14ddfbdb2d3f7bce4c05ba7535009163b3ec2684)

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mswiderski** [comment]
@mbiarnes shall this be merged into 7.4.x? If not please close it

**Comment by mbiarnes** [comment]
@ryanzhang should this go into 7.4.x - I think so? Let's merge this then.

**Comment by ryanzhang** [comment]
I think it's not relevant anymore since LA is shipped. And this is just a small improvement. Feel free to just close it.

**Comment by mbiarnes** [comment]
OK - I will close this then

**Pull request closed without merging**
