### PR TITLE
RHPAM-1384: Clone a list of server URLs when adjusting router configu…

### PR DESCRIPTION
**Pull request by sutaakar**
…ration

The fix consists of cloning of serverUrls to the new collection. The other adjustments are to simplify code and improve readability.

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
test failures not related to this PR

**Pull request merged**
