### PR TITLE
Enhance kie-performance-kit for 7.x tests

### PR DESCRIPTION
**Pull request by MarianMacik**
Hi,

same as #1157, but for master.

Thanks,

Marian

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
One failing test has age of 13 runs and is failing with other master PRs as well. Is it OK?

**Comment by sutaakar** [comment]
@MarianMacik It is ok for this PR, but the tests needs to be fixed.

**Comment by MarianMacik** [comment]
OK, I think we can merge this and the one for 7.3.x (#1157) as well. @tsurdilo wdyt?

**Pull request merged**
