### PR TITLE
Dynamically allocate WildFly/EAP ports for integration tests

### PR DESCRIPTION
**Pull request by sutaakar**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

paste the link(s) from GitHub here

**How to retest or run**:

* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**

* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**

* a compile downstream build please  add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) cdb.\*]**

* a full production downstream please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) product fdb.\*]**

* an upstream build please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) upstream.\*]**

i.e for running a full downstream build =  **Jenkins do fdb**

### CODE REVIEW

**Comment by sutaakar** [comment]
I have tried to eliminate as much hardcoded ports as possible, though there are still some left.
For Camel the default 8080 port is left as it is hardcoded in camel routes and refactoring would be a significant task.
For some (rarely used) ports in WildFly/EAP there is no support for port configuration using Cargo or system properties. In case we would need to have them dynamically bound the support in Cargo would have to be implemented as a prerequisite.

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
SonarCloud failure is related to low test code coverage. However the added code is related to test execution so the issue is irrelevant.
@mareknovotny Can you please merge?

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
