### PR TITLE
DROOLS-1663 Kie DMN support for IMPORT decisions between DMN files

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @mswiderski really sorry I missed this!

### CODE REVIEW

**Comment by mswiderski** [comment]
hmm looks ok to me though I am most likely not the best one to review ... anyone else we should ask @tarilabs ...

**Comment by tarilabs** [comment]
No need to review @mswiderski , I mentioned in case you needed to build locally. I am going to merge as soon as Jenkins flags green. This just align with a drools (core) PR I just merged.

**Comment by tarilabs** [comment]
This PR aligns with https://github.com/kiegroup/drools/pull/1943

**Comment by mswiderski** [comment]
@tarilabs I tried it locally and here is the error I get

```
[ERROR] /Users/maciejswiderski/Development/git-repos/droolsjbpm-integration/kie-camel/src/test/java/org/kie/camel/KieComponentIntegrationTest.java:[126,44] <anonymous org.kie.camel.KieComponentIntegrationTest$1> is not abstract and does not override abstract method scopeNamespace() in org.kie.dmn.api.core.DMNContext
[ERROR] /Users/maciejswiderski/Development/git-repos/droolsjbpm-integration/kie-camel/src/test/java/org/kie/camel/KieComponentOpOnUriTest.java:[38,44] <anonymous org.kie.camel.KieComponentOpOnUriTest$1> is not abstract and does not override abstract method scopeNamespace() in org.kie.dmn.api.core.DMNContext
```

**Comment by tarilabs** [comment]
painful...

**Comment by tarilabs** [comment]
@mswiderski thanks for pointing out, added new commit to reflect. I hope is the last one :)

**Comment by tarilabs** [comment]
```
13:08:59 [INFO] ------------------------------------------------------------------------
13:08:59 [INFO] Reactor Summary:
13:08:59 [INFO] 
13:08:59 [INFO] Drools and jBPM integration multiproject ........... SUCCESS [  4.544 s]
13:08:59 [INFO] KIE Identity And Session Provider .................. SUCCESS [ 19.342 s]
13:08:59 [INFO] KIE :: Maven Plugin ................................ SUCCESS [ 50.064 s]
13:08:59 [INFO] KIE :: Takari Plugin ............................... SUCCESS [ 10.178 s]
13:08:59 [INFO] Drools Benchmark ................................... SUCCESS [ 21.373 s]
13:08:59 [INFO] Drools RHQ JMX Plugin .............................. SUCCESS [ 18.927 s]
13:08:59 [INFO] Drools and jBPM examples ........................... SUCCESS [ 32.042 s]
13:08:59 [INFO] jBPM Simulation .................................... SUCCESS [01:00 min]
13:08:59 [INFO] Kie :: Spring ...................................... SUCCESS [17:33 min]
13:08:59 [INFO] Kie :: Aries Blueprint ............................. SUCCESS [ 51.047 s]
13:08:59 [INFO] KIE EAP :: Drools and jBPM Module layers for JBoss EAP SUCCESS [  0.728 s]
13:08:59 [INFO] KIE EAP :: Config .................................. SUCCESS [  9.244 s]
13:08:59 [INFO] KIE EAP :: Distribution ............................ SUCCESS [ 38.428 s]
13:08:59 [INFO] KIE EAP :: Installer ............................... SUCCESS [ 13.108 s]
13:08:59 [INFO] KIE EAP :: Integration Tests ....................... SUCCESS [ 49.504 s]
13:08:59 [INFO] KIE :: Infinispan .................................. SUCCESS [  0.292 s]
13:08:59 [INFO] KIE :: Infinispan :: Drools persistence ............ SUCCESS [07:51 min]
13:08:59 [INFO] KIE :: Infinispan :: jBPM persistence .............. SUCCESS [08:29 min]
13:08:59 [INFO] Drools :: JBoss Integration ........................ SUCCESS [ 10.000 s]
13:08:59 [INFO] KIE :: Execution Server ............................ SUCCESS [  0.347 s]
13:08:59 [INFO] KIE :: Execution Server :: API ..................... SUCCESS [ 50.863 s]
13:08:59 [INFO] KIE :: Execution Server :: Common .................. SUCCESS [ 17.440 s]
13:08:59 [INFO] KIE :: Execution Server :: Remote .................. SUCCESS [  0.225 s]
13:08:59 [INFO] KIE :: Execution Server :: Remote :: Client ........ SUCCESS [ 47.044 s]
13:08:59 [INFO] KIE :: Execution Server :: Controller .............. SUCCESS [  0.229 s]
13:08:59 [INFO] KIE :: Execution Server :: Controller :: API ....... SUCCESS [ 14.838 s]
13:09:00 [INFO] KIE :: Execution Server :: Services ................ SUCCESS [  0.283 s]
13:09:00 [INFO] KIE :: Execution Server :: Services :: Common ...... SUCCESS [ 27.399 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: JMS ........... SUCCESS [  6.712 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST .......... SUCCESS [  0.136 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST :: Common  SUCCESS [ 15.248 s]
13:09:00 [INFO] KIE :: Execution Server :: Services :: jBPM Extension SUCCESS [ 27.913 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST :: jBPM .. SUCCESS [ 21.334 s]
13:09:00 [INFO] KIE :: Execution Server :: Services :: Drools Extension SUCCESS [ 11.356 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST :: Drools  SUCCESS [ 11.569 s]
13:09:00 [INFO] jBPM Process SVG Manipulation ...................... SUCCESS [ 21.019 s]
13:09:00 [INFO] KIE :: Execution Server :: Services :: jBPM UI Extension SUCCESS [ 12.213 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST :: jBPM UI SUCCESS [ 12.918 s]
13:09:00 [INFO] KIE :: Execution Server :: Services :: OptaPlanner Extension SUCCESS [  9.874 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST :: OptaPlanner SUCCESS [ 12.057 s]
13:09:00 [INFO] KIE :: Execution Server :: Services :: Case Management Extension SUCCESS [ 12.363 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST :: Case Management SUCCESS [ 12.758 s]
13:09:00 [INFO] KIE :: Execution Server :: Services :: DMN Extension SUCCESS [  8.353 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST :: DMN ... SUCCESS [  9.048 s]
13:09:00 [INFO] KIE :: Execution Server :: Services :: Swagger Extension SUCCESS [  7.662 s]
13:09:00 [INFO] KIE :: Execution Server :: Remote :: REST :: Swagger SUCCESS [  9.453 s]
13:09:00 [INFO] KIE :: Execution Server :: Router .................. SUCCESS [  0.246 s]
13:09:00 [INFO] KIE :: Execution Server :: Router :: Proxy ......... SUCCESS [ 25.031 s]
13:09:00 [INFO] KIE :: Execution Server :: Router :: Client ........ SUCCESS [ 23.857 s]
13:09:00 [INFO] KIE :: Execution Server :: Controller :: Implementation SUCCESS [ 18.648 s]
13:09:00 [INFO] KIE :: Execution Server :: Controller :: REST Implementation SUCCESS [ 11.557 s]
13:09:00 [INFO] KIE :: Execution Server :: Controller :: Standalone Implementation SUCCESS [  6.834 s]
13:09:00 [INFO] KIE :: Execution Server :: Controller :: Websocket Common Implementation SUCCESS [ 11.698 s]
13:09:00 [INFO] KIE :: Execution Server :: Controller :: Websocket Implementation SUCCESS [ 18.250 s]
13:09:00 [INFO] KIE :: Execution Server :: Standalone Controller ... SUCCESS [ 27.161 s]
13:09:00 [INFO] KIE :: Execution Server :: Controller :: Websocket Client Implementation SUCCESS [  5.102 s]
13:09:00 [INFO] KIE :: Execution Server :: Controller :: Client .... SUCCESS [ 12.040 s]
13:09:00 [INFO] kie-security ....................................... SUCCESS [  7.814 s]
13:09:00 [INFO] KIE :: Execution Server :: Wars .................... SUCCESS [  0.761 s]
13:09:00 [INFO] KIE :: Execution Server :: Wars :: Distribution Wars SUCCESS [01:46 min]
13:09:00 [INFO] KIE :: Execution Server :: Wars :: Distribution .... SUCCESS [  7.858 s]
13:09:00 [INFO] KIE :: Execution Server :: Tests ................... SUCCESS [  2.297 s]
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Common Integration Tests SUCCESS [03:56 min]
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Drools Integration Tests SUCCESS [08:21 min]
13:09:00 [INFO] KIE :: Execution Server :: Tests :: jBPM Integration Tests FAILURE [02:22 min]
13:09:00 [INFO] KIE :: Execution Server :: Tests :: OptaPlanner Integration Tests SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Drools and jBPM Integration Tests SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Controller Integration Tests SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Policies Integration Tests SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Router Integration Tests SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Case Id Generator Integration Tests SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: DMN Integration Tests SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Custom extension SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Custom extension :: Service SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Custom extension :: REST SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Custom extension :: Client SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Tests :: Custom extension :: Integration Tests SKIPPED
13:09:00 [INFO] KIE :: Execution Server :: Deploy Maven Plugin ..... SUCCESS [  8.642 s]
13:09:00 [INFO] KIE :: Execution Server :: Controller :: Deploy Maven Plugin SUCCESS [ 14.091 s]
13:09:00 [INFO] KIE :: OSGi Integration Parent Project ............. SUCCESS [  0.318 s]
13:09:00 [INFO] kie-karaf-itests-domain-model ...................... SUCCESS [ 11.855 s]
13:09:00 [INFO] KIE :: Karaf Integration Tests Kjar ................ SUCCESS [  7.410 s]
13:09:00 [INFO] KIE :: OSGi Integration ............................ SUCCESS [ 10.331 s]
13:09:00 [INFO] KIE :: Karaf Features .............................. SUCCESS [ 14.250 s]
13:09:00 [INFO] KIE :: Karaf Integration Tests ..................... SUCCESS [09:02 min]
13:09:00 [INFO] KIE Performance Kit ................................ SUCCESS [ 19.978 s]
13:09:00 [INFO] Drools :: Android Integration ...................... SUCCESS [ 20.379 s]
13:09:00 [INFO] Kie :: Camel ....................................... SUCCESS [01:36 min]
13:09:00 [INFO] KIE Tomcat integration ............................. SUCCESS [ 11.974 s]
13:09:00 [INFO] KIE Integration :: Test Coverage ................... SUCCESS [  0.229 s]
13:09:00 [INFO] KIE Integration :: KIE Maven Plugin Additional Test Coverage SUCCESS [  0.189 s]
13:09:00 [INFO] KIE Integration :: KIE Maven Plugin Instrumented kJAR Wrapper SUCCESS [ 17.830 s]
13:09:00 [INFO] KIE Integration :: KIE Maven Plugin Additional Tests SUCCESS [  6.799 s]
13:09:00 [INFO] KIE Integration :: KIE Maven Plugin Additional Test Coverage SUCCESS [  0.434 s]
13:09:00 [INFO] KIE Integration :: KIE Maven Plugin Instrumented Model JAR Wrapper SUCCESS [  8.370 s]
13:09:00 [INFO] KIE Integration :: KIE Maven Plugin Instrumented kJAR Wrapper SUCCESS [ 10.527 s]
13:09:00 [INFO] KIE Integration :: KIE Maven Plugin Additional Tests SUCCESS [  6.046 s]
13:09:00 [INFO] KIE Integration :: KIE Spring Integration Test ..... SUCCESS [ 14.822 s]
13:09:00 [INFO] KIE :: Plugins Testing ............................. SUCCESS [04:43 min]
13:09:00 [INFO] KIE :: Spring :: Boot .............................. SUCCESS [  0.270 s]
13:09:00 [INFO] KIE :: Spring :: Boot :: Auto Configuration ........ SUCCESS [  0.238 s]
13:09:00 [INFO] KIE :: Spring :: Boot :: jBPM Auto Configuration ... SUCCESS [ 17.836 s]
13:09:00 [INFO] KIE :: Spring :: Boot :: Starters .................. SUCCESS [  0.269 s]
13:09:00 [INFO] jBPM :: Spring :: Boot :: Starter :: basic ......... SUCCESS [ 17.010 s]
13:09:00 [INFO] KIE :: Spring :: Boot :: KIE Server Auto Configuration SUCCESS [ 16.508 s]
13:09:00 [INFO] KIE :: Spring :: Boot :: KIE Server Auto Configuration :: Drools SUCCESS [ 12.087 s]
13:09:00 [INFO] KIE :: Spring :: Boot :: KIE Server Auto Configuration :: jBPM SUCCESS [ 49.601 s]
13:09:00 [INFO] KIE :: Spring :: Boot :: KIE Server Auto Configuration :: OptaPlanner SUCCESS [  8.270 s]
13:09:00 [INFO] KIE Server :: Spring :: Boot :: Starter ............ SUCCESS [ 38.034 s]
13:09:00 [INFO] KIE Server :: Spring :: Boot :: Starter :: Drools and DMN SUCCESS [  1.495 s]
13:09:00 [INFO] KIE Server :: Spring :: Boot :: Starter :: jBPM and Case management SUCCESS [  0.827 s]
13:09:00 [INFO] KIE Server :: Spring :: Boot :: Starter :: OptaPlanner SUCCESS [  1.212 s]
13:09:00 [INFO] KIE :: Spring :: Boot :: Samples ................... SUCCESS [  2.765 s]
13:09:00 [INFO] jBPM :: Spring :: Boot :: Sample :: basic .......... SUCCESS [03:11 min]
13:09:00 [INFO] KIE Server :: Spring :: Boot :: Sample ............. SUCCESS [03:03 min]
13:09:00 [INFO] KIE Server :: Spring :: Boot :: Keycloak Sample .... SUCCESS [ 56.743 s]
13:09:00 [INFO] Drools and jBPM integration distribution ........... SUCCESS [ 14.407 s]
13:09:00 [INFO] BPMS distribution .................................. SUCCESS [ 27.086 s]
13:09:00 [INFO] BRMS distribution .................................. SUCCESS [ 12.071 s]
13:09:00 [INFO] ------------------------------------------------------------------------
13:09:00 [INFO] BUILD FAILURE
13:09:00 [INFO] ------------------------------------------------------------------------
13:09:00 [INFO] Total time: 29:04 min (Wall Clock)
13:09:00 [INFO] Finished at: 2018-06-14T07:08:59-04:00
13:09:01 [INFO] Final Memory: 752M/1964M
13:09:01 [INFO] ------------------------------------------------------------------------
13:09:01 [ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.6.6:start (start-container) on project kie-server-integ-tests-jbpm: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly11xInstalledLocalContainer@438b6ae4]: Deployable [http://localhost:33998/kie-server-services/services/rest/server] failed to finish deploying within the timeout period [60000]. The Deployable state is thus unknown. -> [Help 1]
13:09:01 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.6.6:start (start-container) on project kie-server-integ-tests-jbpm: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly11xInstalledLocalContainer@438b6ae4]
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
13:09:01     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:09:01     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
13:09:01     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
13:09:01     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:09:01     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
13:09:01     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:09:01     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
13:09:01     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
13:09:01     at java.lang.Thread.run (Thread.java:748)
13:09:01 Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly11xInstalledLocalContainer@438b6ae4]
13:09:01     at org.codehaus.cargo.maven2.ContainerStartMojo.doExecute (ContainerStartMojo.java:74)
13:09:01     at org.codehaus.cargo.maven2.AbstractCargoMojo.execute (AbstractCargoMojo.java:471)
13:09:01     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
13:09:01     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:09:01     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
13:09:01     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
13:09:01     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:09:01     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
13:09:01     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:09:01     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
13:09:01     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
13:09:01     at java.lang.Thread.run (Thread.java:748)
13:09:01 Caused by: org.codehaus.cargo.container.ContainerException: Deployable [http://localhost:33998/kie-server-services/services/rest/server] failed to finish deploying within the timeout period [60000]. The Deployable state is thus unknown.
13:09:01     at org.codehaus.cargo.container.spi.deployer.DeployerWatchdog.watch (DeployerWatchdog.java:111)
13:09:01     at org.codehaus.cargo.maven2.AbstractCargoMojo.waitDeployableMonitor (AbstractCargoMojo.java:1099)
13:09:01     at org.codehaus.cargo.maven2.ContainerStartMojo.doExecute (ContainerStartMojo.java:59)
13:09:01     at org.codehaus.cargo.maven2.AbstractCargoMojo.execute (AbstractCargoMojo.java:471)
13:09:01     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
13:09:01     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
13:09:01     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:09:01     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
13:09:01     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
13:09:01     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:09:01     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
13:09:01     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:09:01     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
13:09:01     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
13:09:01     at java.lang.Thread.run (Thread.java:748)
```

**Comment by tarilabs** [comment]
I'm going to ask for this to be merged not to block other builds, anyway.

**Comment by mswiderski** [comment]
agreed

**Pull request merged**
