### PR TITLE
RHPAM-3897: switch to jboss-transaction-spi-jakarta

### PR DESCRIPTION
**Pull request by almope**
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>

**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)

**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1768
* https://github.com/kiegroup/jbpm/pull/2016
* https://github.com/kiegroup/drools/pull/3832
* https://github.com/kiegroup/jbpm-work-items/pull/215
* https://github.com/kiegroup/kie-jpmml-integration/pull/64
* https://github.com/kiegroup/optaplanner/pull/1574
* https://github.com/kiegroup/kie-soup/pull/227
* https://github.com/jboss-integration/rhba-installers/pull/92

### CODE REVIEW

**Comment by almope** [comment]
**Important**: Needs to be checked with the profile `tomcat9`

**Review by elguardian — APPROVED** [review]
LGTM

**Comment by almope** [comment]
jenkins retest this

**Review by gmunozfe — APPROVED** [review]
Looks good to me, way to go @almope !

**Pull request merged**
