### PR TITLE
[7.48.x]JBPM-9273 System error occurred while adding deployment unit

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[JBPM-9273](https://issues.redhat.com/browse/JBPM-9273)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/kie-wb-common/pull/3548

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by prashuts** [comment]
Jenkins run fdb

**Review by prashuts — APPROVED** [review]
LGTM

**Review by nmirasch — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
looks like an environment issue as I cannot reproduce this on my local.
<reuseForks>false</reuseForks>
in the  surefire plugin ? Want to know if it is really environment

**Comment by bxf12315** [comment]
@nmirasch @sutaakar @prashuts @lazarotti Can we merge it?

**Comment by nmirasch** [comment]
@bxf12315  I don't understand where this failing test comes at CI build, but if @elguardian says it depends on the environment..I think is ok to merge (more when this is just a cherry-pick )

**Comment by bxf12315** [comment]
> @bxf12315 I don't understand where this failing test comes at CI build, but if @elguardian says it depends on the environment..I think is ok to merge (more when this is just a cherry-pick )

ok Thanks, please merge them.

**Comment by lazarotti** [comment]
if it is not related, so ok to merge.

**Comment by elguardian** [comment]
Hi this is a problem in optaplanner it seems @bxf12315 

[2021-02-18T16:09:41.125Z] 2021-02-18 11:06:24,127 [pool-28-thread-2] WARN  An error was produced during solution recovering. Next attempt will be in a period of PT1S, error: No available endpoints found

Can you set the property 
kieserver.optaplanner.enabled=false
in this file 
https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/resources/application-test.properties

and re-run this ?

**Comment by sutaakar** [comment]
Please don't introduce unrelated changes as part of this PR.
The issue should be addressed separately.

**Comment by prashuts** [comment]
Verified the changes w.r.t this ticket . @sutaakar i agree . It would be better to have the issue in new ticket.

**Comment by bxf12315** [comment]
> Hi this is a problem in optaplanner it seems @bxf12315
> 
> [2021-02-18T16:09:41.125Z] 2021-02-18 11:06:24,127 [pool-28-thread-2] WARN An error was produced during solution recovering. Next attempt will be in a period of PT1S, error: No available endpoints found
> 
> Can you set the property
> kieserver.optaplanner.enabled=false
> in this file
> [https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/resources/application-test.properties](https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/resources/application-test.properties?rgh-link-date=2021-02-23T07%3A52%3A56Z)
> 
> and re-run this ?

you means, change our CI build env?

**Comment by bxf12315** [comment]
@nmirasch @sutaakar @prashuts Can we merge the PR and [1]  firstly? 
[1] https://github.com/kiegroup/droolsjbpm-integration/pull/2386

**Comment by prashuts** [comment]
LGTM-  #2381

**Comment by sutaakar** [comment]
fine for me

**Comment by elguardian** [comment]
@sutaakar  @nmirasch this is incorrecly merged without looking too much into the issue. 
This should not happen again.

**Comment by mareknovotny** [comment]
Is it required to merge also https://github.com/kiegroup/kie-wb-common/pull/3548 ? I am not sure as the description doesn't state it

**Pull request merged**
