### PR TITLE
[JBPM-9415] ClassNotFoundException in kie-server-integ-tests-all test…

### PR DESCRIPTION
**Pull request by sutaakar**
…s running on SpringBoot

Signed-off-by: Karel Suta <ksuta@redhat.com>

**Thank you for submitting this pull request**

**JIRA**: 

[JBPM-9415](https://issues.redhat.com/browse/JBPM-9415)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by sutaakar** [comment]
jenkins execute springboot build

**Comment by sutaakar** [comment]
The GitHub action build seems to fail due to connectivity issue:
```
2020-10-07T11:09:43.2793327Z [ERROR] Failed to execute goal on project process-migration-service: Could not resolve dependencies for project org.drools:process-migration-service:war:7.45.0-SNAPSHOT: Could not transfer artifact io.thorntail:jaxrs:jar:2.7.0.Final from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/io/thorntail/jaxrs/2.7.0.Final/jaxrs-2.7.0.Final.jar: Connection reset -> [Help 1]
2020-10-07T11:09:43.2837751Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project process-migration-service: Could not resolve dependencies for project org.drools:process-migration-service:war:7.45.0-SNAPSHOT: Could not transfer artifact io.thorntail:jaxrs:jar:2.7.0.Final from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/io/thorntail/jaxrs/2.7.0.Final/jaxrs-2.7.0.Final.jar
```

**Review by gmunozfe — APPROVED** [review]
Looks good to me

**Comment by sutaakar** [comment]
@MarianMacik Can you please take a look/merge?

**Review by MarianMacik — APPROVED** [review]
Looks good to me.

**Pull request merged**
