### PR TITLE
BXMSPROD-753 test

### PR DESCRIPTION
**Pull request by Ginxo**

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins retest this please

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
Jenkins run compile downstream build

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
Jenkins run compile downstream build

**Comment by Ginxo** [comment]
Jenkins do full downstream production build

**Comment by Ginxo** [comment]
test full downstream production build

**Comment by Ginxo** [comment]
test full downstream build

**Comment by Ginxo** [comment]
test compile downstream build

**Comment by Ginxo** [comment]
test retest this please

**Comment by Ginxo** [comment]
test new full downstream build

**Comment by mbiarnes** [comment]
Jenkins start upstream build

**Comment by Ginxo** [comment]
test full downstream production build

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
@Ginxo can you please rebase this branch?

**Comment by mbiarnes** [comment]
will close this one and re-open a new one since this has to be rebased

**Pull request closed without merging**
