### PR TITLE
AF-2811: Required Process Variable Tags shouldn't be accepted in forms when empty

### PR DESCRIPTION
**Pull request by akumar074**
* Added "required" and "readonly" property to FormField by tags
 * Fixed validation for input box in ProcessInstance form

**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)

**referenced Pull Requests**: 
https://github.com/kiegroup/kie-wb-common/pull/3609
https://github.com/kiegroup/jbpm-wb/pull/1486

Original PR : https://github.com/kiegroup/droolsjbpm-integration/pull/2398

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by tomasdavidorg** [comment]
Hi @akumar074 ,
I created 2 process variables - 1 required and 1 readonly and I tried these two scenarios:

1. ✅  I deployed process without generating forms. This was ok. The form contained two inputs. First one had to be non-empty. The second couldn't be modified.
2. ⛔ I generated forms in the process. The forms was not generated correctly. The first input was not required and the second was not readonly. When I started the process I got an error message. After I filled the input the error is still visible.

Error message:
`Unable to complete your request. The following exception occurred: "Unable to create response: Variable 'abc' in process instance '8' violated".`

image

**Comment by tomasdavidorg** [comment]
I think this worked when I tried the master branch PR last time. I will also check it tomorrow on the master branch.

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
@tomasdavidorg The behaviour you mentioned is indeed a bug. In Jira, the issue is faced with autogenerated forms. so this PR aims to resolve the same. Can we create a separate Jira for the issue mentioned above. WDYT?

**Comment by tomasdavidorg** [comment]
Hi @akumar074, I can agree with that.

**Comment by tomasdavidorg** [comment]
@akumar074 Thanks for reporting the issue https://issues.redhat.com/browse/RHPAM-3595. Approving.

**Review by tomasdavidorg — APPROVED** [review]

**Review by pefernan — APPROVED** [review]
+1

**Pull request merged**
