### PR TITLE
Set transaction manager factory for spring boot auto configuration

### PR DESCRIPTION
**Pull request by mswiderski**
@MarianMacik please have a try with this change

### CODE REVIEW

**Comment by mswiderski** [comment]
depends on https://github.com/kiegroup/jbpm/pull/1316

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
The failing test org.kie.server.integrationtests.optaplanner.OptaplannerIntegrationTest.org.kie.server.integrationtests.optaplanner.OptaplannerIntegrationTest 
is not related to the changes made in this pr

**Pull request merged**
