### PR TITLE
[JBPM-10159] Escaping variable name in path

### PR DESCRIPTION
**Pull request by fjtirado**
**JIRA**: 

https://issues.redhat.com/browse/JBPM-10159

### CODE REVIEW

**Review by gmunozfe — APPROVED** [review]
Looks good to me, astounding work @fjtirado !

**Comment by fjtirado** [comment]
jenkins retest this

**Review by bxf12315 — APPROVED** [review]
look good to me. Thanks

**Comment by mareknovotny** [comment]
jenkins retest this please

**Pull request merged**
