### PR TITLE
[7.67.x-blue][JBPM-10110] - Need to exclude some bypass integration integration test for specific servers

### PR DESCRIPTION
**Pull request by afalhambra**
Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2821/commits/865d0159701324349538c8866bb6168fdd87e019

### CODE REVIEW

**Review by gmunozfe — APPROVED** [review]
Looks good to me, well done @afalhambra !

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
Not related failures, trying again
Jenkins retest this

**Pull request merged**
