### PR TITLE
[RHPAM-2813] Add springboot property to bypass auth user

### PR DESCRIPTION
**Pull request by gmunozfe**
Added property `org.kie.server.bypass.auth.user=true` inside **start-springboot** just for _kie-server-integ-test-jbpm._

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins execute springboot build

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
@kiegroup/gatekeepers could you merge?

**Pull request merged**
