### PR TITLE
[7.59.x] AF-2880 : Support Elytron in Business Central 

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 

[AF-2880](https://issues.redhat.com/browse/AF-2880)

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1776
* https://github.com/kiegroup/kie-soup/pull/231
* https://github.com/kiegroup/appformer/pull/1199
* https://github.com/kiegroup/droolsjbpm-integration/pull/2611
* https://github.com/kiegroup/jbpm-wb/pull/1518
* https://github.com/kiegroup/kie-wb-distributions/pull/1132
* 
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
if you can please rebase to see Github actions result too, fyi there were newer maven version in github build node which with rebase could be fixed.

**Comment by Rikkola** [comment]
Even after this run there will be failures, since actual bugs are being picked up, but fixing them ATM.

**Comment by Rikkola** [comment]
```
org.kie.server.integrationtests.jbpm.WebServiceHeadersDumbEscapeIntegrationTest.testCallWebServiceHeadersDumbEscape[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35458/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.WebServiceHeadersNoEscapeIntegrationTest.testCallWebServiceHeadersNoEscape[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35458/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.WebServiceHeadersNoEscapeNoMatchIntegrationTest.testCallWebServiceHeadersNoEscapeNoMatch[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35458/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.WebServiceIntegrationTest.testCallWebServiceFromProcess[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35458/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.WebServiceWrappedParamsIntegrationTest.testCallWebServiceWrappedParams[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35458/kie-server-services/services/rest/server'}]
```
jenkins retest this please

**Comment by mareknovotny** [comment]
@sutaakar @gmunozfe @afalhambra can you guys check the failed 5 tests if that is related to changes here?

**Comment by Rikkola** [comment]
I will try to run those tests locally. Second time they fail.

**Comment by mareknovotny** [comment]
merging as decided on mtg, all failures identified in Karaf IT needs to be fixed or ignored in followup investigation and work for main branch PRs

**Pull request merged**
