### PR TITLE
AF-2881 : When try to attach a document the upload button is not showing

### PR DESCRIPTION
**Pull request by akumar074**
* Added input type file check

**JIRA**:

[AF-2881](https://issues.redhat.com/browse/AF-2881)
[RHPAM-3515](https://issues.redhat.com/browse/RHPAM-3515)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by prashuts** [comment]
@akumar074 Reviewed , was able to upload successfully and encountered issue while downloading the document (https://issues.redhat.com/browse/JBPM-9852).

**Review by Rikkola — APPROVED** [review]

**Review by prashuts — APPROVED** [review]

**Pull request merged**
