### PR TITLE
[RHPAM-3405] fix kie-camel feature for fuse 7.6 on karaf

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mareknovotny** [comment]
it seems we need this https://github.com/kiegroup/droolsjbpm-integration/pull/2148 first

**Comment by mariofusco** [comment]
@mareknovotny can we also merge this fix on master? All the reported failures are clearly unrelated.

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
just for sure, but I will merge it after that green or not

**Comment by Rikkola** [comment]
@mariofusco Are you sure the ticket number was RHPAM-3405? Just checking since I just made that ticket and these PRs show up for it :)
Just in case you need to update anything due to this.

**Comment by mareknovotny** [comment]
@Rikkola it was probably typo, this change is related to https://issues.redhat.com/browse/RHPAM-3045

**Comment by Rikkola** [comment]
Ok thought so and I see the ticket has the PR linked so all good.

**Pull request merged**
