### PR TITLE
JBPM-5757 - Replace status List<Integer> with List<Status> in CaseRun…

### PR DESCRIPTION
**Pull request by tsurdilo**
…timeDataService operations

### CODE REVIEW

**Comment by tsurdilo** [comment]
depends on https://github.com/kiegroup/jbpm/pull/781

**Comment by mswiderski** [comment]
@tsurdilo as we discussed it would be better to use string versions in the client side too - so open, closed etc instead of 1 or 2 when searching for cases.

**Comment by tsurdilo** [comment]
@mswiderski updated. thanks.

**Comment by mswiderski** [comment]
test failures seems to be related to the change, can you take a look once you have a minute?

**Comment by tsurdilo** [comment]
@mswiderski tests will fail until https://github.com/kiegroup/jbpm/pull/781 is merged

**Comment by tsurdilo** [comment]
@mswiderski tests pass ok now. jenkins fails seem due to something else now

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by mswiderski** [comment]
looks good, just one question - there are lots of formatting changes - is this the new formatter that should be used:
```
-        createContainer(CONTAINER_ID, releaseId);
 +        createContainer(CONTAINER_ID,
 +                        releaseId);
```

**Comment by tsurdilo** [comment]
@mswiderski yes i use it on all projects now

**Pull request merged**
