### PR TITLE
[AF-1224] Execution UI should point to swagger, instead of endpoint

### PR DESCRIPTION
**Pull request by elguardian**
added capabilities information to server instance key so it can
be retrieved by the use and act acordingly

### CODE REVIEW

**Comment by mswiderski** [comment]
@elguardian why do you need this on server instance? capabilities are already available on server template and should be used from there

**Comment by elguardian** [comment]
@mswiderski aren't they filtered regarding a specfic set ?
https://github.com/elguardian/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java#L173

The data sent back to the client 
https://github.com/elguardian/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java#L227

is not the template thought; so I thought those two arguments were strong enough to add the capabilities in there.

**Comment by mswiderski** [comment]
@elguardian they are at the moment but this seems like a good reason to extend it and add swagger/docs capability there too. That does not have to mean it needs to be presented on UI but since you already require this information to show the link or not it might be worth to use that instead of duplicating it on each server instance

**Comment by elguardian** [comment]
ok to test

**Comment by elguardian** [comment]
@mswiderski do you mind to check whethere the pr is correct or not ? 
https://github.com/kiegroup/kie-wb-common/pull/1900

**Comment by mswiderski** [comment]
@elguardian looks ok though I'd question if the url change is actually a good idea. Main reason is that swagger docs are built as extension that can be easily disabled and by that break the link completely - while the server endpoint always exists. 

so what's the reason for this URL change?

**Comment by elguardian** [comment]
@mswiderski the link to the docs is only shown if the swagger functionality is active and sent by the server. That is the main reason to put this part of the code here, so the UI can decide whether to show the link to the docs or not. 

https://github.com/kiegroup/kie-wb-common/pull/1900/files#diff-1946eafb6f0f208021cf921b473abff7R162

It makes sense to me in the sense that the user is in a UI so you are jumping from UI -> to swagger (which is easier to manipulate from the UI point of view rather getting machine output only useful for rest clients more likely) IMHO.

**Comment by elguardian** [comment]
I guess @porcelli   has something to say as he is the reporter of https://issues.jboss.org/browse/RHPAM-1146

**Comment by mswiderski** [comment]
@elguardian @porcelli frankly speaking I am not convinced this change (of the URL) makes sense - it will cause inconsistence and make people confused as it will behave differently based on the extensions enabled. So I'd opt to stick to what we have at the moment. 
What's the reason to change this URL?

**Comment by porcelli** [comment]
@mswiderski this request came up during enablement as a UX improvement. as, if enabled, the link of Swagger docs makes more sense then just the REST endpoint itself.

With that said, maybe ask for UX support to address @mswiderski concern on how display:
 - just the endpoint URI
 - both endpoint URI and Swagger

**Comment by mswiderski** [comment]
@porcelli thanks and I agree we should first check with UX team to make sure this is not opposite of improvement

**Comment by porcelli** [comment]
@wrnkld could you help us here?

**Comment by wrnkld** [comment]
Added some comments on RHPAM-1146.

**Pull request closed without merging**
