### PR TITLE
[JBPM-9044] Upgrade Wildfly to 18.0.1.Final

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/JBPM-9044

Parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1203

### CODE REVIEW

**Comment by MarianMacik** [comment]
We will also need to update jbpm-container tests in jbpm. There is Cargo with EAP as well.

**Comment by mareknovotny** [comment]
@MarianMacik this is iterative change, so I would welcome if you can prepare change too as @sutaakar, if not  for me it is a longer as I don't work only on this ;)

**Comment by MarianMacik** [comment]
@mareknovotny I have updated WildFly also in `kie-sever-controller` and removed references to WildFly version in readme files.

**Comment by MarianMacik** [comment]
There are some fails with dashbuilder:

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project uberfire-security-management-wildfly: Compilation failure: Compilation failure: 
15:57:59 [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-integration-pullrequests/upstream-repos/appformer/uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/WildflyGroupPropertiesManager.java:[422,13] no suitable constructor found for PropertiesFileLoader(java.lang.String,java.lang.String)
15:57:59 [ERROR]     constructor org.jboss.as.domain.management.security.PropertiesFileLoader.PropertiesFileLoader(java.util.function.Supplier<org.jboss.as.controller.services.path.PathManager>,java.lang.String,java.lang.String) is not applicable
15:57:59 [ERROR]       (actual and formal argument lists differ in length)
15:57:59 [ERROR]     constructor org.jboss.as.domain.management.security.PropertiesFileLoader.PropertiesFileLoader(java.lang.String) is not applicable
15:57:59 [ERROR]       (actual and formal argument lists differ in length)
15:57:59 [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-integration-pullrequests/upstream-repos/appformer/uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/WildflyUserPropertiesManager.java:[349,13] no suitable constructor found for UserPropertiesFileLoader(java.lang.String,java.lang.String)
15:57:59 [ERROR]     constructor org.jboss.as.domain.management.security.UserPropertiesFileLoader.UserPropertiesFileLoader(java.util.function.Supplier<org.jboss.as.controller.services.path.PathManager>,java.lang.String,java.lang.String) is not applicable
15:57:59 [ERROR]       (actual and formal argument lists differ in length)
15:57:59 [ERROR]     constructor org.jboss.as.domain.management.security.UserPropertiesFileLoader.UserPropertiesFileLoader(java.lang.String) is not applicable
15:57:59 [ERROR]       (actual and formal argument lists differ in length)
```
I tried to fix it with the https://github.com/kiegroup/appformer/pull/911

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
@jomarko I know and am trying to eliminate these duplicated classes. The problem here is that kie-server-tests module uses wildfly-jms-client-bom which is bringing not necessary dependencies and they are actually not shown in `dependency:tree` so this is just searching in transitive dep chain

**Comment by jomarko** [comment]
@mareknovotny no problem, take your time, I put that comment just as remark of the state.

**Comment by mareknovotny** [comment]
Jenkins retest this please


```
java.util.concurrent.TimeoutException: Synchronization failed for defined timeout: 240000 milliseconds.
	at org.kie.server.integrationtests.controller.WebSocketKieControllerStartupIntegrationTest.testContainerDisposedAfterStartup(WebSocketKieControllerStartupIntegrationTest.java:248)
```

**Comment by mareknovotny** [comment]
finally green after enforcer fighting

**Pull request merged**
