### PR TITLE
[JBPM-9308] EventEmitter is not working in spring boot

### PR DESCRIPTION
**Pull request by afalhambra**
[**JIRA**](https://issues.redhat.com/browse/JBPM-9308): Adding EventEmitterTest test case

### CODE REVIEW

**Comment by elguardian** [comment]
seems like 
org.jbpm.springboot.samples.BusinessProcessTest.testProcessStartAndWorkOnUserTasks comes from this

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
Jenkins retest this

**Review by elguardian — APPROVED** [review]
LGTM

**Pull request merged**
