### PR TITLE
DROOLS-5663 align kie-maven-plugin default for generateModel config flag

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**: https://issues.redhat.com/browse/DROOLS-5663

**referenced Pull Requests**: none

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]

**Review by mariofusco — APPROVED** [review]

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
```
Test Result (1 failure / +1)
org.kie.integration.testcoverage.instrumentation.InstrumentationTest.testMetaInfoExists
```

Jenkins retest this

**Comment by tarilabs** [comment]
(writing update comment about what changed...)

**Comment by tarilabs** [comment]
To recap

# Code change required

only commit 7cf80ee

# To avoid forgetting

commit a824dee have the same code-comment in both places, so hopefully if using git-blame we can easily re-discover these two annotations HAVE to be aligned

# updating test suite

commits 83ea960 26f9ba3 3ee084f
move the existing test suite into a more explicit one (mentioning NO exec model, since the suite was originally created when the exec model was NOT the default)

# align test
accordingly bcc8ac8 update the behaviour of the test for  DROOLS-4263 (#1856) since what we STILL want under test is that IFF there is no exec model (which must be explicitly set in config flag now) the content of the KJAR do have the 2 metadata files

# cosmetics in Maven reactor
commit 8e42051 just artifact name to be displayed when running the Maven reactor

# new test suite for default==exec model
this will need a separate PR to avoid git history messing up
hence commit 8e2e103 is reverted with fbdaa85
I will open a new PR separately

Hope this clarifies, surprisingly the code change was trivial, but aligning the test suite is not :D

**Review by tkobayas — APPROVED** [review]
Great clarification. Thanks!!

**Comment by lucamolteni** [comment]
Thanks Matteo

**Comment by tarilabs** [comment]
```
Test Result (1 failure / +1)
org.kie.server.integrationtests.controller.KieControllerStartupIntegrationTest.testContainerDisposedAfterStartup[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35342/kie-server-services/services/rest/server'}]
```

( a test timeout )

Jenkins retest this

**Comment by tarilabs** [comment]
```
Test Result (1 failure / +1)
org.kie.server.integrationtests.controller.KieControllerStartupIntegrationTest.testContainerDisposedAfterStartup[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35342/kie-server-services/services/rest/server'}]
```

( a test timeout, again )

🤷‍♂️ 🎱 

Jenkins retest this

**Comment by tarilabs** [comment]
```
Test Result (1 failure / ±0)
org.kie.server.integrationtests.controller.KieControllerStartupIntegrationTest.testContainerDisposedAfterStartup[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:44326/kie-server-services/services/rest/server'}]
```

(same test timeout again and again)

🤷‍♂️ 🎱 🎱 

Jenkins retest this

**Comment by tarilabs** [comment]
Finally...
image

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
