### PR TITLE
JBPM-8976: Fix kie-server expected capabilities comparison

### PR DESCRIPTION
**Pull request by jomarko**
For more details see https://issues.redhat.com/browse/JBPM-8976

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by elguardian** [comment]
failure is not related. Just keep in mind sonar.

**Comment by elguardian** [comment]
1 vulnerability has no impact here.
1 code smells is more about preferences of sonar than a real one.

**Comment by jomarko** [comment]
@elguardian do you agree with merge?

**Comment by wmedvede** [comment]
Hi @jomarko @elguardian 
I'd tested the fix locally and seems to work well. From my side I'd suggest to merge this ASAP since I believe there might be use cases where the KieController stays stucked in a loop trying to connect to the server, since the check always gives an error.
my 2 cents.

**Comment by elguardian** [comment]
@jomarko  yep
@kiegroup/gatekeepers

**Pull request merged**
