### PR TITLE
JBPM-10109: Add support for container alias in user task claim operation

### PR DESCRIPTION
**Pull request by martinweiler**
**JIRA**: https://issues.redhat.com/browse/JBPM-10109

### CODE REVIEW

**Comment by martinweiler** [comment]
@elguardian @fjtirado could you please take a look? I have tested the change in RHPAM and it works as expected, a user is able to claim a task when using the container alias (similar to other task operations in the same class). 

However, the integration test is not working as expected, as it is passing even without applying the change to UserTaskServiceBase, as the claim method is called with the CONTAINER_ID ("definition-project") and not the CONTAINER_ID_ALIAS ("definition-project-alias"). I could not figure out why, so I'd appreciate any hints. Thanks!

**Review by fjtirado — COMMENTED** [review]
@martinweiler This is better than my proposal in the JIRA, so congrats!!!
I think that for completeness we might want to add the same call here
https://github.com/kiegroup/droolsjbpm-integration/blob/main/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/UserTaskServiceBase.java#L98
so batch call also works

**Comment by martinweiler** [comment]
@fjtirado thanks for your input. I added the container check to the bulk claim operation as well.

I also managed to verify the fix in the test class, it just seems to be a bit finicky to get the updates into the deployed web app used during the test.

**Review by fjtirado — APPROVED** [review]

**Comment by fjtirado** [comment]
jenkins retest this

**Pull request merged**
