### PR TITLE
JBPM-9431: Unable to add deployment unit while creating very first container

### PR DESCRIPTION
**Pull request by akumar074**
* Added missing ReleaseId field

**JIRA**: [JBPM-9431](https://issues.redhat.com/browse/JBPM-9431)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins do fdb

**Comment by akumar074** [comment]
Jenkins do fdb

**Comment by prashuts** [comment]
Jenkins run fdb

**Review by prashuts — APPROVED** [review]
Looks fine for me.

**Comment by akumar074** [comment]
@paulovmr I have added you for this PR review. Feel free to change the reviewer.
Thanks!

**Comment by akumar074** [comment]
> Looks fine for me.

Thanks @prashuts

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
