### PR TITLE
JBPM-8744 - Code coverage metrics for PIM service

### PR DESCRIPTION
**Pull request by MarianMacik**

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
The coverage is not displayed in the PR analysis because it counts only new code, which in this PR is just a `pom.xml`. But locally, when I call a report goal of jacoco, the data from integration tests is included.

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins retest this

**Pull request merged**
