### PR TITLE
[RHPAM-2060] - Infinite Configuration file does not exist messages in…

### PR DESCRIPTION
**Pull request by msmagnanijr**
… Smart Router logs

See: https://issues.redhat.com/browse/RHPAM-2060

Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by spolti — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by sutaakar** [comment]
Test failure not related.

**Comment by elguardian** [comment]
@msmagnanijr keep in mind that you should use community jira for integration and runtime engine

**Comment by msmagnanijr** [comment]
> @msmagnanijr keep in mind that you should use community jira for integration and runtime engine
Sure! thanks for the help.

**Comment by mareknovotny** [comment]
guys, in case backporting merge first PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1573 targeting master branch !!

**Pull request merged**
