### PR TITLE
2 EAP instances test for Fuse integration

### PR DESCRIPTION
**Pull request by tkobayas**
**JIRA**: 

Related to https://issues.redhat.com/browse/RHPAM-3128

You can test like this:

mvn clean install -Deap.kie.server.url=file:///home/xxx/jboss-eap-7.3.1.zip -Deap.url=file:///home/xxx/jboss-eap-7.2.7.zip -Dfuse.on.eap.url=file:///home/xxx/fuse-eap-installer-7.7.0.jar -Dkie.server.war=/home/xxx/kie-server.war

So you just need to add "eap.kie.server.url" to point at EAP 7.3 zip.

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
could we close this as RHPAM-3128 is fixed and verified?

**Comment by tkobayas** [comment]
Yes, closing.

**Pull request closed without merging**
