### PR TITLE
[TEST] test comments. DO NOT MERGE 

### PR DESCRIPTION
**Pull request by Ginxo**

### CODE REVIEW

**Comment by Ginxo** [comment]
test

**Comment by Ginxo** [comment]
As datasource is parameterized, then each instance in jenkins reallocates a different database by means of dballocator.
Regarding case sensitivity, I think it's out of our control to change collation at dballocator, but at least we can test those queries in the certified environments.

**Comment by Ginxo** [comment]
LGTM

**Comment by Ginxo** [comment]
As datasource is parameterized, then each instance in jenkins reallocates a different database by means of dballocator.
Regarding case sensitivity, I think it's out of our control to change collation at dballocator, but at least we can test those queries in the certified environments.

**Comment by Ginxo** [comment]
LGTM

**Comment by Ginxo** [comment]
As datasource is parameterized, then each instance in jenkins reallocates a different database by means of dballocator.
Regarding case sensitivity, I think it's out of our control to change collation at dballocator, but at least we can test those queries in the certified environments.

**Comment by Ginxo** [comment]
Jenkins retest this please

**Comment by Ginxo** [comment]
Jenkins retest this please

**Comment by Ginxo** [comment]
As datasource is parameterized, then each instance in jenkins reallocates a different database by means of dballocator.
Regarding case sensitivity, I think it's out of our control to change collation at dballocator, but at least we can test those queries in the certified environments.

**Comment by Ginxo** [comment]
LGTM

**Comment by Ginxo** [comment]
Jenkins retesttest this please

**Comment by AntStephenson** [comment]
LGTM

**Comment by Ginxo** [comment]
Kudos, SonarCloud Quality Gate passed!

[Bug](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=BUG)  
[Vulnerability](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=VULNERABILITY) (and [Security Hotspot](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=SECURITY_HOTSPOT) to review)  
[Code Smell](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&resolved=false&types=CODE_SMELL)

[No Coverage information](https://sonarcloud.io/component_measures?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&metric=coverage&view=list) No Coverage information  
[](https://sonarcloud.io/component_measures?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=org.drools%3Adroolsjbpm-integration&pullRequest=2150&metric=new_duplicated_lines_density&view=list)

warning The version of Java (1.8.0_202) you have used to run this analysis is deprecated and we will stop accepting it from October 2020. Please update to at least Java 11.
Read more [here](https://sonarcloud.io/documentation/upcoming/)

**Comment by Ginxo** [comment]
As datasource is parameterized, then each instance in jenkins reallocates a different database by means of dballocator.
Regarding case sensitivity, I think it's out of our control to change collation at dballocator, but at least we can test those queries in the certified environments.

**Comment by Ginxo** [comment]
As datasource is parameterized, then each instance in jenkins reallocates a different database by means of dballocator.
Regarding case sensitivity, I think it's out of our control to change collation at dballocator, but at least we can those queries in the certified environments.

**Comment by Ginxo** [comment]
I think it's out of our control to change collation at dballocator, but at least we can test those queries in the certified environments.

**Comment by Ginxo** [comment]
As datasource is parameterized, then each instance in jenkins reallocates a different database by means of dballocator.
Regarding case sensitivity, I think it's out of our control to change collation at dballocator, but at least we can those queries in the certified environments.

**Pull request closed without merging**
