### PR TITLE
[JBPM-6574] Test with JMX that timer node name has been added to jobName

### PR DESCRIPTION
**Pull request by gmunozfe**
Depends on [jbpm#1672](https://github.com/kiegroup/jbpm/pull/1672)

Added a springboot test using JMX to obtain jobName containing the node name for an "Intermediate Catch Event"

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
unrelated failures

**Comment by mareknovotny** [comment]
fyi https://github.com/kiegroup/droolsjbpm-integration/pull/2150#issuecomment-659240072 is talking about the fix of those 7 failures, there is the PR CI already triggered to prove it too

**Comment by gmunozfe** [comment]
jenkins retest this please

**Comment by gmunozfe** [comment]
@kiegroup/gatekeepers could you please merge this?

**Pull request merged**
