### PR TITLE
Fix getCaseInstanceProcessInstance API description typo

### PR DESCRIPTION
**Pull request by ron-murhammer**
Fix getCaseInstanceProcessInstance API description typo

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@mswiderski Moved all the API description fix PRs to this one.

**Comment by mswiderski** [comment]
Ok to test

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
test failures not related

**Comment by mswiderski** [comment]
@ron-murhammer thanks a lot for these fixes

**Pull request merged**
