### PR TITLE
DROOLS-4928 Remove common parent and test kjar rules from controller tests

### PR DESCRIPTION
**Pull request by baldimir**

### CODE REVIEW

**Comment by lucamolteni** [comment]
@baldimir does the suite run any faster in this way? what are the advantages?

**Comment by baldimir** [comment]
@lucamolteni not sure if it runs faster, but it removes some areas for potential test instabilities that are not related in any way to the scenarios tested.

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
@baldimir I have prepared a test stabilization PR on https://github.com/kiegroup/droolsjbpm-integration/pull/1997 , it should help according to the results from CI.

**Comment by baldimir** [comment]
Ok, thanks, closing this for now.

**Pull request closed without merging**
