### PR TITLE
[RHPAM-2977] upgrade jackson to version 2.10.4

### PR DESCRIPTION
**Pull request by mariofusco**
Parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1352

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins build

**Comment by mareknovotny** [comment]
from FDB we would need also https://github.com/errai/errai/pull/388

**Comment by mareknovotny** [comment]
There is some problem with kie-osgi maven dependencies?
`Unable to resolve com.fasterxml.jackson.module.jackson-module-jaxb-annotations/2.10.4: missing requirement [com.fasterxml.jackson.module.jackson-module-jaxb-annotations/2.10.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.xml.bind)(version>=2.3.0)(!(version>=3.0.0)))"]]]`
but I can see that in feature https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml#L167

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
@mariofusco @ruromero can't reproduce it locally. Trying again CI build

**Comment by mareknovotny** [comment]
there was merged Thorntail upgrade https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1360 which should solve the ProcessMigrationIntegrationTest failure

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Pull request merged**
