### PR TITLE
[7.2.x] JBPM-6204: Add tests covering exception handling, JBPM-6223 - CaseServicesClient not rising exceptions when bad container ID is used

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by domhanak** [comment]
@mswiderski is CI turned on on 7.2x branch? :)

**Comment by mswiderski** [comment]
@domhanak that's actually very good question... @mbiarnes @psiroky is it?

**Comment by psiroky** [comment]
It is not at this point. We will need to fix that.

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
