### PR TITLE
[JBPM-9291] AMQ Stream (Kafka) Integration WIH / workflow component

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/JBPM-9296
depends on 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1434
https://github.com/kiegroup/jbpm/pull/1727

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
failures not related.

**Comment by elguardian** [comment]
Jenkins run fdb

**Review by afalhambra — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
