### PR TITLE
[RHPAM-1927] Rename fuse71 profile to fuse7

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by kie-ci6** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by jiripetrlik** [comment]
ok to test

**Comment by grgrzybek** [comment]
Should I prepare PR for master as well?

**Comment by mareknovotny** [comment]
yes, please @grgrzybek

**Comment by grgrzybek** [comment]
@mareknovotny but looks like the commit is already there: b15eb916152a7ccc9cea38d56a33150b1c0dc7d3

**Comment by mareknovotny** [comment]
@grgrzybek ok, great

**Pull request merged**
