### PR TITLE
DROOLS-4928 Enable executable model in kie-server-integ-tests-controller

### PR DESCRIPTION
**Pull request by baldimir**
- Also removes common-parent from the test kjars, to reduce the setup complexity (no need to deploy common-parent jar to Maven repository to build the test kjar(s)). 
- Also enables testScanNow in KieControllerRuleCapabilitiesIntegrationTest

### CODE REVIEW

**Comment by baldimir** [comment]
This is the old PR I had opened some time ago. I wasn't able to reopen it again, therefore this new PR.

**Comment by lucamolteni** [comment]
@baldimir is this faster than before? Did you measure?

**Comment by baldimir** [comment]
@lucamolteni I didn't measure, but I think it runs similarly as it used to run before.

**Comment by baldimir** [comment]
@kiegroup/gatekeepers can someone please merge this?

**Pull request merged**
