### PR TITLE
kie-server-tests: Remove duplicated dependency, ignore test

### PR DESCRIPTION
**Pull request by sutaakar**

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by domhanak** [comment]
jenkins retest this

**Comment by domhanak** [comment]
Failure is related to bug with rounding miliseconds of the date and equalsTo filter than does not match the date because it is different by 002 milliseconds. Should be fixed by this #1036 and we should no longer have these random failures

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request merged**
