### PR TITLE
JBPM-7934 - Update Controller REST API endpoint data to Swagger

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@sterobin np, I removed the reference to _jBPM Controller_ now, leaving just _controller_. As for the examples, I'm providing both types (XML and JSON) for all applicable endpoints.

**Comment by cristianonicolai** [comment]
test failure is unrelated to me ( camel ), @mswiderski @MarianMacik are you ok to get this merged?

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by mswiderski** [comment]
these are failing due to some OSGi missing imports/exports for DMN

```
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=kie-dmn; type=karaf.feature; version="[7.15.0.SNAPSHOT,7.15.0.SNAPSHOT]"; filter:="(&(osgi.identity=kie-dmn)(type=karaf.feature)(version>=7.15.0.SNAPSHOT)(version<=7.15.0.SNAPSHOT))" [caused by: Unable to resolve kie-dmn/7.15.0.SNAPSHOT: missing requirement [kie-dmn/7.15.0.SNAPSHOT] osgi.identity; osgi.identity=org.kie.dmn.feel; type=osgi.bundle; version="[7.15.0.201811190400,7.15.0.201811190400]"; resolution:=mandatory [caused by: Unable to resolve org.kie.dmn.feel/7.15.0.201811190400: missing requirement [org.kie.dmn.feel/7.15.0.201811190400] osgi.wiring.package; filter:="(osgi.wiring.package=ch.obermuhlner.math.big)"]]
```

@tarilabs could you please have a look?

**Comment by tarilabs** [comment]
Thanks for the heads up @mswiderski sorry will take a look

**Comment by tarilabs** [comment]
@mswiderski I am addressing that here: https://github.com/kiegroup/drools/pull/2154

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
