### PR TITLE
[7.59.x] JBPM-9935 : JMS login is using JAAS to get username and roles

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**:  

[JBPM-9935](https://issues.redhat.com/browse/JBPM-9935)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Messed up the rebase, fixing it.

**Review by sutaakar — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Rikkola** [comment]
`org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT` 
I was reported this was failing in main too, taking a look.

**Comment by mareknovotny** [comment]
This is flaky test, we can merge without problem

**Comment by mareknovotny** [comment]
do we have a PR for main too?

**Comment by Rikkola** [comment]
We will soon

**Pull request merged**
