### PR TITLE
PLANNER-1622: [Tasks Assignment] Planning model iteration #1

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
Hi @rsynek this is the final version of the PR into mater.

**Comment by wmedvede** [comment]
non related tests failed

org.kie.server.integrationtests.jbpm.cases.CaseAdminServiceIntegrationTest.testGetCaseInstancesByStatus[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:38543/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.cases.CaseAdminServiceIntegrationTest.testGetCaseInstancesByStatusSorting[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:38543/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.cases.CaseAdminServiceIntegrationTest.testGetCaseInstancesSorting[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:38543/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.cases.CaseAdminServiceIntegrationTest.testGetCaseInstances[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:38543/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.cases.CaseAdminServiceIntegrationTest.testGetCaseInstancesByStatus[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:38543/kie-server-

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
@rsynek looks like non related tests has failed again (all integration tests, so it could be related with the node itself), BUT the artifacts where generated well. So the classes in this PR has built well and their corresponding tests has passed too.

Considering that this PR has only the core model and affects no other area I'd suggest merging instead of wasting more time on int.

**Comment by rsynek** [comment]
Test failures are caused by https://github.com/kiegroup/jbpm/commit/3097bbc46271c92a3225f7ba02927bdedccedf75.

**Pull request merged**
