### PR TITLE
[JBPM-9882] Adding actual owner to TaskEvent

### PR DESCRIPTION
**Pull request by fjtirado**
With this addition, code retrieving the event can determine which
was the actual owner after the operation was applied.

**JIRA**:

[link](https://issues.redhat.com/browse/JBPM-9882)

**referenced Pull Requests**: 
https://github.com/kiegroup/droolsjbpm-knowledge/pull/548

### CODE REVIEW

**Review by elguardian — CHANGES_REQUESTED** [review]
We need to discuss this.

**Review by elguardian — APPROVED** [review]

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by afalhambra** [comment]
closing pr - opening same on https://github.com/kiegroup/droolsjbpm-integration/pull/2617

**Pull request closed without merging**
