### PR TITLE
JBPM-9173: Create reproducer test for dmn date on kie server evaluation

### PR DESCRIPTION
**Pull request by jomarko**
This PR is not a fix.
For more details see: https://issues.redhat.com/browse/JBPM-9173

### CODE REVIEW

**Comment by sutaakar** [comment]
@jomarko The PR looks ok, though I would keep it open until a fix is ready.
If the fix will affect just runtime then I would prefer to have this test as unit test in runtime. If the fix will include Kie server marshalling then it is ok to have this test here as part of the fix.

**Comment by jomarko** [comment]
@sutaakar one more question. Is the concept I used for passing person object (I represent as a Map) correct? Or should I pass somehow a Person java class directly?

**Comment by sutaakar** [comment]
I am not sure, I don't have much knowledge of dmn.

**Comment by jomarko** [comment]
@sutaakar thank you for your answer. I have added do not merge label as you suggested not to merge sooner than fix is ready.

**Comment by tarilabs** [comment]
> I am not sure, I don't have much knowledge of dmn.

Just to be clear, there is nothing specific of DMN here. This is just incidentally used as part of the example.

**Comment by tarilabs** [comment]
green :)

**Comment by jomarko** [comment]
@sutaakar may I ask you to review when you have a moment?

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
