### PR TITLE
[JBPM-9812] publish events when using singleton runtime strategy

### PR DESCRIPTION
**Pull request by fjtirado**
Switching from programmatic to declarative approach

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9812)

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins test this

**Review by gmunozfe — APPROVED** [review]
Looks good to me, nailed down @fjtirado !
I've added some integration tests with the PR [droolsjbpm-integration#2534](https://github.com/kiegroup/droolsjbpm-integration/pull/2534) and they worked with this fix

**Comment by fjtirado** [comment]
unrelated, please jenkins test this

**Comment by fjtirado** [comment]
unrelated failures,  jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
@mareknovotny  checking if ci is working now for this one after various test failures has been fixing by other jiras (I guess it will)
jenkins retest this

**Review by afalhambra — APPROVED** [review]
Great job!

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
unrelated, jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Pull request merged**
