### PR TITLE
JBPM-5835: Test coverage for KeepLatestContainerOnlyPolicy

### PR DESCRIPTION
**Pull request by sutaakar**
It could be fixed by not disposing containers in CREATING state or disposing just containers with earlier version. @mswiderski What do you think?

### CODE REVIEW

**Comment by sutaakar** [comment]
Also I have noticed that this policy implementation use its own controller instance: https://github.com/kiegroup/droolsjbpm-integration/blob/9cddb3873c926c4c9d46bfb885e287a438c26e64/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/policy/KeepLatestContainerOnlyPolicy.java#L90 . I think it would be better to use centralized solution, for example provided by KieServerImpl: https://github.com/kiegroup/droolsjbpm-integration/blob/f7dcde6ad77f79efcb286d5327f3e00b8a8cd0c4/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java#L808

**Comment by mswiderski** [comment]
@sutaakar the idea for the fix is valid, do you mind adding it as a fix next to the test?

and using the same controller ... hmm what would be the gain here? Other than reusing that instance?

**Comment by sutaakar** [comment]
Done. About that controller, the only problem what could happen is if customer will implement its own controller with different endpoints. For KieServerImpl there could be provided new controller using service loader, but KeepLatestContainerOnlyPolicy has hardcoded controller implementation.

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Pull request merged**
