### PR TITLE
[DROOLS-6842] Fix Karaf integration tests

### PR DESCRIPTION
**Pull request by grgrzybek**
[DROOLS-6842] Adjust Karaf features and test configuration to Camel 2.24.0 and CXF 3.4.x

[DROOLS-6842] Add optional JPA import to kie-spring to fix KieSpringjBPMPersistenceKarafIntegrationTest

[DROOLS-6842][JBPM-9920] Synchronize test-accessible Taskorm.xml with jbpm

[DROOLS-6842][RHPAM-4038] Add required httpcore-osgi bundle to kie-server-client feature

Signed-off-by: Grzegorz Grzybek <gr.grzybek@gmail.com>

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Build Chain / ubuntu-latest - Java 8: Green but it shows some failures
```
2022-02-23T18:00:16.5006196Z [INFO] Running org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest
2022-02-23T18:00:16.5069500Z 18:00:16.504 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:179 - *** The karaf version is 4.3.2 ***
2022-02-23T18:00:16.5070688Z 18:00:16.504 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:180 - *** The cxf version is 3.4.5 ***
2022-02-23T18:00:16.5090598Z 18:00:16.504 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getKarafDistributionOption:181 - *** The camel version is 2.24.0 ***
2022-02-23T18:00:16.5091517Z 18:00:16.505 [main] INFO  o.k.k.i.AbstractKarafIntegrationTest.getFeaturesUrl:296 - Features URL: mvn:org.kie/kie-karaf-features/7.67.0-SNAPSHOT/xml/features
2022-02-23T18:00:17.4770767Z WireMock server started and bound to localhost:59400
2022-02-23T18:00:30.2475906Z org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=kie-camel; type=karaf.feature; version="[7.67.0.SNAPSHOT,7.67.0.SNAPSHOT]"; filter:="(&(osgi.identity=kie-camel)(type=karaf.feature)(version>=7.67.0.SNAPSHOT)(version<=7.67.0.SNAPSHOT))" [caused by: Unable to resolve kie-camel/7.67.0.SNAPSHOT: missing requirement [kie-camel/7.67.0.SNAPSHOT] osgi.identity; osgi.identity=cxf-specs; type=karaf.feature; version="[3.3.0,3.4.0)"]
2022-02-23T18:00:30.2497831Z    at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
2022-02-23T18:00:30.2512235Z    at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
2022-02-23T18:00:30.2512858Z    at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
2022-02-23T18:00:30.2513624Z    at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
2022-02-23T18:00:30.2514291Z    at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
2022-02-23T18:00:30.2515462Z    at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
2022-02-23T18:00:30.2516344Z    at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
2022-02-23T18:00:30.2517295Z    at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
2022-02-23T18:00:30.2518053Z    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-02-23T18:00:30.2518616Z    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-02-23T18:00:30.2519286Z    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-02-23T18:00:30.2519750Z    at java.lang.Thread.run(Thread.java:750)
2022-02-23T18:00:30.2528202Z Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve kie-camel/7.67.0.SNAPSHOT: missing requirement [kie-camel/7.67.0.SNAPSHOT] osgi.identity; osgi.identity=cxf-specs; type=karaf.feature; version="[3.3.0,3.4.0)"
2022-02-23T18:00:30.2530169Z    at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
2022-02-23T18:00:30.2530610Z    ... 12 more
2022-02-23T18:03:18.0017351Z [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 181.491 s <<< FAILURE! - in org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest
2022-02-23T18:03:18.0059832Z [ERROR] org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest  Time elapsed: 181.49 s  <<< ERROR!
2022-02-23T18:03:18.0060445Z java.lang.RuntimeException: Cannot get the remote bundle context
2022-02-23T18:03:18.0067490Z Caused by: java.rmi.NotBoundException: f1d9c170-4d74-425c-a87b-83d52fd38f9d
2022-02-23T18:03:18.0067759Z
2022-02-23T18:03:18.0070288Z [ERROR] org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest  Time elapsed: 181.491 s  <<< ERROR!
2022-02-23T18:03:18.0071204Z java.lang.RuntimeException: Container never came up
2022-02-23T18:03:18.0072040Z    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
2022-02-23T18:03:18.0072739Z    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
2022-02-23T18:03:18.0083163Z    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
2022-02-23T18:03:18.0084009Z    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
```
That's strange. I see all tests successful on my local env.

Build Chain / ubuntu-latest - Java 11:
```
2022-02-23T15:44:53.4860197Z 2022-02-23 15:44:53,485 [org.kie.spring.KModuleBeanFactoryPostProcessor|main] INFO  Adding KieModule from /home/runner/work/droolsjbpm-integration/droolsjbpm-integration/kiegroup_droolsjbpm_integration/kie-spring/target/test-classes/ to repository.
2022-02-23T16:14:53.8968759Z 2022-02-23 16:14:53,894 [org.springframework.context.support.AbstractApplicationContext|main] WARN  Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ksession1': Cannot resolve reference to bean 'drl_kiesample3' while setting bean property 'kBase'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'drl_kiesample3': Invocation of init method failed; nested exception is java.lang.RuntimeException: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for org.default:artifact:jar:1.0.0
2022-02-23T16:14:53.9517461Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1,800.826 s <<< FAILURE! - in org.kie.spring.tests.KieSpringComponentScanTest
2022-02-23T16:14:53.9691593Z [ERROR] org.kie.spring.tests.KieSpringComponentScanTest  Time elapsed: 1,800.826 s  <<< ERROR!
2022-02-23T16:14:53.9725867Z org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ksession1': Cannot resolve reference to bean 'drl_kiesample3' while setting bean property 'kBase'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'drl_kiesample3': Invocation of init method failed; nested exception is java.lang.RuntimeException: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for org.default:artifact:jar:1.0.0
2022-02-23T16:14:53.9734227Z    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
...
2022-02-23T16:14:54.0129559Z Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'drl_kiesample3': Invocation of init method failed; nested exception is java.lang.RuntimeException: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for org.default:artifact:jar:1.0.0
2022-02-23T16:14:54.0140285Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
2022-02-23T16:14:54.0141266Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
2022-02-23T16:14:54.0169911Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
2022-02-23T16:14:54.0170814Z    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2022-02-23T16:14:54.0187623Z    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2022-02-23T16:14:54.0188438Z    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2022-02-23T16:14:54.0189074Z    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2022-02-23T16:14:54.0207579Z    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
2022-02-23T16:14:54.0208610Z    ... 35 more
2022-02-23T16:14:54.0209290Z Caused by: java.lang.RuntimeException: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for org.default:artifact:jar:1.0.0
2022-02-23T16:14:54.0234356Z    at org.appformer.maven.integration.MavenRepository.getArtifactDependecies(MavenRepository.java:128)
2022-02-23T16:14:54.0235328Z    at org.appformer.maven.integration.DefaultArtifactResolver.getArtifactDependecies(DefaultArtifactResolver.java:54)
2022-02-23T16:14:54.0236059Z    at org.kie.scanner.MavenClassLoaderResolver.getJarDependencies(MavenClassLoaderResolver.java:110)
2022-02-23T16:14:54.0253483Z    at org.kie.scanner.MavenClassLoaderResolver.getClassLoader(MavenClassLoaderResolver.java:74)
2022-02-23T16:14:54.0255579Z    at org.drools.compiler.kie.builder.impl.InternalKieModule.createModuleClassLoader(InternalKieModule.java:152)
2022-02-23T16:14:54.0256414Z    at org.drools.compiler.kie.builder.impl.KieModuleKieProject.<init>(KieModuleKieProject.java:56)
2022-02-23T16:14:54.0282941Z    at org.drools.compiler.kie.builder.impl.KieServicesImpl.newKieContainer(KieServicesImpl.java:195)
2022-02-23T16:14:54.0283705Z    at org.drools.compiler.kie.builder.impl.KieServicesImpl.newKieContainer(KieServicesImpl.java:176)
2022-02-23T16:14:54.0284470Z    at org.kie.spring.KieObjectsResolver.resolveKContainer(KieObjectsResolver.java:60)
2022-02-23T16:14:54.0300765Z    at org.kie.spring.KieObjectsResolver.resolveKBase(KieObjectsResolver.java:32)
2022-02-23T16:14:54.0301431Z    at org.kie.spring.factorybeans.KBaseFactoryBean.afterPropertiesSet(KBaseFactoryBean.java:169)
2022-02-23T16:14:54.0302181Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
2022-02-23T16:14:54.0319797Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
2022-02-23T16:14:54.0320460Z    ... 42 more
2022-02-23T16:14:54.0320932Z Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for org.default:artifact:jar:1.0.0
2022-02-23T16:14:54.0347520Z    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:208)
2022-02-23T16:14:54.0348343Z    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
2022-02-23T16:14:54.0365231Z    at org.appformer.maven.integration.MavenRepository.getArtifactDependecies(MavenRepository.java:126)
2022-02-23T16:14:54.0365771Z    ... 54 more
2022-02-23T16:14:54.0366222Z Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.default:artifact:jar:1.0.0
2022-02-23T16:14:54.0370525Z    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
2022-02-23T16:14:54.0384839Z    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
2022-02-23T16:14:54.0385657Z    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
2022-02-23T16:14:54.0386138Z    ... 56 more
2022-02-23T16:14:54.0409969Z Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.default:artifact:pom:1.0.0 from/to central (https://repo1.maven.org/maven2/): Read timed out
2022-02-23T16:14:54.0410711Z    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
2022-02-23T16:14:54.0426850Z    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
2022-02-23T16:14:54.0427518Z    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
2022-02-23T16:14:54.0433132Z    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
2022-02-23T16:14:54.0438768Z    ... 58 more
2022-02-23T16:14:54.0446280Z Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.default:artifact:pom:1.0.0 from/to central (https://repo1.maven.org/maven2/): Read timed out
2022-02-23T16:14:54.0474094Z    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
2022-02-23T16:14:54.0474829Z    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
2022-02-23T16:14:54.0475398Z    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
2022-02-23T16:14:54.0491391Z    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
2022-02-23T16:14:54.0492046Z    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
2022-02-23T16:14:54.0492655Z    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
2022-02-23T16:14:54.0510679Z    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
2022-02-23T16:14:54.0520051Z    ... 61 more
2022-02-23T16:14:54.0520420Z Caused by: java.net.SocketTimeoutException: Read timed out
2022-02-23T16:14:54.0520848Z    at java.base/java.net.SocketInputStream.socketRead0(Native Method)
2022-02-23T16:14:54.0521313Z    at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
2022-02-23T16:14:54.0535795Z    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
2022-02-23T16:14:54.0536267Z    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
2022-02-23T16:14:54.0536724Z    at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
2022-02-23T16:14:54.0701502Z
```
Seems to be a network issue. "Linux - Pull Request" is green so it's likely unrelated to this PR.

**Review by tkobayas — APPROVED** [review]

**Comment by grgrzybek** [comment]
@tkobayas this is strange:
```
missing requirement [kie-camel/7.67.0.SNAPSHOT] osgi.identity; osgi.identity=cxf-specs; type=karaf.feature; version="[3.3.0,3.4.0)"
```

because the PR: https://github.com/grgrzybek/kiegroup-droolsjbpm-integration/blob/DROOLS-6842/kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml#L107-L109 adds explicitly this range:
```xml
<feature version="[3.3,3.5)">cxf-specs</feature>
<feature version="[3.3,3.5)">cxf-core</feature>
<feature version="[3.3,3.5)">cxf-jaxrs</feature>
```

**Comment by tkobayas** [comment]
Hi @mareknovotny   How can we retrigger GHA? (specifically, java 8)

If I correctly understand, `retest this please` only works for "Linux - Pull Request" which runs with JDK 11. Re-triggering Github Action requires a new commit or admin operation, right?

**Review by mariofusco — APPROVED** [review]

**Comment by mareknovotny** [comment]
you could even update PR with empty commit to trigger it automatically @tkobayas

**Comment by mareknovotny** [comment]
@jiripetrlik are you approving this PR change too? i would merge it then

**Comment by tkobayas** [comment]
Hi @grgrzybek  @mareknovotny  @jiripetrlik  I still see the strange error in GHA "Build Chain / ubuntu-latest - Java 8" while it's green.
```
2022-02-24T13:26:19.7590456Z Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve kie-camel/7.67.0.SNAPSHOT: missing requirement [kie-camel/7.67.0.SNAPSHOT] osgi.identity; osgi.identity=cxf-specs; type=karaf.feature; version="[3.3.0,3.4.0)"
```

@grgrzybek  and I tested this PR locally and all tests passed so I guess it's an issue in GHA CI. @mareknovotny , Can we merge this PR anyway? Because:

- This PR is required for 7.13 release (Fuse integration)
- This PR only deals with OSGi so this shouldn't break other components.
- The GHA is green anyway so it wouldn't bother other PRs. 

I'll file a JIRA to investigate the CI problem separately (not sure if I can figure out).

**Comment by grgrzybek** [comment]
Hi

There MUST be something cached here... there's no occurrence of "[3.3,3.4)"
anywhere.

07:52 $ grep -r '3\.3,3\.4'
✘-1 ~/sources/github.com/kiegroup/droolsjbpm-integration [DROOLS-6842 L|✔]
07:52 $ grep -r '3\.3,3\.5'
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml:
   <feature version="[3.3,3.5)">cxf-specs</feature>
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml:
   <feature version="[3.3,3.5)">cxf-core</feature>
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml:
   <feature version="[3.3,3.5)">cxf-jaxrs</feature>

I really don't know what may be the problem here ;)

regards
Grzegorz Grzybek

pt., 25 lut 2022 o 06:24 Toshiya Kobayashi ***@***.***>
napisał(a):

**Comment by tkobayas** [comment]
Hi @mareknovotny , please merge https://github.com/kiegroup/jbpm/pull/2110 as well, thanks!

**Comment by mareknovotny** [comment]
hmm, i didn't notice it is related, not mention that PR even here in first comment. What a shame! I could see the https://github.com/kiegroup/jbpm/pull/2110 didn't run CI on Jenkins. So launched it now.

**Comment by tkobayas** [comment]
@mareknovotny Sorry that I didn't emphasize that PR. @grgrzybek Please write related PRs in the first comment of a PR next time, thanks!

**Comment by grgrzybek** [comment]
Sorry for not reading carefully @tkobayas ! Only checked to have proper description in https://github.com/kiegroup/jbpm/pull/2110...

**Review by jiripetrlik — COMMENTED** [review]
@mareknovotny @grgrzybek @tkobayas 
Sorry for late reply. Looks good to me.

**Pull request merged**
