### PR TITLE
JBPM-6243 - Add support for kie server controller events notification…

### PR DESCRIPTION
**Pull request by cristianonicolai**
… for web socket clients

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mswiderski another cherry-pick in case is relevant for 7.5.x

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by etirelli** [comment]
@mswiderski @cristianonicolai assuming that the risk for this is low, please go ahead and merge into 7.5.x.

**Comment by cristianonicolai** [comment]
@etirelli @mswiderski thanks.

**Pull request merged**
