### PR TITLE
[JBPM-8177] Security exceptions in localhost log when running kie-server on JWS

### PR DESCRIPTION
**Pull request by elguardian**
bump version to web 3.1 and added the proper constraints to avoid SEVERE log

### CODE REVIEW

**Comment by elguardian** [comment]
@MarianMacik do you mind to check the controller in tomcat ?

**Comment by elguardian** [comment]
@MarianMacik that is normal and is by spec IIRC

**Comment by MarianMacik** [comment]
@elguardian Yes, I have nothing against it, I put it here just as a "proof" :)

**Comment by elguardian** [comment]
@mswiderski can you merge if you agree plz ?

**Comment by MarianMacik** [comment]
@mswiderski My only question was about the allowance of OPTION method for the same purpose as in KIE Server. If it is not a big value in controller, we can merge it as it is now.

**Comment by mswiderski** [comment]
@MarianMacik I'd say it would make sense to add the same OPTIONS as people could build JS UI on top of the controller so might be good to align...

**Comment by MarianMacik** [comment]
@elguardian can you add the OPTION method, please? It is the same snippet as here:
https://github.com/kiegroup/droolsjbpm-integration/pull/1810#pullrequestreview-227262625
Just with different URL patterns:
```
<url-pattern>/rest/*</url-pattern>
<url-pattern>/websocket/*</url-pattern>
```

**Comment by elguardian** [comment]
done @MarianMacik let me know if there is anything else, otherwise let's try if someone can merge

**Comment by MarianMacik** [comment]
Tested OPTIONS method as well.

**Comment by MarianMacik** [comment]
@mswiderski please approve so I can merge

**Pull request merged**
