### PR TITLE
[RHBPMS-4312] Added loading passwords from KeyStore in drools core

### PR DESCRIPTION
**Pull request by rstancel**
Jira: https://issues.jboss.org/browse/RHBPMS-4312

### CODE REVIEW

**Comment by rstancel** [comment]
This PR depends on https://github.com/kiegroup/drools/pull/1588 and cannot pass until it is merged

**Comment by mswiderski** [comment]
@rstancel if you name the branches the same the build will take both into account when running

**Comment by mswiderski** [comment]
@rstancel if I am not mistaken this now completely switches to keystone - meaning existing installation when upgraded won't work anymore unless keystore is created with password, right?

while for product I think that might be acceptable I think for community we should have this fallback (with warning in the logs pointing to docs how to configure keystore) that will use defaults or system property password

@etirelli @rstancel what do you think guys?

**Comment by rstancel** [comment]
@mswiderski you are exactly right. I made it because this was a result from discussion with security guys in previous approach

**Comment by etirelli** [comment]
@rstancel as Maciej said, while we can recommend keystore usage, it presents other issues for community, specially on setup. On trusted environments, a keystore should not be mandatory.

**Comment by rstancel** [comment]
Closing this PR. It is substituded by this one: https://github.com/kiegroup/droolsjbpm-integration/pull/1267

**Pull request closed without merging**
