### PR TITLE
Rhdm 733 test coverage

### PR DESCRIPTION
**Pull request by sutaakar**
Contains fix and a test coverage.
The test fails on line 73 as the rule seems not to fire.

### CODE REVIEW

**Comment by sutaakar** [comment]
Just checked that the Kie server Maven repo loads both SNAPSHOT kjars to kie-server-testing-server-local-repo

**Comment by mswiderski** [comment]
@sutaakar hmm interesting as the build was actually green so all seems to work, or?

**Comment by sutaakar** [comment]
@mswiderski Right, it works now locally.
But I have noticed random NPE (didn't affect the result):
<pre><code> [INFO] [talledLocalContainer] 18:51:23,776 ERROR [stderr] (Timer-2) Exception in thread "Timer-2" java.lang.NullPointerException
[INFO] [talledLocalContainer] 18:51:23,777 ERROR [stderr] (Timer-2) 	at org.kie.server.services.impl.KieServerScannerEventListener.onKieScannerUpdateResultsEvent(KieServerScannerEventListener.java:54)
[INFO] [talledLocalContainer] 18:51:23,777 ERROR [stderr] (Timer-2) 	at org.kie.scanner.event.KieScannerEventSupport.fireKieScannerUpdateResultsEventImpl(KieScannerEventSupport.java:49)
[INFO] [talledLocalContainer] 18:51:23,778 ERROR [stderr] (Timer-2) 	at org.kie.scanner.KieRepositoryScannerImpl.updateKieModule(KieRepositoryScannerImpl.java:348)
[INFO] [talledLocalContainer] 18:51:23,778 ERROR [stderr] (Timer-2) 	at org.kie.scanner.KieRepositoryScannerImpl.scanNow(KieRepositoryScannerImpl.java:321)
[INFO] [talledLocalContainer] 18:51:23,778 ERROR [stderr] (Timer-2) 	at org.kie.scanner.KieRepositoryScannerImpl$ScanTask.run(KieRepositoryScannerImpl.java:289)
[INFO] [talledLocalContainer] 18:51:23,779 ERROR [stderr] (Timer-2) 	at java.util.TimerThread.mainLoop(Timer.java:555)
[INFO] [talledLocalContainer] 18:51:23,779 ERROR [stderr] (Timer-2) 	at java.util.TimerThread.run(Timer.java:505)
 </code></pre>

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@sutaakar looks like some issues deleting files in the added test case ... any ideas?

**Comment by sutaakar** [comment]
@mswiderski Weird, will try to simulate it locally

**Comment by sutaakar** [comment]
@mswiderski Not managed to simulate it locally, but I have a suspicion.
The failure happens when test is trying to delete Kie server local repo. I debugged it locally and I discovered that when container with started scanner is disposed then scanner thread is still running (and I suppose it creates a random failure as it  access repo files while they are being deleted).
I think that the scanner should be stopped in case container is disposed, what do you think?

**Comment by mswiderski** [comment]
@sutaakar fully agree that it should be stopped

**Comment by sutaakar** [comment]
@mswiderski Reported as JBPM-7839

**Comment by mswiderski** [comment]
@sutaakar do you think JBPM-7839 must be solved to stabilise these tests?

**Comment by sutaakar** [comment]
@mswiderski Yes, I think so

**Comment by mswiderski** [comment]
@sutaakar added fix for it to give it a try ... meanwhile working on a test for this change ...

**Comment by mswiderski** [comment]
ok, looks like it helped.... soon the test will come and I guess we will be good to merge

**Comment by mswiderski** [comment]
@sutaakar tests added, could you please take a look?

**Pull request merged**
