### PR TITLE
JBPM-7652 Add HTTPS support to SmartRouter.

### PR DESCRIPTION
**Pull request by DuncanDoyle**
Initial implementation. No proper error handling. No tests.

### CODE REVIEW

**Comment by tsurdilo** [comment]
@DuncanDoyle added some fixes and changes to your code. also added small readme for starting router with tsl support. Squashed all the commits into 1. Can you please take a look and give it another try locally to make sure all is still ok ? Thanks. If you approve I think we are good to go w/ this .

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tmckayus** [comment]
@DuncanDoyle @tsurdilo, question about this.  Should we expect that kieserver instances can connect back to the smartrouter using https with no change? (looking at openshift templates where kieservers have envs hardwired for port 9000 on the smartrouter, thinking generalizing that)

**Pull request merged**
