### PR TITLE
Kie server controller test adjustments

### PR DESCRIPTION
**Pull request by sutaakar**
Adding synchronization loops to stabilize tests for cases when controller is part of Workbench.
In that case controller actions interacting with Kie server are asynchronous.

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Pull request merged**
