### PR TITLE
[JBPM-9329] Use custom truststore for ibm jdk router-proxy tests

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**:  [JBPM-9329](https://issues.redhat.com/browse/JBPM-9329)

Truststore generated with ibm jdk:
`keytool -genkey -alias alias -keystore router_ibm.truststore -storepass mykeystorepass`

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]
Nice work @gmunozfe!

Just out of curiosity, why you moved from static initialization to a static initialization block? Any issue with class loader?

https://github.com/kiegroup/droolsjbpm-integration/blob/533234c508827587ab81e6c8e0b35a281bab8491/kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/proxy/aggregate/KieServerProxyClientTest.java#L45-L47

**Comment by gmunozfe** [comment]
> Nice work @gmunozfe!
> 
> Just out of curiosity, why you moved from static initialization to a static initialization block? Any issue with class loader?
> 
> https://github.com/kiegroup/droolsjbpm-integration/blob/533234c508827587ab81e6c8e0b35a281bab8491/kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/proxy/aggregate/KieServerProxyClientTest.java#L45-L47

No, not really needed, so I gave it back in the same format. Thanks for review @afalhambra !

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
@kiegroup/gatekeepers could you merge?

**Pull request merged**
