### PR TITLE
[RHPAM-2060] - Infinite "Configuration file does not exist" messages …

### PR DESCRIPTION
**Pull request by msmagnanijr**
…in Smart Router logs

See: https://issues.redhat.com/browse/RHPAM-2060

### CODE REVIEW

**Comment by msmagnanijr** [comment]
hey, guys I also need to update the branch for 7.10. Which branch should I use?

**Comment by elguardian** [comment]
@msmagnanijr yes

**Review by elguardian — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]
Looks good to me, works as expected.

**Review by spolti — APPROVED** [review]

**Comment by elguardian** [comment]
merged downstream before this one.

**Pull request merged**
