### PR TITLE
RHPAM-2328: removed unsupported 'io.thorntail:bom-all' and 'swagger'

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/RHPAM-2328

removed unsupported thorntail deps from PIM

### CODE REVIEW

**Comment by ruromero** [comment]
So I understand that what is unsupported is the Swagger fraction, right?

**Comment by MarianMacik** [comment]
That's a good question. I forgot that we use it in one class. And it compiles beause swagger-annotations are on the classpath. So I think we should ask if there is a supported swagger fraction, otherwise we cannot have Swagger here. @mareknovotny what do you think?

**Comment by mareknovotny** [comment]
We can remove it or keep just the swagger annotation

**Comment by ruromero** [comment]
> We can remove it or keep just the swagger annotation

Then let's remove also the Swagger annotations (and dependency) until this fraction is stable. If that ever happens :)

**Comment by mareknovotny** [comment]
done @ruromero, @MarianMacik

**Comment by mareknovotny** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
Jenkins please retest this

**Pull request merged**
