### PR TITLE
[JBPM-9805] Fixing NPE on KafkaConsumer

### PR DESCRIPTION
**Pull request by fjtirado**
Catching throwable rather than exception

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9805)

### CODE REVIEW

**Review by gmunozfe — APPROVED** [review]
Looks good to me, thanks for adding a test for the race condition scenario. Amazing work @fjtirado !

**Comment by elguardian** [comment]
failures not related

**Comment by fjtirado** [comment]
jenkins retes this

**Comment by fjtirado** [comment]
jenkins retest this

**Pull request merged**
