### PR TITLE
[JBPM-9508] Test creation for duplicated processes with same

### PR DESCRIPTION
**Pull request by gmunozfe**
correlationKey

**JIRA**: [JBPM-9508](https://issues.redhat.com/browse/JBPM-9508)

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins retest this

**Review by afalhambra — APPROVED** [review]
Great work @gmunozfe! thanks!

**Comment by afalhambra** [comment]
@gmunozfe just one comment. Since this is not an integration test, would it not make more sense to move this test or a similar test to the jbpm repo instead? So by that, it can be executed in a jenkins db matrix, wdyt?

**Comment by gmunozfe** [comment]
> @gmunozfe just one comment. Since this is not an integration test and is more related to db stuff, would it not make more sense to move this test or a similar test to the jbpm repo instead? So by that, it can be executed in a jenkins db matrix, wdyt?

Here it'll also be executed in db matrix, at exec-server-db-matrix jobs

**Comment by afalhambra** [comment]
@gmunozfe shouldn't we try to rebase and merge this PR?

**Comment by gmunozfe** [comment]
> @gmunozfe shouldn't we try to rebase and merge this PR?

thanks a lot for the heads-up @afalhambra ! Rerunning jenkins after rebase

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
@mareknovotny ready for merging

**Pull request merged**
