### PR TITLE
[7.18.x] AF-1865: [Streamline Development Lifcycle] Fix backguard compatibilities and improve 'dev mode' deployment policy

### PR DESCRIPTION
**Pull request by pefernan**
Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/1747

This change solves some Kie Server backwards compatibility issues, the changes are:

* DEVELOPMENT mode will allow deploy and update any type of modules, not only SNAPSHOTs. DEVELOPMENT mode will still be the default mode.
* Renamed REGULAR mode into PRODUCTION mode. It will keep the same Kie Server deployment policy.

@tomasdavidorg @MarianMacik @mswiderski could you please take a look?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-integration/pull/1748
https://github.com/kiegroup/kie-wb-common/pull/2499
https://github.com/kiegroup/kie-docs/pull/1410

### CODE REVIEW

**Comment by jiripetrlik** [comment]
jenkins retest this

**Comment by grgrzybek** [comment]
@jiripetrlik exactly - I run the tests from the branch of this PR and I had the failures too.
Tomorrow, I'll check what's the problem in normal 7.18.x branch.

**Comment by jiripetrlik** [comment]
@grgrzybek Many thanks for your help with OSGI failures!

**Comment by dgutierr** [comment]
@pefernan @porcelli @grgrzybek The karak tests failure were already identified and a [fix](https://github.com/kiegroup/droolsjbpm-integration/pull/1751) is coming. This shouldn't prevent us from merging this in both master and 7.1.8.x. We can safely proceed with the merge.

**Comment by porcelli** [comment]
@dgutierr the karaf PR is already opened, we might wait for a few more hours to see if it get merged. we already have wait until now, don't think to wait another (max) day won't be a big issue.

**Comment by porcelli** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@porcelli let me update the PR with latest changes!

**Comment by pefernan** [comment]
Jenkins execute full downstream build please

**Pull request merged**
