### PR TITLE
JBPM-6593 - Clustering support for Standalone controller

### PR DESCRIPTION
**Pull request by mswiderski**
@sutaakar could you please have a look?

### CODE REVIEW

**Comment by psiroky** [comment]
Build finished. 4182 tests run, 35 skipped, 7 failed.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
@mswiderski Looks good for Kie servers connected through HTTP.
For Kie server connected through WebSockets it can become more complicated as some Kie servers can be connected to one controller, some to other ones. In such case controller would have to notify its Kie servers about changes in their configuration. What do you think about it?

**Comment by mswiderski** [comment]
@sutaakar this change is to sync the configuration on each controller using same file, so as soon as one writes to it the other reloads that config. 

and what you're referring to is that you have cluster of controllers that behind load balancer and when you change state of the server template kie server is connected to you would like to notify them but for web socket it will only work when the change was done on the server where kie server is connected to right?

for that I would go for another jira as it does affect both (standalone and embedded) controllers.

**Comment by sutaakar** [comment]
@mswiderski Right, will create a JIRA for that

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
