### PR TITLE
[JBPM-9126] Missing "subject" attribute in the UserTaskInstanceDesc

### PR DESCRIPTION
**Pull request by fjtirado**
Changing ConvertUtils to include subject in return values

### CODE REVIEW

**Comment by elguardian** [comment]
@fjtirado  failures seem related. plz check or justify. Otherwise looks ok.

**Comment by fjtirado** [comment]
The error in test execution looks completely unrelated with the change itself. Please launch it again
java.lang.IllegalStateException: There's already another KieContainer created with the id kie-concurrent
	at org.drools.compiler.kie.builder.impl.KieServicesImpl.newKieContainer(KieServicesImpl.java:211)
	at org.drools.compiler.kie.builder.impl.KieServicesImpl.newKieContainer(KieServicesImpl.java:176)
	at org.kie.server.services.impl.KieServerImpl.createContainer(KieServerImpl.java:281)
	at org.kie.server.services.impl.KieContainerCommandServiceImpl.executeScript(KieContainerCommandServiceImpl.java:147)
	at org.kie.server.controller.websocket.client.handlers.CommandScriptMessageHandler.onMessage(CommandScriptMessageHandler.java:68)
	at org.kie.server.controller.websocket.common.handlers.KieServerMessageHandler.onMessage(KieServerMessageHandler.java:48)
	at org.kie.server.controller.websocket.common.handlers.KieServerMessageHandler.onMessage(KieServerMessageHandler.java:27)
	at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:286)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:604)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:590)
	at io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1871)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1451)
	at java.lang.Thread.run(Thread.java:748)

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by elguardian** [comment]
failures unrelated.

**Comment by elguardian** [comment]
good to go

**Pull request merged**
