### PR TITLE
[7.11.x] JBPM-7873 - NoSuchAlgorithmException when starting Smart router with …

### PR DESCRIPTION
**Pull request by tsurdilo**
…HTTPS

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
test failure is not related to this PR. @mswiderski could you take a look when you have time please ?

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by sutaakar** [comment]
Looks good to me, but I think it should be merged just to master.

**Comment by mswiderski** [comment]
it was not requested for 7.1.1 so closing

**Pull request closed without merging**
