### PR TITLE
PLANNER-1627: TaskAssigningPlanning & TaskAssignigRuntime kie-sever extensions (target architecture)

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @rsynek @triceo this PR is basically the refactoring of the task assigning stuff merged on Friday to the final location in kie-server-parent.
Would you mind review?

Thanks

**Comment by rsynek** [comment]
@sutaakar any idea if there is any owner of KIE server now who could review PRs as this one?

**Comment by sutaakar** [comment]
I guess the Kie server doesn't have any specific owner now.

**Comment by wmedvede** [comment]
Hi @krisv your name came up in today's sprint planning meeting as the person candidate for approving/reviewing this Kie Server related PR.
Would you mind have look?

Thanks!

FYI @ge0ffrey

**Comment by wmedvede** [comment]
looks like jenknis job failed due error below but the PR status wasn't refreshed 

08:47:15 GitHub pull request #2034 of commit ac3cfc6ea00b0e89473177ee1b40dd26bb9e7db3, no merge conflicts.
08:47:15 Unable to query GitHub for status of PullRequestorg.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/kiegroup/droolsjbpm-integration/pulls/2034
08:47:15 	at org.kohsuke.github.Requester.parse(Requester.java:646)
08:47:15 	at org.kohsuke.github.Requester.parse(Requester.java:607)

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
Un-related tests failed. Looks like random failures.

++++++++++++++++++
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testScanNow[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42146/kie-server-services/services/rest/server'}]

Failing for the past 1 build (Since Unstable#715 )
Took 4 min 5 sec.
add description
Error Message
Synchronization failed for defined timeout: 240000 milliseconds.
Stacktrace
java.util.concurrent.TimeoutException: Synchronization failed for defined timeout: 240000 milliseconds.

++++++++++++++

org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStartAndStopScanner[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42146/kie-server-services/services/rest/server'}]

Failing for the past 1 build (Since Unstable#715 )
Took 1 min 15 sec.
add description
Error Message
The following assertion failed:
1) expected:<[STARTED]> but was:<[CREATING]>
Stacktrace
org.assertj.core.api.SoftAssertionError: 

The following assertion failed:
1) expected:<[STARTED]> but was:<[CREATING]>

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by sutaakar** [comment]
@wmedvede About https://github.com/kiegroup/droolsjbpm-integration/blob/ac3cfc6ea00b0e89473177ee1b40dd26bb9e7db3/kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-task-assigning-runtime/src/main/java/org/kie/server/remote/rest/taskassigning/runtime/TaskAssigningRuntimeResource.java , if I understand it correctly then these endpoints can be also used by third party user, right? Have you considered adding there Swagger annotations?

**Comment by sutaakar** [comment]
@wmedvede Do you plan to provide implementation of UserSystemService for other application servers or possibly other authentication options like LDAP or Keycloak?

**Comment by sutaakar** [comment]
Have you considered implementing full e2e scenario showing how this functionality can be used by end users of Kie server?

**Comment by wmedvede** [comment]
> @wmedvede About https://github.com/kiegroup/droolsjbpm-integration/blob/ac3cfc6ea00b0e89473177ee1b40dd26bb9e7db3/kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-task-assigning-runtime/src/main/java/org/kie/server/remote/rest/taskassigning/runtime/TaskAssigningRuntimeResource.java , if I understand it correctly then these endpoints can be also used by third party user, right? Have you considered adding there Swagger annotations?

third party users should avoid using this method since the shouldn't try to executePlannings or more flexible queries are provided. But no problem, the swagger information was added.

**Comment by wmedvede** [comment]
> @wmedvede Do you plan to provide implementation of UserSystemService for other application servers or possibly other authentication options like LDAP or Keycloak?

It's not the priority right now, i.e. out of this PR. Even so we have to see, since getting the users from the UserSystemService is not only getting the user + group information it implies also grabbing business related information like skills and affinities which may vary in impredectible ways depending on the particular integration, client. etc. I believe we should avoid ending up in kind of "generic" business data extractor for LDAP, keycloack, etc. Anyway, we can see this in the future.

**Comment by wmedvede** [comment]
> Have you considered implementing full e2e scenario showing how this functionality can be used by end users of Kie server?

Let's see if I go the time for setting up all this, right now there are still other development pieces pending. But I'll try to add some tasks consumption examples in the getting started guide.

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by ge0ffrey** [comment]
Hi guys,

This PR has been open a while, let's get this wrapped up and merged. We have 3 approvals for this PR and no rejections. If no one objects further, I 'll merge it tomorrow.

@krisv @sutaakar Let me know if you want a few more days to review first, otherwise I 'll merge tomorrow, so it's easier to further polish the task assignment work in additional, smaller PR's.

**Comment by ge0ffrey** [comment]
> > Have you considered implementing full e2e scenario showing how this functionality can be used by end users of Kie server?
> 
> Let's see if I go the time for setting up all this, right now there are still other development pieces pending. But I'll try to add some tasks consumption examples in the getting started guide.

Good question - such an end to end scenario would make an interesting video or blog post too.

**Comment by wmedvede** [comment]
Well full build failed in non related tests but all kie-server, business central and jbpm-server artifacts  were generated well.

It looks like there are non related DMNDesinger errors breaking the build:

	Test Result (45 failures / +45)
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testConnectorKnowledgeRequirement
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testInputData
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testConnectorAuthorityRequirement
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testBasicModel
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testBusinessKnowledgeModelExpressionLiteral
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testNodeStyling

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
This is failing again due to non related tests but, looks like all related tests and artifacts were generated.

Expected condition failed: waiting for visibility of element located by By.className: qe-docks-item-W-org.kie.dmn.decision.navigator (tried for 10 second(s) with 500 milliseconds interval)
Stacktrace
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.className: qe-docks-item-W-org.kie.dmn.decision.navigator (tried for 10 second(s) with 500 milliseconds interval)
	at org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.openDMNDesigner(DMNDesignerKogitoSeleniumIT.java:122)
Caused by: org.openqa.selenium.NoSuchElementException: 
Cannot locate an element using By.className: qe-docks-item-W-org.kie.dmn.decision.navigator
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.4.1.el7.x86_64', java.version: '1.8.0_202'
Driver info: driver.version: unknown
	at org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.openDMNDesigner(DMNDesignerKogitoSeleniumIT.java:122)

**Comment by rsynek** [comment]
@wmedvede I have pointed @jomarko at this PR, let's see.

**Comment by jomarko** [comment]
The failed tests are 100% unrelated. feel free to merge. I reported jira for myself and started to investigate here https://issues.redhat.com/browse/KOGITO-1458

**Comment by rsynek** [comment]
Merging based on the investigation of failed tests in FDB.

**Comment by jomarko** [comment]
Failing tests are due to https://issues.redhat.com/browse/DROOLS-5170

**Pull request merged**
