### PR TITLE
[JBPM-9461] Add a flag/switch to include or exclude process variables

### PR DESCRIPTION
**Pull request by elguardian**
Jira : https://issues.redhat.com/browse/JBPM-9461
depends on https://github.com/kiegroup/jbpm/pull/1800

### CODE REVIEW

**Review by afalhambra — CHANGES_REQUESTED** [review]
`package-lock.json` file has been added to the PR by mistake, please remove it.

**Comment by afalhambra** [comment]
Build is failing both locally and on CI. There is style validation failing due to the imports order, as below:

`[ERROR] src/main/java/org/kie/server/api/util/QueryParamFactory.java:[21] (imports) CustomImportOrder: Import statement for 'java.util.Arrays' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.`
`[ERROR] src/main/java/org/kie/server/api/util/QueryParamFactory.java:[22] (imports) CustomImportOrder: Import statement for 'java.util.Collections' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.`
`[ERROR] src/main/java/org/kie/server/api/util/QueryParamFactory.java:[23] (imports) CustomImportOrder: Import statement for 'java.util.List' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.`
`[ERROR] src/main/java/org/kie/server/api/util/QueryParamFactory.java:[24] (imports) CustomImportOrder: Import statement for 'java.util.stream.Collectors' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.`
`[ERROR] src/main/java/org/kie/server/api/util/QueryParamFactory.java:[26] (imports) CustomImportOrder: Import statement for 'org.kie.server.api.model.definition.QueryParam' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.`

**Comment by afalhambra** [comment]
Jenkins retest this

**Review by afalhambra — APPROVED** [review]
Just wait for CI to go green

**Comment by elguardian** [comment]
Jenkins retest this

**Pull request merged**
