### PR TITLE
DROOLS-2713 DMN eval response containing list and sublist fail on server

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @etirelli @baldimir @winklerm

### CODE REVIEW

**Comment by etirelli** [comment]
@tarilabs changes look good, I am just not sure: when is the key of a map not a string?

**Comment by tarilabs** [comment]
> when is the key of a map not a string?

in our case never, but considering generic erasure I would have needed to force an explicit cast when is actually not needed in this code, and as-is should be sufficient in describing in a correct way how the stubbing of the result context is performed. Do you agree?

**Comment by etirelli** [comment]
Ok, thanks!

**Comment by tarilabs** [comment]
```
Test Result (12 failures / -40)
org.kie.spring.jbpm.services.JtaJbpmServicesTest.testWithPerRequestStrategy
org.kie.spring.jbpm.services.JtaJbpmServicesTest.testWithPerProcessInstanceStrategy
org.kie.spring.jbpm.services.JtaJbpmServicesTest.testWithSingletonStrategy
org.kie.spring.jbpm.services.ResourceLocalJbpmServicesTest.testWithPerRequestStrategy
org.kie.spring.jbpm.services.ResourceLocalJbpmServicesTest.testWithPerProcessInstanceStrategy
org.kie.spring.jbpm.services.ResourceLocalJbpmServicesTest.testWithSingletonStrategy
org.kie.spring.jbpm.services.TxOnMethodJtaJbpmServicesTest.testWithPerRequestStrategy
org.kie.spring.jbpm.services.TxOnMethodJtaJbpmServicesTest.testWithPerProcessInstanceStrategy
org.kie.spring.jbpm.services.TxOnMethodJtaJbpmServicesTest.testWithSingletonStrategy
org.kie.spring.jbpm.services.TxOnMethodResourceLocalJbpmServicesTest.testWithPerRequestStrategy
org.kie.spring.jbpm.services.TxOnMethodResourceLocalJbpmServicesTest.testWithPerProcessInstanceStrategy
org.kie.spring.jbpm.services.TxOnMethodResourceLocalJbpmServicesTest.testWithSingletonStrategy
```

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by mswiderski** [comment]
@tarilabs test failures are not related to your changes, they seem to indicate there is some wrong cleanup of db and thus having wrong user name/password used. will take a look into this 

let me know if you'd like to merge it (or merge it yourself)

**Comment by tarilabs** [comment]
@mswidersk ok thanks!

**Pull request merged**
