### PR TITLE
[RHPAM-1927] Fix kie-osgi/kie-itests-karaf by setting concrete versio…

### PR DESCRIPTION
**Pull request by grgrzybek**
…ns (no RELEASE) and upgrading to Karaf 4.2.3 (#1751)

(cherry picked from commit 47764f70919896d9ba1210dcecb174d3a3059303)

### CODE REVIEW

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mareknovotny** [comment]
ok to test

**Comment by pefernan** [comment]
ok to test

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by mbiarnes** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Pull request merged**
