### PR TITLE
[7.7.x] JBPM-7280: Skip removing of container info if not existing

### PR DESCRIPTION
**Pull request by sutaakar**
Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1470

### CODE REVIEW

**Comment by sutaakar** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
test failures not related

**Pull request merged**
