### PR TITLE
fixing KieServerHttpRequestTest.getWithResponseCharset test

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/989
https://github.com/kiegroup/droolsjbpm-integration/pull/1891

**Comment by mbiarnes** [comment]
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-integration-pullrequests/169/testReport/

this is the only error failing here

**Comment by mareknovotny** [comment]
ok, I got it now. There is the warning in the log:
```
2019-08-20 05:45:16,793 [qtp2042495840-15] WARN  Illegal character 0xA in state=HEADER_IN_NAME for buffer HeapByteBuffer@181a1f75[p=27,l=166,c=8192,r=139]={GET / HTTP/1.1\r\nh1: 5\r\nh2\r\n<<<User-Agent: Java/... keep-alive\r\n\r\n>>> keep-alive\r\n\r\n, ...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2019-08-20 05:45:16,796 [qtp2042495840-15] WARN  bad HTTP parsed: 400 Illegal character 0xA for HttpChannelOverHttp@64d42b6a{r=46,c=false,a=IDLE,uri=null}
```

**Comment by mareknovotny** [comment]
I am not sure why it locally works, but I found this https://github.com/eclipse/jetty.project/issues/1116 which seems as jetty had some problems with null HTTP headers, but still it is a little bit hidden for me it is showing `Illegal character 0xA` which is LF line feed in empty HTTP header

**Comment by mareknovotny** [comment]
closing as the parent PR was closed long ago

**Pull request closed without merging**
