### PR TITLE
[7.7.x] JBPM-6894 - Tests added

### PR DESCRIPTION
**Pull request by MarianMacik**
depends on kiegroup/jbpm#1188

### CODE REVIEW

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Only 3 fails now. But will try once more.

```
org.kie.karaf.itest.KieSpringMetaInfAppContextKarafIntegrationTest.testKieBase
org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest.org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest  
org.kie.server.integrationtests.jbpm.QueryInKjarIntegrationTest.org.kie.server.integrationtests.jbpm.QueryInKjarIntegrationTest
```

**Comment by MarianMacik** [comment]
Jenkins retest this

**Pull request merged**
