### PR TITLE
Use source+target=1.6 for test jars to fix JDK9 build

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
@mswiderski @mariofusco I think this could still be merged. Should be pretty save and it fixes some of the JDK9 issues.

**Comment by mswiderski** [comment]
@psiroky fine with me. Let's run build now and if it passes we merge it

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
