### PR TITLE
[DROOLS-6274] Fixing resource filtering

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @kostola @jiripetrlik

See https://issues.redhat.com/browse/DROOLS-6274

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Review by jiripetrlik — COMMENTED** [review]
@gitgabrio 
Would it be possible to add also some test with scenario which previously failed?

**Review by jiripetrlik — APPROVED** [review]

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by danielezonca** [comment]
Test failures are unrelated
```
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testInsertGetDeleteFact
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testFireAllRules
org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testNoSessionInsert
org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testJSonSessionInsert
org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testSessionInsert
org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testNoSessionInsertCustomXstream
org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testSessionGetObject
org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testGetObjects
org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testManualFireAllRules
org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testSetGlobal
org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testInsertObjectWithDeclaredFact
org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testInsertElementsWithReturnObjects
org.kie.server.integrationtests.drools.RuleTemplateIntegrationTest.org.kie.server.integrationtests.drools.RuleTemplateIntegrationTest
```

**Pull request merged**
