### PR TITLE
BXMSPROD-846: upgrade of cxf-core to 3.2.14

### PR DESCRIPTION
**Pull request by mareknovotny**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-846 

**referenced Pull Requests**: 
parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1456

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins retest this

trying another upgrade to cxf 3.3.6

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
@elguardian @gmunozfe @sutaakar @MarianMacik Any idea why these tests always times out?
Is this check properly working https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerStartupIntegrationTest.java#L67 aka https://github.com/kiegroup/droolsjbpm-integration/blob/f96fe00ca82cf7504dd2415e98a3c7a8dfde6beb/kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java#L272-L281 ?

**Review by elguardian — APPROVED** [review]

**Comment by elguardian** [comment]
failures are not related.

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
@mareknovotny The check should work properly, though the mentioned test seems quite unstable in PR checks.

**Comment by mareknovotny** [comment]
I created https://issues.redhat.com/browse/JBPM-9360 for test failures

**Comment by mareknovotny** [comment]
now completely different kie-server integration test failed :(
```
org.kie.server.integrationtests.jbpm.ContainerUpdateIntegrationTest.testUserTaskWithUpdatedContainer[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:41129/kie-server-services/services/rest/server'}]

 Error Details
Unexpected HTTP response code when requesting URI 'http://localhost:41129/kie-server-services/services/rest/server/containers/definition-project/processes/instances/2449'! Error code: 404, message: "Could not find container "definition-project""

 Stack Trace
org.kie.server.api.exception.KieServicesHttpException: Unexpected HTTP response code when requesting URI 'http://localhost:41129/kie-server-services/services/rest/server/containers/definition-project/processes/instances/2449'! Error code: 404, message: "Could not find container "definition-project""
	at org.kie.server.integrationtests.jbpm.ContainerUpdateIntegrationTest.testUserTaskWithUpdatedContainer(ContainerUpdateIntegrationTest.java:84)
```

**Pull request merged**
