### PR TITLE
[7.52.x] AF-2860: Process form renderer for Date objects doesn't submit the correct data (#2501)

### PR DESCRIPTION
**Pull request by akumar074**
(cherry picked from commit ecdc7cdab48a1f158baf60c43dbf8307f73bd0e9)

**JIRA**: 

[RHPAM-3454](https://issues.redhat.com/browse/RHPAM-3454)
[AF-2860](https://issues.redhat.com/browse/AF-2860)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jstastny-cz** [comment]
jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
@akumar074 it looks good to me, do you know what is happening with the FDB?

**Comment by akumar074** [comment]
@adrielparedes [Pipeline](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/7.52.x/job/fdb/job/droolsjbpm-integration-7.52.x.fdb/11/) is still in progess.

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Hi @adrielparedes @jstastny-cz The FDB test failure seems unrelated & artifacts are generated to test.
Thanks

**Review by jstastny-cz — APPROVED** [review]
Tested with FDB artifacts, LGTM.

**Review by adrielparedes — APPROVED** [review]

**Pull request merged**
