### PR TITLE
JBPM-6027: Advanced Search API shows error code 500 instead of 400

### PR DESCRIPTION
**Pull request by markcoble**

### CODE REVIEW

**Comment by sutaakar** [comment]
@markcoble Can you please keep formatting changes separated from actual fix? Currently I have a hard time noticing what actually changed.

**Comment by tsurdilo** [comment]
@markcoble agreeing with @sutaakar - maybe would help if you can point out what changes were done
in TaskSearchServiceIntegrationTest except formatting changes and we could go from there? thanks.

**Comment by markcoble** [comment]
@sutaakar the whole formatting seems to be an ongoing struggle.  i have had the reverse request when I submit changes without the 'agreed' upon conventions.  I  review comments come in for missing formatting as well.

**Comment by markcoble** [comment]
@sutaakar the whole formatting seems to be an ongoing struggle.  i have had the reverse request when I submit changes without the 'agreed' upon formatting conventions.  In a case like this where changes are minimal then as @tsurdilo suggested I think commenting on the changes made as part of the PR would be helpful.

For this PR the integreation test just added one test, namely _TaskSearchServiceIntegrationTest.testFindTaskWithIncompatibleTypeFilter_

Exception handling was added to TaskSearchResource.getHumanTasksWithFilters which returns a 400 for incompatible data types used in the filter data and 500 for all other.  I added the same handling to QueryDataResource.runQueryFiltered which was not part of this JIRA but also not returning correct codes.

This fix solves this specific JIRA request but raises the question of having a beter framework for handling HTTP exceptions with accurate status codes and meaningful error messages.

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by sutaakar** [comment]
@markcoble There is another test concerning this, it is ProcessSearchServiceIntegrationTest.testFindProcessWithIncompatibleTypeFilter(). Please enable it too if your fix solve the issue.

**Comment by markcoble** [comment]
Latest commit includes a similar fix to _ProcessInstanceSearchResource_ The rest are simply formatting changes.

**Comment by markcoble** [comment]
@sutaakar @tsurdilo push a few changes.  pls check and merge if it looks ok!

**Comment by sutaakar** [comment]
The fixes looks ok.

**Pull request merged**
