### PR TITLE
JBPM-7635 - Upgrade to WildFly 13

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/801

### CODE REVIEW

**Comment by mswiderski** [comment]
@sutaakar would it be possible to test this on other application servers? I tested locally on WildFly 13 and all works as expected. 

NOTE: there are still hacks included in pom.xmls to let Jenkins runs tests on WildFly 13 without changing Jenkins job configuration.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
test failures do not seem to be related.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by sutaakar** [comment]
@mswiderski Tomcat tests passed, will run it also against WAS and WLS.

**Comment by sutaakar** [comment]
WLS passed

**Comment by sutaakar** [comment]
WAS passed too

**Pull request closed without merging**
