### PR TITLE
JBPM-7344: Use Tomcat 9 for Kie server integration tests

### PR DESCRIPTION
**Pull request by sutaakar**
Tested on subset of the test suite: common, drools and jbpm. All passed.

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Test failures are not related to this PR.

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
