### PR TITLE
[JBPM-9716] Wrong bootstrap servers property in the Kafka Emitter

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9716](https://issues.redhat.com/browse/JBPM-9716)

**referenced Pull Requests**: 

* https://github.com/kiegroup/jbpm/pull/1925
* https://github.com/kiegroup/kie-docs/pull/3501

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]

**Review by fjtirado — APPROVED** [review]
I think it would be nice to use a constant rather than duplicating the value in three place, wdyt?

**Comment by gmunozfe** [comment]
> I think it would be nice to use a constant rather than duplicating the value in three place, wdyt?

You're right, thanks for bringing it up, done!

**Comment by Ginxo** [comment]
@gmunozfe  can you please rebase master?
https://issues.redhat.com/browse/BXMSPROD-1307 fixes the GA error. Thanks.

**Comment by gmunozfe** [comment]
> @gmunozfe can you please rebase master?
> https://issues.redhat.com/browse/BXMSPROD-1307 fixes the GA error. Thanks.

Done, thanks for pointing out @Ginxo

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
@mareknovotny could you merge?

**Pull request merged**
