### PR TITLE
[JBPM-9457] Fix user-task-case pom file

### PR DESCRIPTION
**Pull request by sutaakar**
Seems to contain accidentally copied code.

Signed-off-by: Karel Suta <ksuta@redhat.com>

**Thank you for submitting this pull request**

**referenced Pull Requests**:

* fixing https://github.com/kiegroup/droolsjbpm-integration/pull/2313

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Review by mareknovotny — DISMISSED** [review]
lgtm

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
@sutaakar there are similar failures in kie-server jbpm integration tests
```
[2021-01-04T11:54:00.247Z] [INFO] [talledLocalContainer] Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to org.kie.api.runtime.process.WorkItemHandler
[2021-01-04T11:54:00.247Z] [INFO] [talledLocalContainer] 	at org.jbpm.runtime.manager.impl.DefaultRegisterableItemsFactory.getWorkItemHandlersFromDescriptor(DefaultRegisterableItemsFactory.java:299)
[2021-01-04T11:54:00.247Z] [INFO] [talledLocalContainer] 	at org.jbpm.runtime.manager.impl.DefaultRegisterableItemsFactory.getWorkItemHandlers(DefaultRegisterableItemsFactory.java:92)
[2021-01-04T11:54:00.247Z] [INFO] [talledLocalContainer] 	at org.jbpm.runtime.manager.impl.KModuleRegisterableItemsFactory.getWorkItemHandlers(KModuleRegisterableItemsFactory.java:103)
[2021-01-04T11:54:00.247Z] [INFO] [talledLocalContainer] 	at org.jbpm.runtime.manager.impl.AbstractRuntimeManager.registerItems(AbstractRuntimeManager.java:150)
[2021-01-04T11:54:00.247Z] [INFO] [talledLocalContainer] 	at org.jbpm.runtime.manager.impl.SingletonRuntimeManager.init(SingletonRuntimeManager.java:132)
[2021-01-04T11:54:00.247Z] [INFO] [talledLocalContainer] 	... 80 more
```

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
@mareknovotny that error is possibly related to negative functional test checking what happen when broken container is deployed.

**Review by elguardian — APPROVED** [review]
this is ok as dependencies for test kjars are coming already in the IT test

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
