### PR TITLE
[JBPM-8864] Move KieServerContainerListFilteringIntegrationTest to the jbpm test …

### PR DESCRIPTION
**Pull request by sutaakar**
…module

KieServerContainerListFilteringIntegrationTest needs to be adjusted to fail while initializing extension.
Previous approach with providing non existing kjar version cannot be used any more as latest fixes will differentiate between deployment failure caused by missing artifacts in Maven repository (container won't be deployed) and extension failures (container will be deployed with failed state).

@elguardian This PR should fix test issues related to https://github.com/kiegroup/droolsjbpm-integration/pull/1950

### CODE REVIEW

**Comment by elguardian** [comment]
that is already in the PR 
https://github.com/kiegroup/droolsjbpm-integration/pull/1950/files#diff-0e79059cbd4485c2b2f0c0d373c3fac6R81
It was working within eclipse but for some reason failing outside. :S I will check this

**Comment by sutaakar** [comment]
It doesn't work in common test module as the jBPM extension is disabled by default there, see https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml#L314

**Comment by elguardian** [comment]
I will moved it ir requires less changes in the code to make it work, 
I need to change some of the tests anyway.

**Comment by elguardian** [comment]
did you approach.

**Pull request closed without merging**
