### PR TITLE
Fix CaseQueryResource.getCaseInstances API description typo

### PR DESCRIPTION
**Pull request by ron-murhammer**
Fix CaseQueryResource.getCaseInstances API description typo

### CODE REVIEW

**Comment by mswiderski** [comment]
@ron-murhammer can we please combine all of these description fixes into single PR?

**Comment by ron-murhammer** [comment]
@mswiderski I can though its much easier to just submit a PR as I find them. Otherwise there's a good chance I forget about them.

**Comment by mswiderski** [comment]
It is. Now each of the PR needs to be executed by Jenkins with all tests which takes both resources and time. Plus in case we should back port them we have to do many and thus increase chance to forget about one etc. so I would really appreciate combining them to one

**Comment by ron-murhammer** [comment]
@mswiderski Ok, I'll try to merge them all together later today.

**Pull request closed without merging**
