### PR TITLE
JBPM-8362 - KIE Server client does not reuse marshaller for JMS

### PR DESCRIPTION
**Pull request by MarianMacik**

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Only kie karaf tests have failed. Retesting.

jenkins retest this

**Comment by MarianMacik** [comment]
2 failed tests are unrelated and should be fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/1777

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
@sutaakar any comments?

**Comment by sutaakar** [comment]
Looks good to me.

**Pull request merged**
