### PR TITLE
RHPAM-479 - WebSocket controller client method scan now not working

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mswiderski builds on master keep failing, not sure if you're aware or had the time to investigate...

**Comment by mswiderski** [comment]
@cristianonicolai build of integration repo or? I am not aware... will investigate in a bit but any details are welcome to speed this up

**Comment by cristianonicolai** [comment]
@mswiderski take a look at the build of this PR as an example... many tests failing in the droolsjbpm-integration module, I believe most are integration tests. Although build failures are consistent, it seems that tests itself are randomly failing.

**Comment by mswiderski** [comment]
go ahead and merge, I will be looking into master test failures later today anyway

**Comment by cristianonicolai** [comment]
@mswiderski ok thanks.

**Pull request merged**
