### PR TITLE
(GSS) [7.11.1] [RHPAM-3584] Add task description mapping

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

**JIRA**: 

[https://issues.redhat.com/browse/RHPAM-3584](https://issues.redhat.com/browse/RHPAM-3584)

**referenced Pull Requests**: 

* https://github.com/kiegroup/jbpm/pull/1913
* https://github.com/kiegroup/droolsjbpm-integration/pull/2440 (cherry-pick)

backport for 7.52.x

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by ruromero** [comment]
jenkins retest this please

**Comment by ruromero** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
@ruromero  can you have a look why the linux PR is failing ?

**Comment by ruromero** [comment]
I am not very familiar with the whole CI process but it looks like a timeout during the execution 
```
[2021-04-13T18:19:34.433Z] Cannot contact kie-psi-rhel7-xlarge-xmem-2160: java.lang.InterruptedException
[2021-04-13T21:40:40.366Z] Cancelling nested steps due to timeout
```

**Comment by ruromero** [comment]
jenkins retest this

**Comment by lazarotti** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
Except these failures (fix should be in https://github.com/kiegroup/droolsjbpm-integration/pull/2459)
- org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testInsertGetDeleteFact
- org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testFireAllRules
- org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testNoSessionInsert
- org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testJSonSessionInsert
- org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testSessionInsert
- org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testNoSessionInsertCustomXstream
- org.kie.camel.embedded.camel.component.CamelEndpointWithMarshallersTest.testSessionGetObject
- org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testGetObjects
- org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testManualFireAllRules
- org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testSetGlobal
- org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testInsertObjectWithDeclaredFact
- org.kie.camel.embedded.camel.component.XStreamBatchExecutionTest.testInsertElementsWithReturnObjects

  
There is this one failing: 

- org.kie.server.integrationtests.drools.RuleTemplateIntegrationTest.org.kie.server.integrationtests.drools.RuleTemplateIntegrationTest

**Comment by ruromero** [comment]
@mareknovotny I don't see how this test is somewhat related to this changes. The build logs are not giving any hint.
Can we wait till this PR you mentioned is green and/or merged?

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
`org.kie.server.integrationtests.drools.RuleTemplateIntegrationTest.org.kie.server.integrationtests.drools.RuleTemplateIntegrationTest` does not seem to be related with this PR.

Retriggering CI build

**Comment by afalhambra** [comment]
@mareknovotny @ruromero - please have a look at a different PR I have already opened

https://github.com/kiegroup/jbpm/pull/1844

It's failing with exactly the same test cases failures.

**Comment by mareknovotny** [comment]
who will fix the failures? Please report the issues for failures and try to find responsible person who will fix them ASAP

**Comment by elguardian** [comment]
@mareknovotny https://github.com/kiegroup/droolsjbpm-integration/pull/2459

**Comment by elguardian** [comment]
jenkins retest this

**Comment by afalhambra** [comment]
failure tests are not related

**Comment by lazarotti** [comment]
The prs https://github.com/kiegroup/droolsjbpm-integration/pull/2463 and https://github.com/kiegroup/kie-soup/pull/196 are still opened. Just pinged Drools team.

**Comment by lazarotti** [comment]
jenkins retest this

**Pull request merged**
