### PR TITLE
BXMSPROD-685: upgrade org.jboss.logging

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1219
https://github.com/kiegroup/droolsjbpm-integration/pull/2039

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Pull request merged**
