### PR TITLE
[7.59.x][JBPM-10012] - Right Springboot version should be 2.3.10

### PR DESCRIPTION
**Pull request by afalhambra**
**[JBPM-10012](https://issues.redhat.com/browse/JBPM-10012)**: Right Springboot version should be 2.3.10

depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1886

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1886

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Review by gmunozfe — APPROVED** [review]
Looks good to me, good catch @afalhambra !

**Comment by mareknovotny** [comment]
there is an enforcer error violation
```
[2022-02-04T12:20:52.092Z] [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
[2022-02-04T12:20:52.092Z] Duplicate classes found:
[2022-02-04T12:20:52.092Z] 
[2022-02-04T12:20:52.092Z]   Found in:
[2022-02-04T12:20:52.092Z]     org.apache.geronimo.specs:geronimo-jms_2.0_spec:jar:1.0-alpha-2:compile
[2022-02-04T12:20:52.092Z]     jakarta.jms:jakarta.jms-api:jar:2.0.3:compile
[2022-02-04T12:20:52.092Z]   Duplicate classes:
[2022-02-04T12:20:52.092Z]     javax/jms/QueueConnection.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageNotReadableException.class
[2022-02-04T12:20:52.092Z]     javax/jms/XAJMSContext.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSDestinationDefinitions.class
[2022-02-04T12:20:52.092Z]     javax/jms/InvalidDestinationRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/ObjectMessage.class
[2022-02-04T12:20:52.092Z]     javax/jms/TopicRequestor.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSException.class
[2022-02-04T12:20:52.092Z]     javax/jms/InvalidSelectorException.class
[2022-02-04T12:20:52.092Z]     javax/jms/Message.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSConnectionFactoryDefinition.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSSecurityException.class
[2022-02-04T12:20:52.092Z]     javax/jms/IllegalStateRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/ServerSessionPool.class
[2022-02-04T12:20:52.092Z]     javax/jms/Topic.class
[2022-02-04T12:20:52.092Z]     javax/jms/ConnectionFactory.class
[2022-02-04T12:20:52.092Z]     javax/jms/ConnectionMetaData.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageListener.class
[2022-02-04T12:20:52.092Z]     javax/jms/XAConnectionFactory.class
[2022-02-04T12:20:52.092Z]     javax/jms/Destination.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSConnectionFactoryDefinitions.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageConsumer.class
[2022-02-04T12:20:52.092Z]     javax/jms/QueueRequestor.class
[2022-02-04T12:20:52.092Z]     javax/jms/QueueBrowser.class
[2022-02-04T12:20:52.092Z]     javax/jms/CompletionListener.class
[2022-02-04T12:20:52.092Z]     javax/jms/XASession.class
[2022-02-04T12:20:52.092Z]     javax/jms/IllegalStateException.class
[2022-02-04T12:20:52.092Z]     javax/jms/TransactionInProgressException.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageFormatRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSContext.class
[2022-02-04T12:20:52.092Z]     javax/jms/InvalidSelectorRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/ResourceAllocationException.class
[2022-02-04T12:20:52.092Z]     javax/jms/XATopicConnectionFactory.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSConnectionFactory.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSPasswordCredential.class
[2022-02-04T12:20:52.092Z]     javax/jms/StreamMessage.class
[2022-02-04T12:20:52.092Z]     javax/jms/Queue.class
[2022-02-04T12:20:52.092Z]     javax/jms/ResourceAllocationRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSDestinationDefinition.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageNotWriteableException.class
[2022-02-04T12:20:52.092Z]     javax/jms/DeliveryMode.class
[2022-02-04T12:20:52.092Z]     javax/jms/TopicConnection.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageFormatException.class
[2022-02-04T12:20:52.092Z]     javax/jms/XAQueueConnection.class
[2022-02-04T12:20:52.092Z]     javax/jms/XAConnection.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageProducer.class
[2022-02-04T12:20:52.092Z]     javax/jms/TemporaryQueue.class
[2022-02-04T12:20:52.092Z]     javax/jms/TopicConnectionFactory.class
[2022-02-04T12:20:52.092Z]     javax/jms/XAQueueSession.class
[2022-02-04T12:20:52.092Z]     javax/jms/InvalidClientIDException.class
[2022-02-04T12:20:52.092Z]     javax/jms/BytesMessage.class
[2022-02-04T12:20:52.092Z]     javax/jms/QueueSender.class
[2022-02-04T12:20:52.092Z]     javax/jms/TransactionRolledBackException.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSSessionMode.class
[2022-02-04T12:20:52.092Z]     javax/jms/Connection.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageEOFException.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/ExceptionListener.class
[2022-02-04T12:20:52.092Z]     javax/jms/ConnectionConsumer.class
[2022-02-04T12:20:52.092Z]     javax/jms/ServerSession.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSSecurityRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/MessageNotWriteableRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/QueueSession.class
[2022-02-04T12:20:52.092Z]     javax/jms/TemporaryTopic.class
[2022-02-04T12:20:52.092Z]     javax/jms/TopicPublisher.class
[2022-02-04T12:20:52.092Z]     javax/jms/XAQueueConnectionFactory.class
[2022-02-04T12:20:52.092Z]     javax/jms/QueueReceiver.class
[2022-02-04T12:20:52.092Z]     javax/jms/MapMessage.class
[2022-02-04T12:20:52.092Z]     javax/jms/InvalidClientIDRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/TransactionRolledBackRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/Session.class
[2022-02-04T12:20:52.092Z]     javax/jms/TextMessage.class
[2022-02-04T12:20:52.092Z]     javax/jms/TopicSession.class
[2022-02-04T12:20:52.092Z]     javax/jms/TopicSubscriber.class
[2022-02-04T12:20:52.092Z]     javax/jms/InvalidDestinationException.class
[2022-02-04T12:20:52.092Z]     javax/jms/TransactionInProgressRuntimeException.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSProducer.class
[2022-02-04T12:20:52.092Z]     javax/jms/JMSConsumer.class
[2022-02-04T12:20:52.092Z]     javax/jms/QueueConnectionFactory.class
[2022-02-04T12:20:52.092Z]     javax/jms/XATopicConnection.class
[2022-02-04T12:20:52.092Z]     javax/jms/XATopicSession.class
[2022-02-04T12:20:52.092Z] 
```
please check and exclude duplicated dependency if possible

**Review by mareknovotny — CHANGES_REQUESTED** [review]
please fix the enforcer error

**Comment by afalhambra** [comment]
> please fix the enforcer error

thanks @mareknovotny - checking

**Comment by gmunozfe** [comment]
Looks the same as @VaniHaripriya fixed on main branch when bumped to 2.4.9
https://github.com/kiegroup/droolsjbpm-integration/commit/70ea9f875d8cfa19f31fc4f7ef6f238b4fd1fd4f

**Comment by afalhambra** [comment]
@mareknovotny ready to merge

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
