### PR TITLE
[JBPM-5215] Reuse deployment descriptor classes from common jBPM module

### PR DESCRIPTION
**Pull request by elguardian**
reimport the kie-internal api

### CODE REVIEW

**Comment by elguardian** [comment]
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/341

**Comment by elguardian** [comment]
ok to test

**Comment by elguardian** [comment]
ok to test

**Comment by elguardian** [comment]
@MarianMacik I could not go through all because jbpm wasn't compiling the other day. Also there is some problem with cases tests and something regarding osgi. I need to check this.

**Comment by mswiderski** [comment]
@elguardian case related tests should be fixed by 
https://github.com/kiegroup/droolsjbpm-integration/commit/f8a14b021e474ab271e4acb87cd72cc958c72ee9

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
