### PR TITLE
[DROOLS-5195] remove no longer supported integration modules

### PR DESCRIPTION
**Pull request by mariofusco**
parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1301

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
the ci says droolsjbpm-brms-distribution and droolsjbpm-bpms-distribution modules don't exist !?
These modules should not be removed as they are used in droolsjbpm-tools and in final assemblies too I believe @mariofusco

**Comment by mariofusco** [comment]
Jenkins retest this please

**Comment by mariofusco** [comment]
jenkins test

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Pull request merged**
