### PR TITLE
[7.7.x] RHPAM-1149 - Synchronization issue for concurrent registrations in Sm…

### PR DESCRIPTION
**Pull request by mswiderski**
…art router (#1492)

@sutaakar are is the back port for 7.7.x

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
test failures not related

**Pull request merged**
