### PR TITLE
[JBPM-9906] Stabilize JSONMarshallerTest in windows

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9906](https://issues.redhat.com/browse/JBPM-9906)

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins retest this

**Review by afalhambra — APPROVED** [review]
Amazing work, thanks @gmunozfe

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
@mareknovotny ready to merge

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
