### PR TITLE
PLANNER-2055: When a dinamic task with actors = null is added to a case the task assigning query looks to produce a null pointer exception

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
failing tests are not related, will relaunch the build when they are fixed since it looks like there's an email thread about them.

org.kie.server.integrationtests.controller.RestKieControllerManagementIntegrationTest.testUpdateContainerConfigSent[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:40923/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.RestKieControllerManagementIntegrationTest.testUpdateContainerConfigSent[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:40923/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerManagementIntegrationTest.testUpdateContainerConfigSent[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:40923/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStartAndStopScanner[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:40923/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testScanNow[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:40923/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.rest.JbpmRestIntegrationTest.testKieModuleMetaDataGetProcesses[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35857/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.rest.JbpmRestIntegrationTest.testKieModuleMetaDataGetProcesses[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35857/kie-server-services/services/rest/server'}]

**Comment by wmedvede** [comment]
Hi @rsynek would you mind review this PR?
Thanks!

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
Nice, 
I get an error while trying to see what the error was 

HTTP ERROR 404
Problem accessing /job/KIE/job/master/job/pullrequest/job/new-PR-droolsjbpm-integration-master.pullrequests/75/. Reason:

    Not Found

**Comment by wmedvede** [comment]
not possible to see the error

HTTP ERROR 404
Problem accessing /job/KIE/job/master/job/pullrequest/job/test-new-PR-droolsjbpm-integration-master.pullrequests/3/. Reason:

    Not Found

**Comment by rsynek** [comment]
@wmedvede Either the build number is incorrect or there have been quite many PRs recently. The build history has been reduced to the 10 last builds, maybe that's the issue.

**Comment by rsynek** [comment]
jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by wmedvede** [comment]
> @wmedvede Either the build number is incorrect or there have been quite many PRs recently. The build history has been reduced to the 10 last builds, maybe that's the issue.

This PR has only been executed 2 times, so I don't believe the history maximum has been reached. Unless this history maximum is per repository.

On the other hand, the build number si something automatically set at some point, so, if it was set wrong it looks like a bug somewere in the scripts

**Comment by wmedvede** [comment]
This time the failing tests are the ones below, again completely unrelated with this test.

Considering that the change passed their own tests all the times, and is completely safe, and we have spent 2 days trying to get a green that likely will never be produced I believe we should merge this.

FYI @ge0ffrey , @rsynek  

Test Result (3 failures / +3)
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStartAndStopScanner[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35724/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testScanNow[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35724/kie-server-services/services/rest/server'}]

**Comment by rsynek** [comment]
@wmedvede I fully agree. Would you do me a favor? Please mark the 3 failing tests with @Ignore and file Jiras about them (1 for HACEP, 1 for the WebSocket). These randomly failing tests most stop hurting us.

**Comment by wmedvede** [comment]
> @wmedvede I fully agree. Would you do me a favor? Please mark the 3 failing tests with @ignore and file Jiras about them (1 for HACEP, 1 for the WebSocket). These randomly failing tests most stop hurting us.

Hello @desmax74 , would you mind have a look and mark this test to be @Ignored if proceed?

org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest

**Comment by wmedvede** [comment]
spin off PR -> https://github.com/kiegroup/droolsjbpm-integration/pull/2161

org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStartAndStopScanner
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testScanNow

**Comment by rsynek** [comment]
@wmedvede thanks, merging.

**Pull request merged**
