### PR TITLE
[JBPM-8700] Not able to enable swagger documentation when using spring-boot-kieserver

### PR DESCRIPTION
**Pull request by elguardian**
setting to true RunAsFilter so resources can be loaded properly

### CODE REVIEW

**Comment by elguardian** [comment]
@mswiderski related to swagger documentation

**Comment by MarianMacik** [comment]
jenkins execute springboot build

**Comment by MarianMacik** [comment]
jenkins execute springboot build

**Comment by MarianMacik** [comment]
Spring Boot is now OK. 2 failed tests are completely unrelated and their fix is coming.

**Comment by elguardian** [comment]
@MarianMacik @mswiderski  this is targgeting 7.5 any thing stopping from being merge ?

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins execute springboot build

**Pull request merged**
