### PR TITLE
[JBPM-8765] Swagger points to wrong URL for Business application

### PR DESCRIPTION
**Pull request by elguardian**
using the cxf path as a base for swagger feature. this matches the documentation.

### CODE REVIEW

**Comment by elguardian** [comment]
@sutaakar can you check this one ?

**Comment by elguardian** [comment]
failed test not relevant

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
@MarianMacik any progress with this one ?

**Comment by MarianMacik** [comment]
jenkins retest this

and then I will merge :)

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Pull request merged**
