### PR TITLE
fixed enforcer rule ban-duplicated-classes for wildfly-elytron, which…

### PR DESCRIPTION
**Pull request by mareknovotny**
… is shaded jar

### CODE REVIEW

**Comment by elguardian** [comment]
waiting for CI build

**Comment by mareknovotny** [comment]
just fyi https://issues.redhat.com/browse/ELY-1971 in future we need to migrate that wildfly-elytron dependency

**Comment by mareknovotny** [comment]
so the failure are the same like in https://github.com/kiegroup/droolsjbpm-integration/pull/2098 PR run plus there is timed out one 
@elguardian we need someone to fix them. This change doesn'ŧ change the tests itself, just Enforcer rule ignores wildfly-elytron.

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
failures unrelated 
https://github.com/kiegroup/droolsjbpm-integration/pull/2100

**Comment by elguardian** [comment]
@mareknovotny  I am merging. You won't get a clean run.

**Comment by mareknovotny** [comment]
ok, are those failures on master then?

**Pull request merged**
