### PR TITLE
JBPM-9185; Exclude UserTaskServiceIntegrationTest failing on jenkins

### PR DESCRIPTION
**Pull request by jomarko**
The details about failing can be found in: https://issues.redhat.com/browse/JBPM-9158

### CODE REVIEW

**Comment by mareknovotny** [comment]
@jomarko there is already fix merged https://github.com/kiegroup/jbpm/pull/1647

**Comment by mareknovotny** [comment]
and followup PR here is opened too https://github.com/kiegroup/droolsjbpm-integration/pull/2086

**Comment by jomarko** [comment]
@mareknovotny thank you for pointers and sorry for inconvenience and additional work needed to review this PR.

**Comment by mareknovotny** [comment]
np at all, both you and @gmunozfe worked on it in parallel

**Pull request closed without merging**
