### PR TITLE
RHBPMS-4760: Task Subforms retrieved by Kie Server Rest API is missing subform fields

### PR DESCRIPTION
**Pull request by pefernan**
@mswiderski @jsoltes could you take a look?

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@pefernan was the problem with insert vs replace node or was there something else?

**Comment by pefernan** [comment]
@mswiderski there was two problems:
-When filtering the SubForm & MultipleSubForm fields weren't added to the xml because of the if-else braces
-Second issue I found is that on MultipleSubforms the defaultForm was added 2 times to the XML (first time when processing inputs & 2nd time when processing outputs)

**Comment by pefernan** [comment]
@mswiderski yes testing it right now

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes better now?

**Pull request merged**
