### PR TITLE
AF-2880 : Support Elytron in Business Central

### PR DESCRIPTION
**Pull request by Rikkola**
**Thank you for submitting this pull request**

**JIRA**: 

[AF-2880](https://issues.redhat.com/browse/AF-2880)

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1723
* https://github.com/kiegroup/droolsjbpm-integration/pull/2559
* https://github.com/kiegroup/kie-soup/pull/220
* https://github.com/kiegroup/appformer/pull/1182
* https://github.com/kiegroup/drools-wb/pull/1519
* https://github.com/kiegroup/jbpm-wb/pull/1511
* https://github.com/kiegroup/kie-wb-distributions/pull/1121

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
```
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest
org.kie.server.springboot.samples.KeycloakKieServerTest.org.kie.server.springboot.samples.KeycloakKieServerTest
```

Jenkins retest this

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
except `org.kie.server.springboot.samples.KeycloakKieServerTest.org.kie.server.springboot.samples.KeycloakKieServerTest` all other tests look flaky or fixed by #2593 for `org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest`.
Is `org.kie.server.springboot.samples.KeycloakKieServerTest.org.kie.server.springboot.samples.KeycloakKieServerTest` related to elytron change? `java.lang.ClassNotFoundException: org.wildfly.client.config.ConfigXMLParseException`

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins run cdb

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins run cdb

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins run cdb

**Comment by mareknovotny** [comment]
there are 33 failures in kie-server and in karaf IT tests, any idea why this fails @sutaakar @jiripetrlik ?

**Comment by sutaakar** [comment]
The `FileRepositoryTest` looks like intermittent issue, I wasn't able to reproduce it locally.

**Comment by sutaakar** [comment]
The `KeycloakKieServerTest` failure may be related, but I am not much familiar with that test, @gmunozfe may know better.

**Comment by Rikkola** [comment]
`KeycloakKieServerTest` could break due to this.

**Comment by mbiarnes** [comment]
Jenkins run cdb

**Review by tomasdavidorg — APPROVED** [review]

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Test failures related to kie-server and jbpm need an update, on that now.

**Comment by Rikkola** [comment]
And it looks like I will still need Monday to fix this. The problem is I will need to add an Elytron option for `UserDataServiceProvider`.

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
@mariofusco  @ge0ffrey compiler error in Optaplanner due this change https://github.com/kiegroup/drools/commit/7a08551605f7b2483ecdb550a698acf3b29f4623?
```
[2021-09-30T16:26:04.528Z] [INFO] 100 warnings 
[2021-09-30T16:26:04.528Z] [INFO] -------------------------------------------------------------
[2021-09-30T16:26:04.528Z] [INFO] -------------------------------------------------------------
[2021-09-30T16:26:04.528Z] [ERROR] COMPILATION ERROR : 
[2021-09-30T16:26:04.528Z] [INFO] -------------------------------------------------------------
[2021-09-30T16:26:04.528Z] [ERROR] /home/jenkins/workspace/KIE/main/pullrequest/droolsjbpm-integration-main.pr/bc/kiegroup_optaplanner/optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsKieVfsUrlType.java:[83,39] cannot find symbol
[2021-09-30T16:26:04.528Z]   symbol:   method toPortableString()
[2021-09-30T16:26:04.528Z]   location: class org.kie.memorycompiler.resources.KiePath
[2021-09-30T16:26:04.528Z] [ERROR] /home/jenkins/workspace/KIE/main/pullrequest/droolsjbpm-integration-main.pr/bc/kiegroup_optaplanner/optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsKieVfsUrlType.java:[136,37] cannot find symbol
[2021-09-30T16:26:04.528Z]   symbol:   method toPortableString()
[2021-09-30T16:26:04.528Z]   location: class org.kie.memorycompiler.resources.KiePath
[2021-09-30T16:26:04.528Z] [INFO] 2 errors 
[2021-09-30T16:26:04.528Z] [INFO] ---------
```

**Comment by mareknovotny** [comment]
jenins retest this please

- org.kie.wb.test.rest.functional.ProjectIntegrationTest.testDeployProjectSnapshotTwice
- org.kie.wb.test.rest.security.HealthCheckServiceIntegrationTest.org.kie.wb.test.rest.security.HealthCheckServiceIntegrationTest

**Pull request merged**
