### PR TITLE
[DROOLS-6566] Upgrade to Karaf 4.3.2 and fix all (but 3) integration …

### PR DESCRIPTION
**Pull request by grgrzybek**
…tests ...

The changes can be summarized:
* there's special kie-osgi-servlet3-compatibility bundle fragment
  provided to handle Servlet API 3/4 OSGi problems
* I've changed dbcp to dbcp2 in "h2" feature to be able to set proper
  ClassLoader to load H2 driver
* droolsjbpm-hibernate no longer needs to "wrap:" hibernate bundles -
  Entity classes should *always* be loaded from the EMF bundle and
  required imports are added in
  KieBlueprintjBPMPersistenceKarafIntegrationTest#getDefaultOptions()
* I've copied changed version of Taskorm.xml from JBPM to reflect model
  changes
* OsgiKieModule can now deal with changed bundle: URI from Felix 6 (OSGi
  Core R7)

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
ok to test

**Review by jiripetrlik — APPROVED** [review]
@grgrzybek 
Thank you! Looks good to me.

**Comment by grgrzybek** [comment]
The build failures are expected before kiegroup/jbpm#2007 is merged

**Comment by mareknovotny** [comment]
@grgrzybek our CI can take both repository PRs if you called the branch the same and i can see you did that. So CI should be green.

**Comment by grgrzybek** [comment]
@mareknovotny so I'll check the failing tests (worked for me, so may be flaky) on Monday (after my 3-day PTO), ok?

**Comment by tkobayas** [comment]
Most (or all) of failures should be fixed by https://github.com/kiegroup/drools/commit/ff579b546e5b196ffbe4a29e957d97e9c9f2e618
```
[2021-09-01T10:34:32.240Z] [INFO] [talledLocalContainer] Caused by: org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
[2021-09-01T10:34:32.240Z] [INFO] [talledLocalContainer]        at org.apache.xerces.jaxp.validation.ValidatorImpl.setProperty(ValidatorImpl.java:283)
[2021-09-01T10:34:32.240Z] [INFO] [talledLocalContainer]        at org.drools.compiler.kproject.models.KieModuleMarshaller$KieModuleValidator.validate(KieModuleMarshaller.java:191)
[2021-09-01T10:34:32.240Z] [INFO] [talledLocalContainer]        ... 90 more
```
Will re-run the test.

**Comment by tkobayas** [comment]
Jenkins retest this

**Review by mariofusco — APPROVED** [review]

**Review by tkobayas — APPROVED** [review]
Thanks!

**Comment by tkobayas** [comment]
Linux - Pull Request — Build finished. 6731 tests run, 82 skipped, 0 failed.
https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/droolsjbpm-integration-main.pr/168/

keycloak-kie-server-spring-boot-sample test failed.
```
[2021-09-02T07:24:27.108Z] [INFO] Running org.kie.server.springboot.samples.KeycloakKieServerTest
...
[2021-09-02T08:30:47.519Z] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

but kie-karaf-itests were successful.
```
[2021-09-02T06:51:59.665Z] [INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ kie-karaf-itests ---
[2021-09-02T06:51:59.665Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/main/pullrequest/droolsjbpm-integration-main.pr/bc/kiegroup_droolsjbpm_integration/kie-osgi/kie-karaf-itests/target/failsafe-reports
...
[2021-09-02T07:00:41.728Z] [INFO] Results:
[2021-09-02T07:00:41.728Z] [INFO]
[2021-09-02T07:00:41.728Z] [WARNING] Tests run: 60, Failures: 0, Errors: 0, Skipped: 3
```
I think tests are basically okay but re-run just in case.

**Comment by tkobayas** [comment]
Jenkins retest this

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
