### PR TITLE
[JBPM-9573] Keycloak image not found in tests

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9573](https://issues.redhat.com/browse/JBPM-9573)

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Review by afalhambra — APPROVED** [review]
Good one!

**Comment by gmunozfe** [comment]
@mareknovotny @elguardian ready to merge

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
