### PR TITLE
JBPM-6196: Define Tomcat datasource with Cargo

### PR DESCRIPTION
**Pull request by sutaakar**

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
build is green on tomcat as well, see https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/master/job/narayana-droolsjbpm-integration/6/

ready to be merged, @sutaakar anything else to add?

**Comment by sutaakar** [comment]
@mswiderski Nothing to add, ready to be merged

**Comment by sutaakar** [comment]
Removed username/password from Narayana datasource definition.

**Comment by sutaakar** [comment]
@mswiderski I guess we can merge it now. Will check all databases once merged.

**Pull request merged**
