### PR TITLE
[7.59.x] [RHPAM-4201] Add httpcore-osgi bundle to kie-server-client features

### PR DESCRIPTION
**Pull request by grgrzybek**
**Thank you for submitting this pull request**

**JIRA**:

[RHPAM-4201](https://issues.redhat.com/browse/RHPAM-4201)

### CODE REVIEW

**Review by tkobayas — APPROVED** [review]

**Comment by tkobayas** [comment]
Hi @mareknovotny @mariofusco  Could you approve running workflows? Thanks!

**Comment by mareknovotny** [comment]
@tkobayas i think even you can comment with "ok to test" to approve at least Jenkins CI.

**Comment by mareknovotny** [comment]
please prepare also PR for main branch.

**Comment by jiripetrlik** [comment]
@mareknovotny 
Actually this is cherry-pick from https://github.com/kiegroup/droolsjbpm-integration/pull/2718 which is already on main.

**Comment by mariofusco** [comment]
Failure in `org.kie.server.springboot.samples.KeycloakKieServerTest.org.kie.server.springboot.samples.KeycloakKieServerTest` is not related, merging.

**Pull request merged**
