### PR TITLE
RHDM-251 - Wildfly 11 upgrade

### PR DESCRIPTION
**Pull request by mareknovotny**
another round of reverted PR - https://github.com/kiegroup/droolsjbpm-integration/pull/1348

### CODE REVIEW

**Comment by sutaakar** [comment]
@mareknovotny Can this be merged?

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
@sutaakar I need to let others to merge all PR set.

**Comment by mbarkley** [comment]
Note that the failing test in this PR has also recently failed on master.

**Pull request merged**
