### PR TITLE
[7.67.x-blue][RHPAM-4688] Exclude sshd-common from wildfly-eletron

### PR DESCRIPTION
**Pull request by lampajr**
**Thank you for submitting this pull request**

**JIRA**: 
- https://issues.redhat.com/browse/RHPAM-4688

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by lampajr** [comment]
GHA is failing during java and maven setup:
```
2023-05-17T08:28:28.0285059Z downloading https://archive.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
2023-05-17T08:29:48.1013625Z ##[error]read ECONNRESET
```

**Comment by lampajr** [comment]
Jenkins retest this

**Comment by lampajr** [comment]
Some tests failures:
```
[2023-05-17T08:59:51.262Z] [INFO] [talledLocalContainer] 04:59:50,185 ERROR [org.kie.server.services.jbpm.JbpmKieServerExtension] (Thread-2 (ActiveMQ-client-global-threads)) Error when creating container definition-project by extension jBPM KIE Server extension: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: RuntimeManager with id definition-project is already active
...
[2023-05-17T08:59:55.928Z] [ERROR] Tests run: 6, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 31.102 s <<< FAILURE! - in org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest
[2023-05-17T08:59:55.928Z] [ERROR] testDeployedBrokenProjectFixAndRedeploy[JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:33014/kie-server-services/services/rest/server'}](org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest)  Time elapsed: 4.659 s  <<< FAILURE!
[2023-05-17T08:59:55.928Z] org.junit.ComparisonFailure: [Message should be of type info] expected:<[INFO]> but was:<[ERROR]>
[2023-05-17T08:59:55.929Z]      at org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy(ContainerFailureRecoveryIntegrationTest.java:92)
[2023-05-17T08:59:55.929Z] 
[2023-05-17T08:59:55.929Z] [ERROR] testDeployedBrokenProjectFixAndRedeploy[JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:33014/kie-server-services/services/rest/server'}](org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest)  Time elapsed: 4.165 s  <<< FAILURE!
[2023-05-17T08:59:55.929Z] org.junit.ComparisonFailure: [Message should be of type info] expected:<[INFO]> but was:<[ERROR]>
[2023-05-17T08:59:55.929Z]      at org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy(ContainerFailureRecoveryIntegrationTest.java:92)
[2023-05-17T08:59:55.929Z] 
[2023-05-17T08:59:55.929Z] [ERROR] testDeployedBrokenProjectFixAndRedeploy[XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:33014/kie-server-services/services/rest/server'}](org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest)  Time elapsed: 4.176 s  <<< FAILURE!
[2023-05-17T08:59:55.929Z] org.junit.ComparisonFailure: [Message should be of type info] expected:<[INFO]> but was:<[ERROR]>
[2023-05-17T08:59:55.929Z]      at org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy(ContainerFailureRecoveryIntegrationTest.java:92)
[2023-05-17T08:59:55.929Z] 
[2023-05-17T08:59:55.929Z] [ERROR] testDeployedBrokenProjectFixAndRedeploy[JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}](org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest)  Time elapsed: 4.569 s  <<< FAILURE!
[2023-05-17T08:59:55.929Z] org.junit.ComparisonFailure: [Message should be of type info] expected:<[INFO]> but was:<[ERROR]>
[2023-05-17T08:59:55.929Z]      at org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy(ContainerFailureRecoveryIntegrationTest.java:92)
[2023-05-17T08:59:55.929Z] 
[2023-05-17T08:59:55.929Z] [ERROR] testDeployedBrokenProjectFixAndRedeploy[JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}](org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest)  Time elapsed: 4.32 s  <<< FAILURE!
[2023-05-17T08:59:55.929Z] org.junit.ComparisonFailure: [Message should be of type info] expected:<[INFO]> but was:<[ERROR]>
[2023-05-17T08:59:55.929Z]      at org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy(ContainerFailureRecoveryIntegrationTest.java:92)
[2023-05-17T08:59:55.929Z] 
[2023-05-17T08:59:55.929Z] [ERROR] testDeployedBrokenProjectFixAndRedeploy[XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}](org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest)  Time elapsed: 4.375 s  <<< FAILURE!
[2023-05-17T08:59:55.929Z] org.junit.ComparisonFailure: [Message should be of type info] expected:<[INFO]> but was:<[ERROR]>
[2023-05-17T08:59:55.929Z]      at org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy(ContainerFailureRecoveryIntegrationTest.java:92)

```

and

```
[2023-05-17T08:52:25.432Z] [ERROR] Tests run: 31, Failures: 1, Errors: 0, Skipped: 17, Time elapsed: 72.726 s <<< FAILURE! - in org.kie.server.integrationtests.jbpm.JobServiceIntegrationTest
[2023-05-17T08:52:25.432Z] [ERROR] testMessagesOfContainerUpdateContainerToBroken[XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:33014/kie-server-services/services/rest/server'}](org.kie.server.integrationtests.jbpm.ContainerUpdateIntegrationTest)  Time elapsed: 6.658 s  <<< FAILURE!
[2023-05-17T08:52:25.432Z] java.lang.AssertionError: 
[2023-05-17T08:52:25.432Z] [Shound have two messages] 
[2023-05-17T08:52:25.432Z] Expected size:<2> but was:<3> in:
[2023-05-17T08:52:25.432Z] <[org.kie.server.api.model.Message@7b1d0973,
[2023-05-17T08:52:25.432Z]     org.kie.server.api.model.Message@e7908,
[2023-05-17T08:52:25.432Z]     org.kie.server.api.model.Message@183b991c]>
[2023-05-17T08:52:25.432Z]      at org.kie.server.integrationtests.jbpm.ContainerUpdateIntegrationTest.testMessagesOfContainerUpdateContainerToBroken(ContainerUpdateIntegrationTest.java:174)

```

**Comment by lampajr** [comment]
> i got an idea to upgrade wildfly-elytron to 1.15.16.Final which is also productized in EAP 7.4.10. and do not play here with exclusions, WDYT? @lampajr

it looks good, let's try with that

**Comment by mareknovotny** [comment]
so we can close this PR as the upgrade of Wildfly-Elytron looked like better approach

**Pull request closed without merging**
