### PR TITLE
AF-1799: Upgrade JDK 11 + GWT 2.9

### PR DESCRIPTION
**Pull request by caponetto**
**Upgrade JDK 11 + GWT 2.9**

Feel free to comment and/or raise any concerns.

This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039

Thanks guys for that!

**JIRA**:

[AF-1799](https://issues.redhat.com/browse/AF-1799)

**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
Is this PR set replacing https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1442 ? @caponetto

**Comment by caponetto** [comment]
Hi @mareknovotny, 
Yes, these PRs are meant to replace all PRs associated with these ones:
- kiegroup/appformer#1030
- kiegroup/appformer#1039

Most of their changes are incorporated into the PRs I've opened.

They're still WIP though, we had to do some workarounds so the build could successfully finish on local env.

**Comment by mareknovotny** [comment]
ok, thanks @caponetto.

@porcelli @jomarko fyi, I think your PRs can be closed then

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Review by MarianMacik — APPROVED** [review]

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by tiagobento** [comment]
@cristianonicolai Hi Cristiano! Will you review this one?

**Comment by mareknovotny** [comment]
jenkins retest this please

**Review by sutaakar — APPROVED** [review]

**Comment by caponetto** [comment]
jenkins retest this

**Review by cristianonicolai — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by caponetto** [comment]
🟢

**Review by Srihari1192 — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
the github action ubuntu-latest reference was updated to ubuntu 20.04 which broke the cleaning step due change package names
https://github.com/actions/virtual-environments/issues/1816 is still open so this is weird, but @Ginxo created https://issues.redhat.com/browse/BXMSPROD-1201 to fix it temporary and later fix package names.

**Pull request merged**
