### PR TITLE
[DROOLS-4739] Support Camel integration test with the executable model

### PR DESCRIPTION
**Pull request by tkobayas**

### CODE REVIEW

**Comment by mareknovotny** [comment]
please use preferably label "DO NOT MERGE" or new feature of Github - Draft PR. This [DO-NOT-MERGE] PR title requires to change it before merging and sometimes people forget and then it is in stored in commit msg forever ;)

**Comment by tkobayas** [comment]
@mareknovotny Thank you. I'll fix my other PRs which have [DO-NOT-MERGE].

@lucamolteni @jiripetrlik Please do not review yet. This is still working in progress.

**Comment by lucamolteni** [comment]
@tkobayas sorry I reviewed it by error. I'll review it back later :)

**Comment by tkobayas** [comment]
jenkins test again

**Comment by tkobayas** [comment]
jenkins test again

**Comment by tkobayas** [comment]
The Jenkins test says "FAILURE" but actually all tests passed (The issue was at the last stage of reporting. I'll send an email about it). So please review @lucamolteni @jiripetrlik . Thanks!

**Pull request merged**
