### PR TITLE
Kie spring batch listeners test

### PR DESCRIPTION
**Pull request by winklerm**
Added reproducer for BZ 1309020.

### CODE REVIEW

**Comment by mrietveld** [comment]
@winklerm Would you mind rebasing the commits into 1 commit? 

Otherwise, +1.

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by winklerm** [comment]
@mrietveld Sure, good point! I have just made it one commit. Apologies for the late reply, I have missed the notification somehow.

**Comment by winklerm** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@winklerm is this reproducer or just additional test?

**Comment by winklerm** [comment]
@mswiderski this is a reproducer for https://bugzilla.redhat.com/show_bug.cgi?id=1309020 - quite an old one, but probably still valid - unless I have missed something regarding <kie:batch> processing.

**Comment by mswiderski** [comment]
@mariofusco could you please have a look if that should be merged or not?

**Comment by mariofusco** [comment]
Replaced and fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/1276

**Pull request closed without merging**
