### PR TITLE
JBPM-9708 Allow navigation from the parent process instance to the child process instance using Process Diagram

### PR DESCRIPTION
**Pull request by bxf12315**
… map in the SVG file which is returned by url /server/containers/{containerId}/images/processes/{processId}

-- make the PR can compatible with the old svg file

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[RHPAM-3655](https://issues.redhat.com/browse/RHPAM-3655)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by jstastny-cz** [comment]
Even though FDB failed, the artifacts are available, I can test with that.

**Review by jstastny-cz — APPROVED** [review]
I've tested with old project (before the change) and it works fine now. I've check also reproducer from @martinweiler and it works as expected too.

**Comment by jstastny-cz** [comment]
On thing to note though is that it allows navigation also for nodes, that were already executed, so the sub-process might have been already cleaned - in that case the redirect shows `"Not found"` in a blank page. Which I think is acceptable.

**Comment by bxf12315** [comment]
Jenkins retest this

**Review by romartin — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by lazarotti** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
@bxf12315 could you try to look why the 42 tests are failing. These are shown in both runs on Jenkins and on Github Actions so there are some problems in droolsjbpm-integrations repository

**Comment by bxf12315** [comment]
> @bxf12315 could you try to look why the 42 tests are failing. These are shown in both runs on Jenkins and on Github Actions so there are some problems in droolsjbpm-integrations repository

ok

**Comment by lazarotti** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by lazarotti** [comment]
@nmirasch @bxf12315 @jstastny-cz the new change related to nodeId is completely unrelated to the current Jenkins issues, can we go ahead with this merge, please?

**Comment by elguardian** [comment]
merged

**Pull request merged**
