### PR TITLE
DROOLS-6592 reproducer ONLY

### PR DESCRIPTION
**Pull request by tarilabs**
https://issues.redhat.com/browse/DROOLS-6592

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by tkobayas — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
All Failed Tests

Test Name | Duration | Age
-- | -- | --
org.kie.karaf.itest.blueprint.KieBlueprintjBPMPersistenceKarafIntegrationTest.testStartProcessEnv | 10 sec | 1
org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskCompletedBoundaryTimerProcessInstance | 10 sec | 2
org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskNotCompletedBoundaryTimerProcessInstance | 0.28 sec | 2
org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskNotCompletedBoundaryTimerProcessInstance | 0.28 sec | 2

unrelated. 🎱 

Jenkins retest this

**Comment by elguardian** [comment]
@tarilabs I am ok with the test. What I am not sure is why this is still on draft. Is there anything pending ? do you want to be merge ?

**Comment by tarilabs** [comment]
@elguardian just not sure why these continue failing:

Test Name | Duration | Age
-- | -- | --
org.kie.karaf.itest.blueprint.KieBlueprintjBPMPersistenceKarafIntegrationTest.testStartProcessEnv | 11 sec | 1
org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskCompletedBoundaryTimerProcessInstance | 10 sec | 1
org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskNotCompletedBoundaryTimerProcessInstance | 0.12 sec | 1
org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskNotCompletedBoundaryTimerProcessInstance | 0.12 sec | 1

Jenkins retest this

**Comment by tarilabs** [comment]
looping @lucamolteni @mariofusco FYI

**Review by mariofusco — APPROVED** [review]

**Review by hellowdan — APPROVED** [review]

**Review by lucamolteni — APPROVED** [review]

**Comment by tarilabs** [comment]
probably was unrelated, but log is not longer available

Jenkins retest this

**Pull request merged**
