### PR TITLE
[JBPM-9705] Able to execute process admin REST API's without valid co…

### PR DESCRIPTION
**Pull request by abhijithumbe**
…ntainerID

**Thank you for submitting this pull request**

**JIRA**: _(https://issues.redhat.com/browse/JBPM-9705)_

### CODE REVIEW

**Comment by krisv** [comment]
ok to test

**Comment by Ginxo** [comment]
@abhijithumbe  can you please rebase master?
https://issues.redhat.com/browse/BXMSPROD-1307 fixes the GA error. Thanks.

**Comment by abhijithumbe** [comment]
@Ginxo Sure will do. Thanks

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by fjtirado** [comment]
@abhijithumbe 
The problem why this JIRA i so risky are aliases, which are still not took into account. 
You can start rejecting customer request that were working using aliases. 
And issue is that I cannot find (when trying to fix this) a working alias resolver. 
Honestly, I do not understand why are we doing this.

**Pull request closed without merging**
