### PR TITLE
[RHPAM-3988] Make the kieservice client timeout value configurable in RestKieServicesClientProvider used by controller

### PR DESCRIPTION
**Pull request by ghjboss**
[link](https://issues.redhat.com/browse/RHPAM-3988)

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
Works as expected

**Review by sutaakar — APPROVED** [review]

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
thax @ghjboss  for the contribution. really appreciated !

**Pull request merged**
