### PR TITLE
[DROOLS-6853] jdk17 compatibility

### PR DESCRIPTION
**Pull request by mariofusco**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6853

Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1912
https://github.com/kiegroup/drools/pull/4261
https://github.com/kiegroup/jbpm/pull/2122
https://github.com/kiegroup/droolsjbpm-integration/pull/2736
https://github.com/kiegroup/drools-wb/pull/1541
https://github.com/kiegroup/jbpm-designer/pull/929
https://github.com/kiegroup/jbpm-wb/pull/1546
https://github.com/kiegroup/kie-wb-distributions/pull/1158

### CODE REVIEW

**Review by mareknovotny — CHANGES_REQUESTED** [review]
here the new jaxb deps are making duplicated classes conflict

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins run cdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins run cdb

**Pull request merged**
