### PR TITLE
2 EAP instances test for Fuse integration

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

**Thank you for submitting this pull request**

**JIRA**:
Related to [https://issues.redhat.com/browse/RHPAM-3128](https://issues.redhat.com/browse/RHPAM-3128)

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Review by tkobayas — CHANGES_REQUESTED** [review]
Thank you very much for the PR, @sutaakar !

Here are some additions. Please have a look at this diff:

https://gist.github.com/tkobayas/d3461b25f14a98e44dce43c98b362bb3

- Added `<single.kie.server.base.http.url>` : Profile `wildfly` uses single server instance so kie-server port is `8080`. So `pingURL` has to point at `8080`. (Without this, we need to wait until timeout) . Of course, you may change the property name if you want :)

- Parameterized kie-server port in `camel-context.xml` : `camel-context.xml` in `camel-container-tests-module` has to point at the kie-server port (for profile `eap`, `8180`. for profile `wildfly`, `8080`) so parameterized by system property `kie.server.port`.

- Changed activation property to `fuse.eap.url` : This is not mandatory but as you changed the property from `eap.url` to `fuse.eap.url`, I changed accordingly.

With the diff, I confirmed that both profile `wildfly` and `eap` run successfully on my local env. Thanks!

**Comment by sutaakar** [comment]
@tkobayas PR updated, now all the tests should pass.
Thanks for suggestions.

**Review by tkobayas — APPROVED** [review]
Thanks!

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by jiripetrlik** [comment]
@sutaakar @tkobayas 
Can you please provide an example parameters for EAP. I was not successful with following parameters: -Dfuse.eap.url=file:///tmp/fuse-eap/jboss-eap-7.2.3-full-build.zip -Dkie-server.eap.url=file:///tmp/fuse-eap/jboss-eap-7.2.3-full-build.zip -Dfuse.on.eap.url=file:///tmp/fuse-eap/fuse-eap-installer-7.5.0.fuse-750024-redhat-00002.jar -Dkie.server.war=/tmp/fuse-eap/kie-server.war -Dkie.server.port=8180

Is there something more which needs to be configured?

**Comment by jiripetrlik** [comment]
@sutaakar 
Thank you for your PR and help with figuring out which parameters use. Looks good to me.

**Review by jiripetrlik — APPROVED** [review]

**Comment by sutaakar** [comment]
@kiegroup/gatekeepers Can you please merge?

**Pull request merged**
