### PR TITLE
Fix NPE on KieSpringTransactionManager#begin

### PR DESCRIPTION
**Pull request by sibmaks**
Sometimes I have got NullPointerExceptionon this method. Actually, it looks like in try section some exception happened on transaction creation and it's suppressed by NPE.

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]
@sibmaks Thanks for your contribution, looks good to me.
Can you please share a stacktrace or create a JBPM JIRA in https://issues.redhat.com/ to be associated with this PR?

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sutaakar** [comment]
Jenkins retest this please

**Comment by sibmaks** [comment]
@sutaakar sorry for a long awaiting
```java
(serverId=92) 2020-10-06 14:28:34.588  WARN Camel (camel-1) thread #28 - Multicast KieSpringTransactionManager:begin:59 - Unable to begin transaction
java.lang.NullPointerException: null
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:703)
	at org.kie.spring.persistence.KieSpringTransactionManager.getStatus(KieSpringTransactionManager.java:142)
	at org.kie.spring.persistence.KieSpringTransactionManager.begin(KieSpringTransactionManager.java:50)
	at org.drools.persistence.PersistableRunner$TransactionInterceptor.execute(PersistableRunner.java:589)
	at org.drools.persistence.PersistableRunner$TransactionInterceptor.execute(PersistableRunner.java:565)
	at org.drools.persistence.PersistableRunner.execute(PersistableRunner.java:400)
	at org.drools.persistence.PersistableRunner.execute(PersistableRunner.java:68)
	at org.drools.core.runtime.InternalLocalRunner.execute(InternalLocalRunner.java:37)
	at org.drools.core.runtime.InternalLocalRunner.execute(InternalLocalRunner.java:41)
	at org.drools.core.command.impl.CommandBasedStatefulKnowledgeSession.getIdentifier(CommandBasedStatefulKnowledgeSession.java:134)
```

**Comment by sibmaks** [comment]
Actually, NPE happened in case of using one TM for several Kie sessions. I know, that it's wrong using, but skipped exception was ConcurrentModificationException, that more useful for understanding.

**Comment by mareknovotny** [comment]
Jenknis retest this

**Comment by mareknovotny** [comment]
Jenknis retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
@sibmaks Can you create the PR from some unique named branch? Our automation checks all the Kie upstream repositories you have cloned and use same branch to build upstream repositories (this approach is needed in case of PRs affecting multiple repositories). It seems that you have cloned some other Kie repositories and have master branch there pointing to some older commit.

**Comment by sibmaks** [comment]
@sutaakar should I rollback changes before in master?

**Comment by sutaakar** [comment]
@sibmaks sorry, I am not sure what do you mean by rolling back changes before. Just please open PR with same commit as here, only difference will be that you will use unique branch name in your fork carrying the commit.

**Comment by mareknovotny** [comment]
@sibmaks please follow our contributing rules at https://github.com/kiegroup/droolsjbpm-build-bootstrap/#working-with-git
Specifically:
1. you should create a new branch with topic matching jira id JBPM-9410
2. add into that topic branch ONLY the commit you did on your own, no rebased commits from other like you have now here 11 other commits alongside yours.

**Review by mareknovotny — CHANGES_REQUESTED** [review]
the PR contains not only the change for fixing the jira JBPM-9410

**Comment by elguardian** [comment]
commit is too long  and it seems this was superseeded by 
https://github.com/kiegroup/droolsjbpm-integration/pull/2273 
reopen if necessary

**Pull request closed without merging**
