### PR TITLE
Fixing for the response messages to have successful spelt correctly

### PR DESCRIPTION
**Pull request by timwuthenow**
Updating the response message for all API responses to have the proper spelling of successful

### CODE REVIEW

**Comment by kie-ci4** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by timwuthenow** [comment]
ok to test

**Comment by mswiderski** [comment]
ok to test

**Comment by mswiderski** [comment]
@sterobin would you mind double checking?

**Comment by timwuthenow** [comment]
Has this been merged into a release branch yet? Do I need to do the conflict resolution?

**Comment by mswiderski** [comment]
nope, it didn't. could you please resolve conflicts and I will merge it

**Comment by mareknovotny** [comment]
@timwuthenow can you rebase and fix conflicts, please?

**Comment by elguardian** [comment]
closing as out of date.

**Pull request closed without merging**
