### PR TITLE
DROOLS-6571 reproducer for EvalHelper accessorCache on kie server

### PR DESCRIPTION
**Pull request by tarilabs**
Reproducer on kie-server for DROOLS-6571

**JIRA**: https://issues.redhat.com/browse/DROOLS-6571

**referenced Pull Requests**: 

* https://github.com/kiegroup/drools/pull/3803

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
```
02:40:57  [INFO] --- cargo-maven3-plugin:1.9.3:stop (stop-container) @ kie-server-integ-tests-dmn-pmml-trusty ---
02:40:57  [INFO] [talledLocalContainer] WildFly 23.0.2.Final is stopping...
02:40:58  [INFO]  Archive artifact won't be executed
02:40:58  /home/jenkins/workspace/KIE/main/pullrequest/droolsjbpm-integration-main.pr@tmp/durable-e9b37115/script.sh: line 1:  8229 Terminated              build-chain-action -token=**** -df='https://raw.githubusercontent.com/${GROUP}/droolsjbpm-build-bootstrap/${BRANCH}/.ci/pull-request-config.yaml' -folder='bc' build pr -url=https://github.com/kiegroup/droolsjbpm-integration/pull/2584 --skipParallelCheckout -cct '(^mvn .*)||$1 -s /home/jenkins/workspace/KIE/main/pullrequest/droolsjbpm-integration-main.pr@tmp/config4787642840801968184tmp -Dmaven.wagon.http.ssl.insecure=true'
02:40:58  script returned exit code 143
```

Jenkins retest this

**Comment by tarilabs** [comment]
upstream is merged


Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
`Linux - Pull Request — Build finished. 6801 tests run, 100 skipped, 0 failed.`

with 

```
[2021-09-01T20:02:19.246Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (generate-aggregated-jacoco-report) on project droolsjbpm-integration: An Ant BuildException has occured: Unable to read execution data file /home/jenkins/workspace/KIE/main/pullrequest/droolsjbpm-integration-main.pr/bc/kiegroup_droolsjbpm_integration/target/jacoco.exec
```

I would merge this as soon as QE ack.

**Review by hellowdan — APPROVED** [review]

**Review by pibizza — APPROVED** [review]

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
