### PR TITLE
[AF-1668]: Fixed wrong infinispan configuration file. Also tests fixed

### PR DESCRIPTION
**Pull request by adrielparedes**
@ederign @jhrcek This fixes test in master. I had to update infinispan configuration file.
 Would you mind to review?

### CODE REVIEW

**Comment by jhrcek** [comment]
Compilation error that seems unrelated to this PR:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project kie-spring: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-integration-pullrequests/kie-spring/src/test/java/org/kie/spring/jbpm/AbstractJbpmSpringTest.java:[30,26] cannot find symbol
[ERROR]   symbol:   class PoolingDataSource
[ERROR]   location: package org.jbpm.test.util
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-integration-pullrequests/kie-spring/src/test/java/org/kie/spring/jbpm/AbstractJbpmSpringTest.java:[34,22] cannot find symbol
[ERROR]   symbol:   class PoolingDataSource
[ERROR]   location: class org.kie.spring.jbpm.AbstractJbpmSpringTest
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-integration-pullrequests/kie-spring/src/test/java/org/kie/spring/jbpm/AbstractJbpmSpringTest.java:[67,22] cannot find symbol
[ERROR]   symbol:   class PoolingDataSource
[ERROR]   location: class org.kie.spring.jbpm.AbstractJbpmSpringTest
[ERROR] -> [Help 1]
```

jenkins retest this

**Comment by jhrcek** [comment]
Master is currently broken. See https://github.com/kiegroup/jbpm/pull/1360#issuecomment-434943508

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by jhrcek** [comment]
The build won't work until https://github.com/kiegroup/droolsjbpm-integration/pull/1620 is merged (and then this PR rebased onto master).

**Comment by ederign** [comment]
jenkins retest this

**Pull request merged**
