### PR TITLE
Revert "Refactor KJar builds for Kie server tests to use installed Ma…

### PR DESCRIPTION
**Pull request by sutaakar**
…ven binary (#2019)"

This reverts commit 1351e1d55e06d288c7a051b73a6b5c807b57a1d5.

### CODE REVIEW

**Comment by sutaakar** [comment]
@tarilabs I need to temporarily revert the fix as it breaks downstream builds.

**Comment by sutaakar** [comment]
@lucamolteni Can you please ack/merge this?

**Comment by lucamolteni** [comment]
@mariofusco please merge this

**Comment by sutaakar** [comment]
To be replaced by https://github.com/kiegroup/droolsjbpm-integration/pull/2025

**Comment by mariofusco** [comment]
replaced by https://github.com/kiegroup/droolsjbpm-integration/pull/2025

**Pull request closed without merging**
