### PR TITLE
(GSS) [7.44.x] [RHPAM-3219] No Model definition in KIE Server Swagger API

### PR DESCRIPTION
**Pull request by fjtirado**
Moving response to ApiResponse

**Depends on**
[#droolsjbpm-build-bootstrap:1527](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1527)

**JIRA**: 

[RHPAM-3219](https://issues.redhat.com/browse/RHPAM-3219)

### CODE REVIEW

**Comment by MarianMacik** [comment]
@fjtirado can you please incorporate #2294? The explanation is in the PR description. Thanks!

**Review by elguardian — CHANGES_REQUESTED** [review]
@fjtirado plz check @MarianMacik  comment.

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by MarianMacik** [comment]
@fjtirado Can you please add missing ignores? I think we are missing something like
```json
{
  "code": "java.annotation.added",
  "annotationType": "io.swagger.annotations.ApiOperation",
  "elementKind": "method",
  "classSimpleName": "CaseQueryResource",
  "justification": "[JBPM-9410] No Model definition in KIE Server Swagger API"
}
```
for the case-mgmt module

and

```json
{
  "code": "java.annotation.added",
  "annotationType": "io.swagger.annotations.ApiOperation",
  "elementKind": "method",
  "classSimpleName": "RuntimeDataResource",
  "justification": "[JBPM-9410] No Model definition in KIE Server Swagger API"
}
```
for the jbpm module.

**Comment by fjtirado** [comment]
@kiegroup/gatekeepers Failed test seems unrelated, can we merge this?

**Comment by elguardian** [comment]
@fjtirado needs rebase.

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by elguardian** [comment]
@fjtirado can you check the error ?
12:20:25  Caused by: java.lang.IllegalStateException: /home/jenkins/workspace/KIE/7.44.x/pullrequest/droolsjbpm-integration-7.44.x.pullrequests/kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java:434:1: expecting RCURLY, found '<<'

**Pull request merged**
