### PR TITLE
AF-910

### PR DESCRIPTION
**Pull request by desmax74**
switched to the forked version of takari from https://github.com/desmax74/kie-soup/tree/AF-910

### CODE REVIEW

**Comment by desmax74** [comment]
@porcelli

**Comment by mswiderski** [comment]
@desmax74 is this still valid or can it be closed?

**Comment by desmax74** [comment]
@mswiderski is still valid until our merged PRs in Takari will be part of the next Takari release, @porcelli wdyt ?

**Comment by domhanak** [comment]
@desmax74 What is the current status of this PR? I see AF-910 already resolved.

**Comment by desmax74** [comment]
@domhanak this is outdated and will be replaced with the PR from @porcelli with takari 1.13.5 with our changes inside

**Pull request closed without merging**
