### PR TITLE
[7.52.x] [JBPM-9745] The REST API (queries/tasks/instances)returns an empty list if we set BYPASS_AUTH_USER to true

### PR DESCRIPTION
**Pull request by abhijithumbe**
…st if we set BYPASS_AUTH_USER to true

**JIRA**: _(https://issues.redhat.com/browse/RHPAM-3712)_

### CODE REVIEW

**Comment by elguardian** [comment]
@abhijithumbe please rebase.

**Comment by mareknovotny** [comment]
jenkins retest this please

**Review by afalhambra — CHANGES_REQUESTED** [review]
@abhijithumbe please make the changes accordingly as per its counterpart one already merged in master https://github.com/kiegroup/droolsjbpm-integration/pull/2490
Thanks!

**Comment by elguardian** [comment]
@afalhambra 
you merged that fix in 7.52
https://github.com/kiegroup/droolsjbpm-integration/commit/a2208ce38cbe62fb402ff622cafc590425d0d904

**Pull request merged**
