### PR TITLE
RHBRMS-3033: trying to use only bundled com.fasterxml.jackson libs

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/RHBRMS-3033

This is one point to fix kie-server, I am not sure if there are more such deployment to need exclusions like this

### CODE REVIEW

**Comment by mareknovotny** [comment]
@psiroky of course, I did a safe tryout ;)
I will clean them

**Comment by psiroky** [comment]
@mswiderski could you please take a look? I believe this should be ready to go.

**Comment by mswiderski** [comment]
this might fix kie server itself but won't fix controller/workbench which the jira is actually about see this stack trace https://issues.jboss.org/secure/attachment/12426417/stacktrace.txt

So please make sure that it will work with workbench... which I believe it won't as by excluding jackson from EAP/WildFly module it will essentially break workbench REST API. But I might be wrong...

**Comment by mareknovotny** [comment]
@mswiderski is there a integration test for that? I ran the mentioned kie-server-integ-tests-common module against EAP7.1.

And excluding of jackson is just the module, but there is bundled one in the app(s). I hope it is in controller/workbench too, but I can be wrong ;)

**Comment by sutaakar** [comment]
@mareknovotny Please try to run integration tests in kie-server-integ-tests-controller module. This module contains integration tests for standalone controller with Kie server.

**Comment by mswiderski** [comment]
@mareknovotny I don't think we have integration test that tests it with workbench. 

The issue I see is that workbench has REST api to for example create org unit, new project, compile it etc. (https://github.com/kiegroup/appformer/blob/master/uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java#L490) And it by defaults completely rely on application server JAX-RS features meaning it will expect payload to be transformed to given object before it actually reaches the application code. So if we exclude it (jackson) on workbench side I believe it will not find the right jars or it might find those that are not compatible anyway.

So the way is to test this with workbench to be completely sure it does work. Which I think it won't as this exclusion is only on kie server side.

**Comment by mareknovotny** [comment]
@sutaakar that is ran in the full test build on the PR verification or not?

**Comment by mareknovotny** [comment]
@mswiderski I will try to test it manually then. Thanks for the head up

**Comment by sutaakar** [comment]
@mareknovotny Yes, it is. Just PR build runs against WildFly10/EAP7.0 , it would be good to run the module also with WildFly11/EAP7.1

**Comment by mareknovotny** [comment]
closing as we will use what @mswiderski sent in   https://github.com/kiegroup/droolsjbpm-integration/pull/1299

**Pull request closed without merging**
